import type { Playbook } from '../../domain/types';

export const comingOfAgeCn: Playbook = {
  id: 'coming-of-age-cn',
  title: 'Growing up · ages 16–22 · China',
  summary:
    'ID card, adulthood at 18, military service registration, driving, first job, tax and the legal marriage age in mainland China. National rules; local offices set the details.',
  region: 'China',
  country: 'CN',
  family: 'coming-of-age',
  anchorKind: 'born',
  ages: { from: 16, to: 22 },
  conditions: [
    'For a Chinese citizen living in mainland China, from 16 to 22',
    'Some steps apply only to men, drivers or people with a job',
  ],
  reviewedAt: '2026-09-27',
  version: 1,
  sources: [
    {
      title: 'Resident Identity Card Law of the PRC (2003 text) — gov.cn',
      url: 'https://www.gov.cn/gongbao/content/2003/content_62254.htm',
    },
    {
      title: 'Resident Identity Card Law of the PRC (2011 amendment, fingerprints) — National People\'s Congress',
      url: 'http://www.npc.gov.cn/zgrdw/npc/xinwen/2011-10/31/content_1678466_2.htm',
    },
    {
      title: 'Civil Code Articles 17 and 18 explained — Yiyang government',
      url: 'http://dth.yiyang.gov.cn/30176/30211/30215/content_1328977.html',
    },
    {
      title: 'What is the legal marriage age under the Civil Code? — Wuhan Civil Affairs Bureau',
      url: 'https://mzj.wuhan.gov.cn/zwgk_918/zc/zcwd/202111/t20211110_1830765.shtml',
    },
    {
      title: 'Electoral Law of the NPC and Local People\'s Congresses — National People\'s Congress',
      url: 'http://www.npc.gov.cn/npc/c2/c30834/202011/t20201119_308799.html',
    },
    {
      title: 'Military Service Law of the PRC (2021) — National Conscription Office',
      url: 'https://www.gfbzb.gov.cn/zbbm/zcfg/byfg/202108/20210821/2100962138.html',
    },
    {
      title: 'Military service registration (兵役登记) — National Conscription Office',
      url: 'https://www.gfbzb.gov.cn/bydj/',
    },
    {
      title: 'Personal bank account classification explained — People\'s Bank of China, Xi\'an branch',
      url: 'https://xian.pbc.gov.cn/xian/129483/132864/3202066/index.html',
    },
    {
      title: 'Telephone user real-name registration rules (MIIT Order 25) — gov.cn',
      url: 'https://www.gov.cn/zhengce/2022-08/23/content_5722716.htm',
    },
    {
      title: 'Motor Vehicle Driving Licence Application and Use Provisions (MPS Order 162) — gov.cn',
      url: 'https://www.gov.cn/gongbao/content/2022/content_5679696.htm',
    },
    {
      title: 'Traffic Safety Integrated Service Platform (交管12123) — Ministry of Public Security',
      url: 'https://www.122.gov.cn/',
    },
    {
      title: 'Social Insurance Law of the PRC — State Taxation Administration law library',
      url: 'https://fgk.chinatax.gov.cn/zcfgk/c100009/c5192937/content.html',
    },
    {
      title: 'Regulations on the Management of Housing Provident Fund — gov.cn',
      url: 'https://www.gov.cn/gongbao/content/2019/content_5468861.htm',
    },
    {
      title: 'When to do the annual individual income tax reconciliation — Shanxi Tax Service, State Taxation Administration',
      url: 'http://shanxi.chinatax.gov.cn/web/detail/sx-11400-548-1805765',
    },
  ],
  steps: [
    {
      id: 'id-card',
      title: 'Apply for the resident ID card (居民身份证) at 16',
      offsetDays: 5934,
      durationDays: 30,
      validForDays: 3652,
      dependsOn: [],
      documents: ['Resident ID card'],
      prepare: ['Household register (户口簿)', 'ID card application form (居民身份证申领登记表)', 'Old card, if they had one as a child'],
      ages: { from: 16, to: 16 },
      howTo:
        '1. Under the Resident ID Card Law, Chinese citizens living in China apply for a card from 16; under 16 it is optional and a guardian applies.\n2. The law gives 3 months from the 16th birthday to apply to the police (公安机关) where the hukou is registered.\n3. Fingerprints are recorded when applying.\n4. Cards issued under 16 are valid for 5 years; from 16 to 25, 10 years; from 26 to 45, 20 years; from 46, long-term.\n5. The card is later needed for gaokao registration, bank accounts, phone numbers and driving tests.',
    },
    {
      id: 'majority',
      title: 'Turn 18: full civil capacity (完全民事行为能力人)',
      offsetDays: 6574,
      durationDays: 1,
      dependsOn: [],
      documents: [],
      prepare: ['Talk through contracts, money and responsibility now in their own name'],
      ages: { from: 18, to: 18 },
      howTo:
        '1. Under the Civil Code, a person of 18 or over is an adult with full civil capacity and can enter civil legal acts alone.\n2. A 16- or 17-year-old whose main income is their own labour is treated as having full civil capacity too.',
    },
    {
      id: 'voter',
      title: 'Check voter registration (选民登记) for local elections',
      offsetDays: 6604,
      durationDays: 14,
      dependsOn: ['majority'],
      documents: [],
      prepare: ['Resident ID card', 'Where they live or work now'],
      ages: { from: 18, to: 22 },
      conditions: ['Only when a direct local people\'s congress election is held where they live'],
      howTo:
        '1. Citizens of 18 or over have the right to vote and to stand for election.\n2. Deputies to county and township people\'s congresses are elected directly by voters.\n3. Registration is by electoral district and stays valid; before each election the list adds people who have turned 18 since the last one.\n4. After moving, ask the local election office where they are registered.',
    },
    {
      id: 'bank-account',
      title: 'Open a bank account in their own name (Class I, Ⅰ类户)',
      offsetDays: 6604,
      durationDays: 14,
      dependsOn: ['majority'],
      documents: ['Bank card for a Class I account'],
      prepare: ['Resident ID card', 'Mobile number in their own name'],
      ages: { from: 18, to: 18 },
      howTo:
        '1. Personal accounts come in 3 classes: Class I is opened at a bank counter with an in-person identity check and has full functions.\n2. Class II and III accounts can be opened online with limited functions and are linked to a Class I account.\n3. One person can hold only one Class I account at each bank.\n4. Salary, social insurance, housing provident fund and large transfers go through a Class I account.',
    },
    {
      id: 'phone',
      title: 'Get a mobile number in their own name',
      offsetDays: 6604,
      durationDays: 7,
      dependsOn: ['majority'],
      documents: ['Mobile number registered to them'],
      prepare: ['Resident ID card', 'Choose an operator and plan'],
      ages: { from: 18, to: 18 },
      howTo:
        '1. Operators ask for a valid ID and register the user\'s real identity when a number is set up.\n2. A number in their own name is used for bank, tax and government app logins.\n3. For a number already registered to a parent, ask the operator how to move it.',
    },
    {
      id: 'military-registration',
      title: 'Complete the initial military service registration (兵役登记)',
      offsetDays: 6574,
      durationDays: 30,
      dependsOn: [],
      documents: ['Military service registration certificate (兵役登记证)'],
      prepare: ['Resident ID card', 'Account on the National Conscription Office site (全国征兵网)'],
      ages: { from: 17, to: 18 },
      conditions: ['Only for men'],
      howTo:
        '1. Under the Military Service Law, men who turn 18 by December 31 do the initial registration that year, as the local military service office arranges.\n2. It can be done online or in person at a registration point.\n3. The National Conscription Office lists the window as January 1 to October 31; this date assumes the 18th birthday, so move it to fall inside the window of the year they turn 18.\n4. Registering is not enlisting; those who want to serve apply separately online.\n5. The initial registration is for men; the law lets the army take women into service according to its needs.',
    },
    {
      id: 'driving-theory',
      title: 'Join a driving school and pass the theory test (科目一)',
      offsetDays: 6634,
      durationDays: 60,
      validForDays: 1095,
      dependsOn: ['majority'],
      documents: ['Learner permit (学习驾驶证明)'],
      prepare: ['Resident ID card', 'Health check the vehicle office asks for', 'Compare driving schools', 'Account on 交管12123'],
      ages: { from: 18, to: 18 },
      conditions: ['Only if they want to drive'],
      howTo:
        '1. The small car licence (小型汽车, C1, or automatic, C2) is open from 18.\n2. The theory test (科目一) on traffic law is marked out of 100; 90 passes.\n3. The vehicle office issues the learner permit within a day of passing; it is valid for 3 years.\n4. All subjects have to be passed while the permit is valid, or passed subjects are void.',
    },
    {
      id: 'driving-skills',
      title: 'Pass the site test (科目二) and road test (科目三)',
      offsetDays: 6754,
      durationDays: 90,
      dependsOn: ['driving-theory'],
      documents: ['Test results'],
      prepare: ['Practice hours with the driving school', 'Test bookings on 交管12123'],
      ages: { from: 18, to: 18 },
      conditions: ['Only if they want to drive'],
      howTo:
        '1. For a C1 small car, the site test can be booked 10 days after getting the learner permit and the road test 30 days after (20 days for C2).\n2. The site test passes at 80 of 100 for small cars; the road test at 90.\n3. Each sitting allows one retake; after failing both, rebook after 10 days.\n4. Each of the two tests can be booked at most 5 times while the permit is valid; failing the 5th time voids the other passed subjects.\n5. This date is an estimate.',
    },
    {
      id: 'driving-licence',
      title: 'Pass the safe driving knowledge test (科目四) and get the licence (机动车驾驶证)',
      offsetDays: 6790,
      durationDays: 30,
      dependsOn: ['driving-skills'],
      documents: ['Driving licence'],
      prepare: ['Practice questions on safe and civil driving'],
      ages: { from: 18, to: 18 },
      conditions: ['Only if they want to drive'],
      howTo:
        '1. Officially this is the second part of subject 3 (安全文明驾驶常识), commonly called 科目四; it can be sat the same day both driving tests are passed.\n2. It is marked out of 100; 90 passes. Failing it keeps the road test pass.\n3. The licence can also be held in electronic form on 交管12123.',
    },
    {
      id: 'probation',
      title: 'Drive out the 12-month probation period (实习期)',
      offsetDays: 7160,
      durationDays: 365,
      dependsOn: ['driving-licence'],
      documents: ['Probation sign (实习标志)'],
      prepare: ['Put the probation sign on the back of the car'],
      ages: { from: 18, to: 19 },
      conditions: ['Only if they drive'],
      howTo:
        '1. The first 12 months after a first car licence are the probation period, with the standard probation sign on the back of the car.\n2. During it: no buses, passenger transport, emergency vehicles or dangerous goods, and no towing a trailer.\n3. On an expressway, a driver who has held a covering licence for 3 years or more rides along.\n4. Reaching 12 points during probation cancels the licence class.',
    },
    {
      id: 'marriage-age',
      title: 'Note the legal marriage age (法定婚龄)',
      offsetDays: 7305,
      durationDays: 1,
      dependsOn: [],
      documents: [],
      prepare: [],
      ages: { from: 20, to: 22 },
      howTo: '1. Under Article 1047 of the Civil Code, men can marry from 22 and women from 20.',
    },
    {
      id: 'social-insurance',
      title: 'Check social insurance is set up with the first job (社会保险)',
      offsetDays: 7700,
      durationDays: 30,
      dependsOn: [],
      documents: ['Social insurance record'],
      prepare: ['Resident ID card', 'Class I bank account', 'Employment contract'],
      ages: { from: 18, to: 22 },
      conditions: ['Only once they start a job with an employer'],
      howTo:
        '1. Under the Social Insurance Law, the employer applies for the employee\'s social insurance registration within 30 days of the start date.\n2. Self-employed people and flexible workers can register themselves.\n3. This date assumes a first job at about 21; move it to the real start date.',
    },
    {
      id: 'provident-fund',
      title: 'Check the housing provident fund account is opened (住房公积金)',
      offsetDays: 7700,
      durationDays: 30,
      dependsOn: [],
      documents: ['Housing provident fund account'],
      prepare: ['Resident ID card', 'Employment contract'],
      ages: { from: 18, to: 22 },
      conditions: ['Only once they start a job with an employer'],
      howTo:
        '1. Under the provident fund regulations, an employer registers a new employee with the housing provident fund centre within 30 days of hiring and opens or transfers their account.\n2. This date assumes a first job at about 21; move it to the real start date.',
    },
    {
      id: 'tax-app',
      title: 'Register on the individual income tax app (个人所得税)',
      offsetDays: 7700,
      durationDays: 14,
      dependsOn: [],
      documents: ['Individual income tax app account'],
      prepare: ['Resident ID card', 'Mobile number in their own name', 'Class I bank card for refunds'],
      ages: { from: 18, to: 22 },
      conditions: ['Only once they have earned income, e.g. from a job'],
      howTo:
        '1. Employers withhold tax from pay; the app shows income and tax reported under their ID.\n2. This date assumes a first job at about 21; move it to the real start date.',
    },
    {
      id: 'tax-reconciliation',
      title: 'Do the annual income tax reconciliation (年度汇算)',
      offsetDays: 8030,
      durationDays: 120,
      dependsOn: ['tax-app'],
      documents: ['Reconciliation result'],
      prepare: ['Special additional deductions (专项附加扣除), if any', 'Class I bank card'],
      ages: { from: 21, to: 22 },
      conditions: ['Only once they have earned income, e.g. from a job'],
      howTo:
        '1. The reconciliation for a tax year runs from March 1 to June 30 of the following year, in the app.\n2. It settles a refund or extra tax; the tax authority sets who is required to file.\n3. Early in the window, the app may ask for a booking.\n4. This date assumes income the year they turn 21; move it to June 30 of the year after.',
    },
  ],
};
