import type { Playbook } from '../../domain/types';

export const comingOfAgeCa: Playbook = {
  id: 'coming-of-age-ca',
  title: 'Growing up · ages 14–19 · CA',
  summary:
    'IDs, first job, driving, voting and first accounts from 14 to 19. Federal rules apply across Canada; provincial rules are Ontario\'s.',
  region: 'Ontario, Canada',
  anchorKind: 'born',
  ages: { from: 14, to: 19 },
  conditions: [
    'For a young person living in Ontario, from 14 to 19',
    'Some steps are only for Canadian citizens or residents',
  ],
  reviewedAt: '2026-09-26',
  version: 1,
  sources: [
    {
      title: 'Register of Future Electors — Elections Canada',
      url: 'https://www.elections.ca/content.aspx?section=vot&dir=reg/fut&document=index&lang=e',
    },
    {
      title: 'Register to vote — Elections Canada',
      url: 'https://www.elections.ca/content.aspx?section=vot&dir=reg&document=index&lang=e',
    },
    {
      title: 'Minimum age to work — Ontario.ca',
      url: 'https://www.ontario.ca/page/minimum-age-work',
    },
    {
      title: 'Social Insurance Number: Apply — Canada.ca',
      url: 'https://www.canada.ca/en/employment-social-development/services/sin/apply.html',
    },
    {
      title: 'P105 — Students and Income Tax — Canada.ca',
      url: 'https://www.canada.ca/en/revenue-agency/services/forms-publications/publications/p105/p105-students-income-tax.html',
    },
    {
      title: 'Health card renewal — Ontario.ca',
      url: 'https://www.ontario.ca/page/health-card-renewal',
    },
    {
      title: 'Get a G driver\'s licence: new drivers — Ontario.ca',
      url: 'https://www.ontario.ca/page/get-g-drivers-licence-new-drivers',
    },
    {
      title: 'Ontario Photo Card — Ontario.ca',
      url: 'https://www.ontario.ca/page/ontario-photo-card',
    },
    {
      title: 'Age of Majority and Accountability Act — Ontario.ca',
      url: 'https://www.ontario.ca/laws/statute/90a07',
    },
    {
      title: 'Before you contribute to a TFSA — Canada.ca',
      url: 'https://www.canada.ca/en/revenue-agency/services/tax/individuals/topics/tax-free-savings-account/contributing/before.html',
    },
    {
      title: 'Opening your FHSAs — Canada.ca',
      url: 'https://www.canada.ca/en/revenue-agency/services/tax/individuals/topics/first-home-savings-account/opening-your-fhsas.html',
    },
    {
      title: 'Cannabis laws — Ontario.ca',
      url: 'https://www.ontario.ca/page/cannabis-laws',
    },
    {
      title: 'Opening a bank account — Canada.ca',
      url: 'https://www.canada.ca/en/financial-consumer-agency/services/banking/opening-bank-account.html',
    },
    {
      title: 'Joint credit cards — Canada.ca',
      url: 'https://www.canada.ca/en/financial-consumer-agency/services/credit-cards/joint-credit-card.html',
    },
  ],
  steps: [
    {
      id: 'work-ages',
      title: 'Check which jobs they can legally do',
      offsetDays: 5113,
      durationDays: 7,
      dependsOn: [],
      documents: [],
      prepare: ['Type of workplace for each job idea'],
      ages: { from: 14, to: 18 },
      howTo:
        '1. From 14: offices, stores, arenas and restaurant serving areas.\n2. From 15: factories, restaurant kitchens, repair shops, garages, warehouses and laundries.\n3. From 16: construction, logging and most surface mining.\n4. From 18: underground mines, window cleaning and a few others.\n5. Under 16s cannot work during school hours.',
    },
    {
      id: 'future-electors',
      title: 'Join the Register of Future Electors',
      offsetDays: 5143,
      durationDays: 7,
      dependsOn: [],
      documents: [],
      prepare: ['Home address'],
      ages: { from: 14, to: 17 },
      conditions: ['Only if they are a Canadian citizen'],
      howTo:
        '1. Canadian citizens aged 14 to 17 living in Canada can sign up with Elections Canada.\n2. At 18 they are registered to vote in the next federal election.',
    },
    {
      id: 'sin',
      title: 'Apply for a Social Insurance Number',
      offsetDays: 5143,
      durationDays: 30,
      dependsOn: [],
      documents: ['Social Insurance Number'],
      prepare: [
        'Primary identity document: birth certificate, citizenship certificate or PR card',
        'Secondary document with name and date of birth, such as a passport',
      ],
      ages: { from: 14, to: 17 },
      howTo:
        '1. Anyone 12 or older can apply for their own SIN; a parent can apply for a minor.\n2. Apply online, by mail or at a Service Canada office. There is no fee.\n3. No card is issued; the number is shown in My Service Canada Account.',
    },
    {
      id: 'tax-return',
      title: 'File a first income tax return',
      offsetDays: 5718,
      durationDays: 30,
      dependsOn: ['sin'],
      documents: ['T4 slips', 'Notice of assessment'],
      prepare: ['T4 from each employer', 'Tuition slips, if any'],
      ages: { from: 14, to: 19 },
      conditions: ['Only once they have earned income, e.g. from a first job'],
      howTo:
        '1. Returns are due April 30 of the following year; this date assumes income the year they turn 15, so move it to match.\n2. Filing gets back tax withheld from pay and records earned income for future RRSP deduction room.\n3. Filing every year also sets up the GST/HST credit, which students can get once they turn 19.',
    },
    {
      id: 'ohip-16',
      title: 'Renew the health card in person with a photo',
      offsetDays: 5874,
      durationDays: 30,
      dependsOn: [],
      documents: ['Ontario photo health card'],
      prepare: ['Renewal notice', 'Current health card', 'Proof of Ontario residency and identity'],
      ages: { from: 16, to: 16 },
      conditions: ['Only if they have an Ontario health card'],
      howTo:
        '1. Anyone turning 16 must renew their Ontario health card in person at ServiceOntario.\n2. A photo and signature are taken then.',
    },
    {
      id: 'g1',
      title: 'Get the G1 learner\'s licence',
      offsetDays: 5874,
      durationDays: 30,
      validForDays: 1826,
      dependsOn: [],
      documents: ['G1 licence'],
      prepare: ['Study the MTO Driver\'s Handbook', 'Original ID with legal name and date of birth'],
      ages: { from: 16, to: 19 },
      conditions: ['Only if they want to drive'],
      howTo:
        '1. The minimum age is 16.\n2. Pass a vision test and a knowledge test at a DriveTest centre.\n3. The whole graduated licensing process must be finished within 5 years or it starts over.',
    },
    {
      id: 'photo-card',
      title: 'Get an Ontario Photo Card as ID',
      offsetDays: 5904,
      durationDays: 30,
      validForDays: 1826,
      dependsOn: [],
      documents: ['Ontario Photo Card'],
      prepare: ['Original ID with legal name and date of birth, such as a birth certificate'],
      ages: { from: 16, to: 19 },
      conditions: ['Only if they don\'t have a driver\'s licence'],
      howTo:
        '1. Ontario residents 16 or older without a driver\'s licence can apply in person at ServiceOntario.\n2. The card is valid for 5 years.',
    },
    {
      id: 'driver-ed',
      title: 'Take a government-approved beginner driver education course',
      offsetDays: 5964,
      durationDays: 90,
      dependsOn: ['g1'],
      documents: ['Driver education certificate'],
      prepare: ['Compare approved driving schools'],
      ages: { from: 16, to: 17 },
      conditions: ['Only if they want to take the G2 road test sooner'],
      howTo: '1. Finishing an approved course lets them take the first road test after 8 months with a G1 instead of 12.',
    },
    {
      id: 'g2',
      title: 'Pass the G2 road test',
      offsetDays: 6239,
      durationDays: 30,
      dependsOn: ['g1'],
      documents: ['G2 licence'],
      prepare: ['Book the road test', 'Supervised practice hours'],
      ages: { from: 16, to: 19 },
      conditions: ['Only if they want to drive'],
      howTo:
        '1. The first road test is allowed after 12 months with a G1, or after 8 months with approved driver education.\n2. This date assumes 12 months; move it 4 months earlier after driver education.',
    },
    {
      id: 'g',
      title: 'Pass the G road test for a full licence',
      offsetDays: 6604,
      durationDays: 30,
      dependsOn: ['g2'],
      documents: ['G licence'],
      prepare: ['Book the road test', 'Highway driving practice'],
      ages: { from: 17, to: 19 },
      conditions: ['Only if they want to drive'],
      howTo: '1. The G test is allowed after 12 months with a G2.',
    },
    {
      id: 'majority',
      title: 'Turn 18: the age of majority in Ontario',
      offsetDays: 6574,
      durationDays: 1,
      dependsOn: [],
      documents: [],
      prepare: ['Talk through contracts, consent and money now in their own name'],
      ages: { from: 18, to: 18 },
      howTo: '1. In Ontario a person stops being a minor and becomes an adult at 18.',
    },
    {
      id: 'bank-credit',
      title: 'Open a bank account and credit card in their own name',
      offsetDays: 6604,
      durationDays: 30,
      dependsOn: ['majority'],
      documents: ['Bank account details', 'Credit card'],
      prepare: [
        'One document with name and address and one with name and date of birth',
        'Compare no-cost or low-cost student accounts',
      ],
      ages: { from: 18, to: 19 },
      howTo:
        '1. Banks need two ID documents from a reliable source, or one plus someone vouching.\n2. The primary cardholder of a credit card must be of the age of majority in their province.\n3. Purchases as an authorized user on a parent\'s card don\'t build their own credit history.',
    },
    {
      id: 'vote',
      title: 'Check registration and vote',
      offsetDays: 6604,
      durationDays: 14,
      dependsOn: [],
      documents: [],
      prepare: ['Current address'],
      ages: { from: 18, to: 19 },
      conditions: ['Only if they are a Canadian citizen'],
      howTo:
        '1. Canadian citizens 18 or older can vote in federal elections.\n2. Check or update registration with Elections Canada\'s online service; the tax return can also update it.',
    },
    {
      id: 'tfsa',
      title: 'Open a TFSA',
      offsetDays: 6634,
      durationDays: 14,
      dependsOn: ['sin', 'majority'],
      documents: ['TFSA account'],
      prepare: ['Social Insurance Number', 'Choose a bank or broker'],
      ages: { from: 18, to: 19 },
      conditions: ['Only if they are a resident of Canada'],
      howTo:
        '1. Residents of Canada with a valid SIN start building TFSA room the year they turn 18.\n2. Unused room carries forward, so opening later loses nothing.',
    },
    {
      id: 'fhsa',
      title: 'Consider opening an FHSA',
      offsetDays: 6664,
      durationDays: 14,
      dependsOn: ['sin', 'majority'],
      documents: ['FHSA account'],
      prepare: ['Social Insurance Number'],
      ages: { from: 18, to: 19 },
      conditions: [
        'Only if they are a resident of Canada',
        'Only if they are a first-time home buyer',
      ],
      howTo:
        '1. They must be 18 or older and a resident of Canada.\n2. They must not have lived in a home they owned in the current year or the 4 years before.\n3. FHSA room only starts once the account is opened, so opening early starts the clock even with no deposit.',
    },
    {
      id: 'legal-age-19',
      title: 'Turn 19: legal age for alcohol and cannabis',
      offsetDays: 6940,
      durationDays: 1,
      dependsOn: [],
      documents: [],
      prepare: ['Talk about safe use and never driving impaired'],
      ages: { from: 19, to: 19 },
      howTo: '1. In Ontario, 19 is the minimum age to buy, use or possess recreational cannabis, the same as for alcohol and tobacco.',
    },
  ],
};
