import type { Playbook } from '../../domain/types';

export const comingOfAgeBc: Playbook = {
  id: 'coming-of-age-bc',
  title: 'Growing up · ages 14–19 · British Columbia',
  summary:
    'IDs, first job, driving, voting and first accounts from 14 to 19. Federal rules apply across Canada; provincial rules are British Columbia\'s, where adulthood starts at 19.',
  region: 'British Columbia, Canada',
  province: 'BC',
  family: 'coming-of-age',
  anchorKind: 'born',
  ages: { from: 14, to: 19 },
  conditions: [
    'For a young person living in British Columbia, from 14 to 19',
    'Some steps are only for Canadian citizens or residents',
  ],
  reviewedAt: '2026-09-27',
  version: 1,
  sources: [
    {
      title: 'Hiring young people — Gov.bc.ca Employment Standards',
      url: 'https://www2.gov.bc.ca/gov/content/employment-business/employment-standards-advice/employment-standards/hiring/young-people',
    },
    {
      title: 'Hiring children under 16 years of age (ESA Part 2, Section 9) — Gov.bc.ca',
      url: 'https://www2.gov.bc.ca/gov/content/employment-business/employment-standards-advice/employment-standards/forms-resources/igm/esa-part-2-section-9',
    },
    {
      title: 'Register of Future Electors — Elections Canada',
      url: 'https://www.elections.ca/content.aspx?section=vot&dir=reg/fut&document=index&lang=e',
    },
    {
      title: 'Register to vote — Elections Canada',
      url: 'https://www.elections.ca/content.aspx?section=vot&dir=reg&document=index&lang=e',
    },
    {
      title: 'Future Voters — Elections BC',
      url: 'https://elections.bc.ca/resources/voters-list/future-voters/',
    },
    {
      title: 'Who can vote — Elections BC',
      url: 'https://elections.bc.ca/voting/what-you-need-to-vote/who-can-vote/',
    },
    {
      title: 'Social Insurance Number: Apply — Canada.ca',
      url: 'https://www.canada.ca/en/employment-social-development/services/sin/apply.html',
    },
    {
      title: 'P105 — Students and Income Tax — Canada.ca',
      url: 'https://www.canada.ca/en/revenue-agency/services/forms-publications/publications/p105/p105-students-income-tax.html',
    },
    {
      title: 'Get your L — ICBC',
      url: 'https://icbc.com/driver-licensing/new-drivers/Get-your-L',
    },
    {
      title: 'Graduated licensing — ICBC',
      url: 'https://icbc.com/driver-licensing/new-drivers/Graduated-licensing',
    },
    {
      title: 'Changes to the Graduated Licensing Program — ICBC',
      url: 'https://icbc.com/driver-licensing/new-drivers/graduated-licensing-program-changes',
    },
    {
      title: 'Apply for a BCID card — ICBC',
      url: 'https://icbc.com/driver-licensing/getting-licensed/Apply-for-a-bcid',
    },
    {
      title: 'Identification Card Regulation — BC Laws',
      url: 'https://www.bclaws.gov.bc.ca/civix/document/id/complete/statreg/4_2013',
    },
    {
      title: 'Your BC Services Card — Gov.bc.ca',
      url: 'https://www2.gov.bc.ca/gov/content/health/health-drug-coverage/msp/bc-residents/personal-health-identification/your-bc-services-card',
    },
    {
      title: 'Which card to get — Gov.bc.ca',
      url: 'https://www2.gov.bc.ca/gov/content/governments/government-id/bc-services-card/your-card/find-out-card-type',
    },
    {
      title: 'Age of Majority Act — BC Laws',
      url: 'https://www.bclaws.gov.bc.ca/civix/document/id/complete/statreg/96007_01',
    },
    {
      title: 'Opening a TFSA — Canada.ca',
      url: 'https://www.canada.ca/en/revenue-agency/services/tax/individuals/topics/tax-free-savings-account/opening.html',
    },
    {
      title: 'Opening your FHSAs — Canada.ca',
      url: 'https://www.canada.ca/en/revenue-agency/services/tax/individuals/topics/first-home-savings-account/opening-your-fhsas.html',
    },
    {
      title: 'Cannabis and youth — Gov.bc.ca',
      url: 'https://www2.gov.bc.ca/gov/content/safety/public-safety/cannabis/cannabis-and-youth',
    },
    {
      title: 'LCRB frequently asked questions — Gov.bc.ca',
      url: 'https://www2.gov.bc.ca/gov/content/employment-business/business/liquor-regulation-licensing/liquor-licence-permits/liquor-resources-information/lcrb-faq',
    },
    {
      title: 'Opening a bank account — Canada.ca',
      url: 'https://www.canada.ca/en/financial-consumer-agency/services/banking/opening-bank-account.html',
    },
    {
      title: 'Joint credit cards — Canada.ca',
      url: 'https://www.canada.ca/en/financial-consumer-agency/services/credit-cards/joint-credit-card.html',
    },
  ],
  steps: [
    {
      id: 'work-ages',
      title: 'Check which jobs they can legally do',
      offsetDays: 5113,
      durationDays: 7,
      dependsOn: [],
      documents: [],
      prepare: ['Type of workplace and tasks for each job idea'],
      ages: { from: 14, to: 18 },
      howTo:
        '1. At 14 and 15: "light work" such as cashier, server of food, lifeguard, tutor, stocking shelves or dishwashing, with a parent\'s written consent.\n2. Other jobs at 14 or 15 also need a permit from the Employment Standards Branch.\n3. From 16: no parental consent needed, but construction and silviculture stay off-limits until 16.\n4. Under 18: no logging, tree falling, chainsaw work or power line work.',
    },
    {
      id: 'work-consent',
      title: 'Sign the written consent for a first job at 14 or 15',
      offsetDays: 5143,
      durationDays: 7,
      dependsOn: ['work-ages'],
      documents: ['Signed parental consent'],
      prepare: ['Job offer with duties and hours', 'Proof of age for the employer'],
      ages: { from: 14, to: 15 },
      conditions: ['Only if they take a job before turning 16'],
      howTo:
        '1. The employer keeps the parent\'s written consent and proof of age on file.\n2. At 14 and 15 they cannot work during school hours, more than 4 hours on a school day, more than 7 hours on a non-school day, or more than 20 hours in a week with 5 school days.',
    },
    {
      id: 'future-electors',
      title: 'Join the Register of Future Electors',
      offsetDays: 5143,
      durationDays: 7,
      dependsOn: [],
      documents: [],
      prepare: ['Home address'],
      ages: { from: 14, to: 17 },
      conditions: ['Only if they are a Canadian citizen'],
      howTo:
        '1. Canadian citizens aged 14 to 17 living in Canada can sign up with Elections Canada.\n2. At 18 they are registered to vote in the next federal election.',
    },
    {
      id: 'sin',
      title: 'Apply for a Social Insurance Number',
      offsetDays: 5143,
      durationDays: 30,
      dependsOn: [],
      documents: ['Social Insurance Number'],
      prepare: [
        'Primary identity document: birth certificate, citizenship certificate or PR card',
        'Secondary document with name and date of birth, such as a passport',
      ],
      ages: { from: 14, to: 17 },
      howTo:
        '1. Anyone 12 or older can apply for their own SIN; a parent can apply for a minor.\n2. Apply online, by mail or at a Service Canada office. There is no fee.\n3. No card is issued; the number is shown in My Service Canada Account.',
    },
    {
      id: 'bcid',
      title: 'Get a BCID card as photo ID',
      offsetDays: 5174,
      durationDays: 30,
      validForDays: 1826,
      dependsOn: [],
      documents: ['BCID card'],
      prepare: ['Original ID with legal name and date of birth, such as a birth certificate', 'A parent or guardian to consent'],
      ages: { from: 14, to: 19 },
      conditions: ['Only if they don\'t have a driver\'s licence'],
      howTo:
        '1. Anyone 12 or older can apply at an ICBC driver licensing office.\n2. Under 19, a parent or guardian consents to the application.\n3. The card is valid for about 5 years, ending on the birthday nearest 5 years from issue.',
    },
    {
      id: 'tax-return',
      title: 'File a first income tax return',
      offsetDays: 5718,
      durationDays: 30,
      dependsOn: ['sin'],
      documents: ['T4 slips', 'Notice of assessment'],
      prepare: ['T4 from each employer', 'Tuition slips, if any'],
      ages: { from: 14, to: 19 },
      conditions: ['Only once they have earned income, e.g. from a first job'],
      howTo:
        '1. Returns are due April 30 of the following year; this date assumes income the year they turn 15, so move it to match.\n2. Filing gets back tax withheld from pay and records earned income for future RRSP deduction room.\n3. Filing every year also sets up the GST/HST credit, which students can get once they turn 19.',
    },
    {
      id: 'bc-future-voters',
      title: 'Join Elections BC\'s List of Future Voters',
      offsetDays: 5874,
      durationDays: 7,
      dependsOn: [],
      documents: [],
      prepare: ['Home address'],
      ages: { from: 16, to: 17 },
      conditions: ['Only if they are a Canadian citizen'],
      howTo:
        '1. Canadian citizens who are 16 or 17 and live in BC can sign up online with Elections BC.\n2. At 18 they are added to the Provincial Voters List automatically.',
    },
    {
      id: 'learner',
      title: 'Get the L learner\'s licence',
      offsetDays: 5874,
      durationDays: 30,
      validForDays: 730,
      dependsOn: [],
      documents: ['Learner\'s licence'],
      prepare: ['Study Learn to Drive Smart', 'Try ICBC\'s practice knowledge test', 'Original ID', 'Parent or guardian consent'],
      ages: { from: 16, to: 19 },
      conditions: ['Only if they want to drive'],
      howTo:
        '1. The L is available on or after the 16th birthday.\n2. Pass a vision screening and a knowledge test: 40 of 50 questions right.\n3. Under 19, a parent or guardian signs consent.\n4. The L is valid for 2 years; renewing it means passing the knowledge test again.',
    },
    {
      id: 'driver-training',
      title: 'Take an ICBC-approved driver training course',
      offsetDays: 5964,
      durationDays: 90,
      dependsOn: ['learner'],
      documents: ['Course completion certificate'],
      prepare: ['Compare ICBC-approved driving schools'],
      ages: { from: 16, to: 17 },
      conditions: ['Only if they want a shorter novice stage'],
      howTo:
        '1. Finishing an approved course during the L stage, within 365 days of starting it, can cut the 24-month N stage to 18 months.\n2. The shorter stage applies only while they stay free of violations and at-fault crashes.',
    },
    {
      id: 'novice',
      title: 'Pass the road test for the N novice licence',
      offsetDays: 6239,
      durationDays: 30,
      dependsOn: ['learner'],
      documents: ['Novice licence'],
      prepare: ['Book the road test', 'A year of supervised practice'],
      ages: { from: 17, to: 19 },
      conditions: ['Only if they want to drive'],
      howTo: '1. The road test is allowed after at least 12 months of practice on the L with a qualified supervisor.',
    },
    {
      id: 'vote',
      title: 'Check registration and vote',
      offsetDays: 6604,
      durationDays: 14,
      dependsOn: [],
      documents: [],
      prepare: ['Current address'],
      ages: { from: 18, to: 19 },
      conditions: ['Only if they are a Canadian citizen'],
      howTo:
        '1. Canadian citizens 18 or older can vote in federal elections and, once they have lived in BC for 6 months, in BC provincial elections.\n2. Check or update federal registration with Elections Canada and provincial registration with Elections BC online.\n3. Updating a driver\'s licence, BCID or BC Services Card address also updates Elections BC.',
    },
    {
      id: 'full-licence',
      title: 'Upgrade to a full Class 5 licence',
      offsetDays: 6969,
      durationDays: 30,
      dependsOn: ['novice'],
      documents: ['Class 5 licence'],
      prepare: ['Driving record with no prohibitions or suspensions'],
      ages: { from: 18, to: 19 },
      conditions: ['Only if they want to drive'],
      howTo:
        '1. Drivers under 25 need at least 24 months of safe driving on the N, or 18 months after approved training.\n2. From October 19, 2026, a Driving Record Assessment replaces the second road test, followed by a 12-month restriction period.\n3. Speeding or phone convictions in that time, or any prohibition or suspension, block the upgrade.\n4. This date assumes 24 months; move it 6 months earlier after approved training.',
    },
    {
      id: 'photo-services-card',
      title: 'Get a photo BC Services Card',
      offsetDays: 6939,
      durationDays: 60,
      dependsOn: [],
      documents: ['Photo BC Services Card or combined driver\'s licence'],
      prepare: ['Letter from Health Insurance BC', 'ID documents the letter asks for'],
      ages: { from: 18, to: 19 },
      conditions: ['Only if they are enrolled in MSP'],
      howTo:
        '1. Under 19, MSP issues a non-photo BC Services Card and enrolment doesn\'t need renewing.\n2. Around 18 and a half, Health Insurance BC sends a letter to renew enrolment; the photo card is then issued at an ICBC driver licensing office.\n3. Drivers can combine the BC Services Card with their driver\'s licence.',
    },
    {
      id: 'majority',
      title: 'Turn 19: the age of majority in BC',
      offsetDays: 6939,
      durationDays: 1,
      dependsOn: [],
      documents: [],
      prepare: ['Talk through contracts, consent and money now in their own name'],
      ages: { from: 19, to: 19 },
      howTo:
        '1. In British Columbia a person becomes an adult at 19, a year later than federal ages such as voting at 18.\n2. Some contracts, such as a TFSA or a credit card, wait until then.',
    },
    {
      id: 'legal-age-19',
      title: 'Turn 19: legal age for alcohol and cannabis',
      offsetDays: 6939,
      durationDays: 1,
      dependsOn: [],
      documents: [],
      prepare: ['Talk about safe use and never driving impaired'],
      ages: { from: 19, to: 19 },
      howTo: '1. In BC, 19 is the minimum age to buy, possess or consume non-medical cannabis, the same as for liquor.',
    },
    {
      id: 'bank-credit',
      title: 'Get a credit card in their own name',
      offsetDays: 6969,
      durationDays: 30,
      dependsOn: ['majority'],
      documents: ['Bank account details', 'Credit card'],
      prepare: [
        'One document with name and address and one with name and date of birth',
        'Compare no-cost or low-cost student accounts',
      ],
      ages: { from: 19, to: 19 },
      howTo:
        '1. Banks need two ID documents from a reliable source, or one plus someone vouching.\n2. The primary cardholder of a credit card must be of the age of majority in their province, which is 19 in BC.\n3. Purchases as an authorized user on a parent\'s card don\'t build their own credit history.',
    },
    {
      id: 'tfsa',
      title: 'Open a TFSA',
      offsetDays: 6969,
      durationDays: 14,
      dependsOn: ['sin', 'majority'],
      documents: ['TFSA account'],
      prepare: ['Social Insurance Number', 'Choose a bank or broker'],
      ages: { from: 19, to: 19 },
      conditions: ['Only if they are a resident of Canada'],
      howTo:
        '1. TFSA room starts building the year they turn 18, if they are a resident of Canada with a valid SIN.\n2. In provinces where contracts need age 19, like BC, the account opens at 19 and the room from 18 carries over.\n3. Unused room carries forward, so opening later loses nothing.',
    },
    {
      id: 'fhsa',
      title: 'Consider opening an FHSA',
      offsetDays: 6999,
      durationDays: 14,
      dependsOn: ['sin', 'majority'],
      documents: ['FHSA account'],
      prepare: ['Social Insurance Number'],
      ages: { from: 19, to: 19 },
      conditions: [
        'Only if they are a resident of Canada',
        'Only if they are a first-time home buyer',
      ],
      howTo:
        '1. The FHSA opens at 18, or at 19 where that is the legal age to enter a contract, as in BC.\n2. They must not have lived in a home they owned in the current year or the 4 years before.\n3. FHSA room only starts once the account is opened, so opening early starts the clock even with no deposit.',
    },
  ],
};
