import type { Playbook } from '../../domain/types';

export const highSchoolBc: Playbook = {
  id: 'high-school-bc',
  title: 'High school · Grades 8–12 · British Columbia',
  summary:
    'Dogwood requirements, graduation assessments and post-secondary applications for a teen going through a BC public secondary school. Dates assume Grade 8 starts around age 13.',
  region: 'British Columbia, Canada',
  province: 'BC',
  family: 'high-school',
  anchorKind: 'born',
  ages: { from: 13, to: 18 },
  conditions: [
    'For a young person attending secondary school in British Columbia, Grades 8 to 12',
    'Working towards the BC Certificate of Graduation (Dogwood Diploma)',
  ],
  reviewedAt: '2026-09-27',
  version: 1,
  sources: [
    {
      title: 'Welcome to British Columbia: the school system — Gov.bc.ca',
      url: 'https://www2.gov.bc.ca/assets/gov/education/administration/kindergarten-to-grade-12/diverse-student-needs/educationwelcomeletter_jan2016_english_final.pdf',
    },
    {
      title: 'Certificates of Graduation — Gov.bc.ca',
      url: 'https://www2.gov.bc.ca/gov/content/education-training/k-12/support/graduation',
    },
    {
      title: 'Graduation Requirements policy — Gov.bc.ca',
      url: 'https://www2.gov.bc.ca/gov/content/education-training/k-12/administration/legislation-policy/public-schools/graduation-requirements',
    },
    {
      title: 'Indigenous-Focused Graduation Requirement — Gov.bc.ca',
      url: 'https://www2.gov.bc.ca/gov/content/education-training/k-12/support/indigenous-focused-graduation-requirements',
    },
    {
      title: 'Career-Life Connections — B.C. Curriculum',
      url: 'https://curriculum.gov.bc.ca/curriculum/career-education/all/career-life-connections',
    },
    {
      title: 'Graduation assessment information for parents and students — Gov.bc.ca',
      url: 'https://www2.gov.bc.ca/gov/content/education-training/k-12/support/curriculum-and-assessment/assessments/graduation',
    },
    {
      title: 'Apply — EducationPlannerBC',
      url: 'https://apply.educationplannerbc.ca/',
    },
    {
      title: 'Complete the application — UBC Undergraduate Admissions',
      url: 'https://you.ubc.ca/applying-ubc/how-to-apply/application/',
    },
    {
      title: 'Order a high school transcript or certificate as a current student — Gov.bc.ca',
      url: 'https://www2.gov.bc.ca/gov/content/education-training/k-12/support/transcripts-and-certificates/order-a-high-school-transcript-or-certificate',
    },
    {
      title: 'District/Authority Scholarships — Gov.bc.ca',
      url: 'https://www2.gov.bc.ca/gov/content/education-training/k-12/support/scholarships/provincial-scholarships/district-authority-scholarships',
    },
    {
      title: 'How to apply — StudentAid BC',
      url: 'https://studentaidbc.ca/apply/how-to-apply',
    },
    {
      title: 'Pay for education using the Registered Education Savings Plan — Canada.ca',
      url: 'https://www.canada.ca/en/employment-social-development/services/student-financial-aid/education-savings/resp/use.html',
    },
  ],
  steps: [
    {
      id: 'grade8-courses',
      title: 'Choose Grade 8 courses with the Grade 7 teacher',
      offsetDays: 4600,
      durationDays: 30,
      dependsOn: [],
      documents: [],
      prepare: ['District course guide', 'Grade 7 report card', 'Questions for the secondary school counsellor'],
      ages: { from: 12, to: 13 },
      howTo:
        '1. Most BC districts run secondary school from Grade 8 to 12; some start it at Grade 9 after a middle school, so check the district.\n2. Course selection usually happens in the winter or spring of Grade 7; schools set their own dates.\n3. Most students start Grade 8 in September of the year they turn 13, so move this step to the real date.',
    },
    {
      id: 'grade8-start',
      title: 'Start Grade 8',
      offsetDays: 4748,
      durationDays: 7,
      dependsOn: ['grade8-courses'],
      documents: ['Timetable'],
      prepare: ['School supply list', 'Locker and bus details', 'Counsellor\'s name'],
      ages: { from: 12, to: 13 },
      howTo: '1. The school year starts in September, the year the student turns 13 in most cases.',
    },
    {
      id: 'grad-plan',
      title: 'Choose Grade 10 courses and map out the 80 credits',
      offsetDays: 5358,
      durationDays: 30,
      dependsOn: ['grade8-start'],
      documents: [],
      prepare: ['List of required courses', 'Credits planned per grade', 'Meeting with the counsellor'],
      ages: { from: 14, to: 15 },
      howTo:
        '1. The Dogwood needs at least 80 credits from Grades 10 to 12: 52 from required courses and at least 28 elective credits.\n2. Required: Language Arts 10, 11 and 12; Math 10 and 11 or 12; Science 10 and 11 or 12; Social Studies 10 and 11 or 12; Physical and Health Education 10; an Arts Education or Applied Design, Skills and Technologies course; Career-Life Education; and Career-Life Connections.\n3. At least 16 credits must be at Grade 12 level, including a Language Arts 12 course and Career-Life Connections.\n4. The 3 graduation assessments and 4 Indigenous-focused credits are also needed.\n5. Course selection is usually in the winter of Grade 9; this date is an estimate.',
    },
    {
      id: 'numeracy-10',
      title: 'Write the Grade 10 Numeracy Assessment',
      offsetDays: 5768,
      durationDays: 30,
      dependsOn: ['grade8-start'],
      documents: ['Assessment result'],
      prepare: ['Session date from the school', 'Sample questions from the Ministry'],
      ages: { from: 15, to: 16 },
      howTo:
        '1. Writing it is a graduation requirement; it tests maths learned across subjects up to Grade 10.\n2. It is usually written in Grade 10; the school picks the session, so this due date is an estimate.\n3. It can be rewritten; the best result counts and goes on the transcript.',
    },
    {
      id: 'literacy-10',
      title: 'Write the Grade 10 Literacy Assessment',
      offsetDays: 5768,
      durationDays: 30,
      dependsOn: ['grade8-start'],
      documents: ['Assessment result'],
      prepare: ['Session date from the school', 'Sample questions from the Ministry'],
      ages: { from: 15, to: 16 },
      howTo:
        '1. Writing it is a graduation requirement.\n2. It is usually written in Grade 10; the school picks the session, so this due date is an estimate.\n3. It can be rewritten; the best result counts and goes on the transcript.',
    },
    {
      id: 'cle',
      title: 'Complete Career-Life Education',
      offsetDays: 5770,
      durationDays: 150,
      dependsOn: ['grad-plan'],
      documents: [],
      prepare: ['Ideas for university, college, trades or work'],
      ages: { from: 15, to: 16 },
      howTo:
        '1. Career-Life Education is a required 4-credit course.\n2. Many schools run it in Grade 10; this due date assumes the end of Grade 10, so move it to match the school.',
    },
    {
      id: 'grade11-courses',
      title: 'Choose Grade 11 courses to keep post-secondary options open',
      offsetDays: 5723,
      durationDays: 30,
      dependsOn: ['grad-plan'],
      documents: [],
      prepare: [
        'Programs of interest and their admission requirements',
        'Current marks',
        'Meeting with the counsellor',
      ],
      ages: { from: 15, to: 16 },
      howTo:
        '1. Post-secondary programs list specific Grade 11 and 12 courses, such as a particular Math or Science, as admission requirements.\n2. Some Grade 12 courses need a Grade 11 course first, so plan both years together.\n3. Course selection is usually in the winter of Grade 10; schools set their own dates.',
    },
    {
      id: 'grade12-courses',
      title: 'Choose Grade 12 courses to meet program requirements',
      offsetDays: 6089,
      durationDays: 30,
      dependsOn: ['grade11-courses'],
      documents: [],
      prepare: ['Admission requirements for each program on the shortlist', 'Credit count so far'],
      ages: { from: 16, to: 17 },
      howTo:
        '1. Check each program\'s required Grade 12 courses and minimum marks on the institution\'s site or EducationPlannerBC.\n2. Count at least 16 Grade 12 credits, including Language Arts 12 and Career-Life Connections.\n3. Course selection is usually in the winter of Grade 11.',
    },
    {
      id: 'indigenous-focused',
      title: 'Earn the 4 Indigenous-focused credits',
      offsetDays: 6130,
      durationDays: 300,
      dependsOn: ['grad-plan'],
      documents: [],
      prepare: ['List of Indigenous-focused courses the school offers'],
      ages: { from: 15, to: 17 },
      howTo:
        '1. Since 2023/24, every Dogwood student completes at least 4 credits of Indigenous-focused coursework; the 80-credit total stays the same.\n2. Options include provincial Indigenous-focused courses, First Nations language courses, approved local courses and some external credentials.\n3. Ask the school which of its courses also count towards another requirement.\n4. This due date assumes the end of Grade 11 and is an estimate.',
    },
    {
      id: 'scholarships',
      title: 'Apply for scholarships and awards',
      offsetDays: 6389,
      durationDays: 180,
      dependsOn: ['grade12-courses'],
      documents: ['Scholarship applications'],
      prepare: ['Reference letters', 'List of volunteering and activities', 'Short personal statements'],
      ages: { from: 17, to: 18 },
      howTo:
        '1. District/Authority Scholarships are provincial awards chosen by local committees for excellence in areas such as fine arts, athletics, trades, languages or community service; ask the school how to apply.\n2. Recipients hear in spring, are confirmed in September and get a tuition voucher in November; it has 5 years to be redeemed.\n3. Many post-secondary schools also have entrance awards with their own forms.\n4. Deadlines vary widely; this date is an estimate for spring of Grade 12.',
    },
    {
      id: 'epbc',
      title: 'Apply to BC post-secondary through EducationPlannerBC',
      offsetDays: 6345,
      durationDays: 60,
      dependsOn: ['grade12-courses'],
      documents: ['EducationPlannerBC application'],
      prepare: ['Program choices', 'Personal Education Number (PEN) from the school', 'Payment card'],
      ages: { from: 17, to: 18 },
      conditions: ['Only if they plan to go to a public college or university in BC'],
      howTo:
        '1. Most BC public post-secondary institutions take applications through EducationPlannerBC.\n2. Each institution sets its own deadlines; UBC\'s application opens in early October and closes January 15 for September entry.\n3. This due date assumes mid-January of Grade 12 and is an estimate; check each program.',
    },
    {
      id: 'transcript-send',
      title: 'Send the transcript to chosen schools through StudentTranscripts Service',
      offsetDays: 6375,
      durationDays: 14,
      dependsOn: ['epbc'],
      documents: ['Transcript order'],
      prepare: ['Basic BCeID account', 'List of institutions applied to'],
      ages: { from: 17, to: 18 },
      conditions: ['Only if they applied to post-secondary'],
      howTo:
        '1. Grade 12 students pick institutions in the StudentTranscripts Service between November and June of their graduation year.\n2. Choosing "Send Updates" lets the institution request updated marks until the date entered.\n3. This date is an estimate; some institutions ask for it with the application.',
    },
    {
      id: 'literacy-12',
      title: 'Write the Grade 12 Literacy Assessment',
      offsetDays: 6400,
      durationDays: 30,
      dependsOn: ['literacy-10'],
      documents: ['Assessment result'],
      prepare: ['Session date from the school', 'Sample questions from the Ministry'],
      ages: { from: 17, to: 18 },
      howTo:
        '1. Writing it is a graduation requirement.\n2. It is usually written in Grade 12; the school picks the session, so this due date is an estimate.\n3. It can be rewritten; the best result counts.',
    },
    {
      id: 'clc',
      title: 'Complete Career-Life Connections and the capstone',
      offsetDays: 6450,
      durationDays: 270,
      dependsOn: ['cle'],
      documents: ['Capstone project'],
      prepare: ['Log of career-life exploration hours', 'Capstone idea'],
      ages: { from: 17, to: 18 },
      howTo:
        '1. Career-Life Connections is a required 4-credit course and counts as a Grade 12 credit.\n2. It includes at least 30 hours of career-life exploration, such as work, volunteering, fieldwork or a passion project.\n3. It ends with a capstone project the student designs and presents.\n4. Schools spread it over Grades 11 and 12 differently; this date assumes spring of Grade 12.',
    },
    {
      id: 'studentaid-bc',
      title: 'Apply for StudentAid BC',
      offsetDays: 6514,
      durationDays: 42,
      dependsOn: [],
      documents: ['StudentAid BC application'],
      prepare: ['Social Insurance Number', 'BC Services Card account login', 'School and program', 'Parents\' financial information'],
      ages: { from: 17, to: 18 },
      conditions: ['Only if they need student financial aid for college or university'],
      howTo:
        '1. Applications for the next program year usually open in June.\n2. There is no need to wait for an offer; funding is released once the school confirms enrolment.\n3. Parents usually add their part through the Supporting Users Portal.\n4. Applying about 2 months before classes is an estimate that leaves time for funding to arrive.',
    },
    {
      id: 'dogwood',
      title: 'Graduate with the Dogwood Diploma',
      offsetDays: 6484,
      durationDays: 30,
      dependsOn: ['grad-plan', 'numeracy-10', 'literacy-10', 'literacy-12', 'cle', 'clc', 'indigenous-focused', 'grade12-courses'],
      documents: ['BC Certificate of Graduation (Dogwood Diploma)'],
      prepare: ['Credit count', 'Graduation ceremony date'],
      ages: { from: 17, to: 18 },
      howTo:
        '1. The Dogwood is awarded once the 80 credits, required courses, Indigenous-focused credits and 3 graduation assessments are all done.\n2. Most students finish in June of Grade 12; move this step to the real date.',
    },
    {
      id: 'transcript',
      title: 'Keep a copy of the transcript and Dogwood',
      offsetDays: 6514,
      durationDays: 14,
      dependsOn: ['dogwood'],
      documents: ['BC secondary school transcript'],
      prepare: ['Scan the diploma', 'Store both somewhere safe'],
      ages: { from: 17, to: 18 },
      howTo:
        '1. The transcript lists Grade 10 to 12 courses and assessment results.\n2. Later copies are ordered through the StudentTranscripts Service with a BCeID.',
    },
    {
      id: 'resp-eap',
      title: 'Request Educational Assistance Payments from the RESP',
      offsetDays: 6588,
      durationDays: 30,
      dependsOn: ['dogwood'],
      documents: ['Proof of enrolment'],
      prepare: ['RESP promoter contact', 'Tuition and costs estimate'],
      ages: { from: 18, to: 18 },
      conditions: ['Only if they have an RESP', 'Only if they enrol in a qualifying post-secondary program'],
      howTo:
        '1. The subscriber contacts the RESP promoter to request an EAP.\n2. The promoter needs official proof of enrolment.\n3. Full-time programs in Canada must run at least 3 weeks in a row with at least 10 hours a week.\n4. EAPs are taxable income for the student and can be paid up to 6 months after enrolment ends.',
    },
  ],
};
