import type { Playbook } from '../../domain/types';

export const highSchoolOn: Playbook = {
  id: 'high-school-on',
  title: 'High school · Grades 9–12 · Ontario',
  summary:
    'Diploma requirements, key tests and post-secondary applications for a teen going through an Ontario public high school. Dates assume Grade 9 starts around age 14.',
  region: 'Ontario, Canada',
  country: 'CA',
  province: 'ON',
  family: 'high-school',
  anchorKind: 'born',
  ages: { from: 13, to: 18 },
  conditions: [
    'For a young person attending high school in Ontario, Grades 9 to 12',
    'Working towards the Ontario Secondary School Diploma (OSSD)',
  ],
  reviewedAt: '2026-09-26',
  version: 1,
  sources: [
    {
      title: 'High school graduation requirements — Ontario.ca',
      url: 'https://www.ontario.ca/page/high-school-graduation-requirements',
    },
    {
      title: 'Getting ready for high school — Ontario.ca',
      url: 'https://www.ontario.ca/page/getting-ready-high-school',
    },
    {
      title: 'Ontario Secondary School Literacy Test (OSSLT) — EQAO',
      url: 'https://www.eqao.com/the-assessment/osslt/',
    },
    {
      title: 'Grade 10 Career Studies: a guide for parents — Ontario Ministry of Education',
      url: 'https://www.dcp.edu.gov.on.ca/en/glc2o-guide',
    },
    {
      title: 'Diploma and certificate requirements and related procedures — Ontario.ca',
      url: 'https://www.ontario.ca/document/ontario-schools-kindergarten-grade-12-policy-and-program-requirements/diploma-and-certificate-requirements-related-procedures',
    },
    {
      title: 'Ontario Student Transcript manual — Ontario.ca',
      url: 'https://www.ontario.ca/page/ontario-student-transcript-manual',
    },
    {
      title: 'Deadlines — Ontario Universities\' Application Centre',
      url: 'https://www.ouac.on.ca/planning/deadlines/',
    },
    {
      title: 'Important dates — ontariocolleges.ca',
      url: 'https://www.ontariocolleges.ca/en/apply/important-dates',
    },
    {
      title: 'How to apply for OSAP — Ontario.ca',
      url: 'https://www.ontario.ca/page/how-apply-osap',
    },
    {
      title: 'Pay for education using the Registered Education Savings Plan — Canada.ca',
      url: 'https://www.canada.ca/en/employment-social-development/services/student-financial-aid/education-savings/resp/use.html',
    },
  ],
  steps: [
    {
      id: 'grade9-courses',
      title: 'Choose Grade 9 courses with the Grade 8 teacher',
      offsetDays: 4900,
      durationDays: 30,
      dependsOn: [],
      documents: [],
      prepare: ['Board course calendar', 'Grade 8 report card', 'Questions for the guidance counsellor'],
      ages: { from: 13, to: 14 },
      howTo:
        '1. Course selection for Grade 9 usually happens in the winter of Grade 8; schools set their own dates.\n2. Most students start Grade 9 in September of the year they turn 14, so move this step to the real date.\n3. For students who started Grade 9 in 2024 or later, 1 technological education credit is compulsory in Grade 9 or 10.',
    },
    {
      id: 'hours-start',
      title: 'Start a log of community involvement hours',
      offsetDays: 5053,
      durationDays: 7,
      dependsOn: [],
      documents: ['Community involvement log'],
      prepare: ['School board\'s hours form', 'Supervisor name and contact for each activity'],
      ages: { from: 13, to: 14 },
      howTo:
        '1. The diploma needs at least 40 hours of community involvement (volunteering).\n2. Hours can be collected from the summer before Grade 9.\n3. Each board publishes its own form and list of eligible activities; get supervisors to sign as you go.',
    },
    {
      id: 'grade9-start',
      title: 'Start Grade 9',
      offsetDays: 5113,
      durationDays: 7,
      dependsOn: ['grade9-courses'],
      documents: ['Timetable'],
      prepare: ['School supply list', 'Locker and bus details', 'Guidance counsellor\'s name'],
      ages: { from: 13, to: 14 },
      howTo: '1. The school year starts in September, the year the student turns 14 in most cases.',
    },
    {
      id: 'ossd-plan',
      title: 'Map out the 30 credits and 2 online credits',
      offsetDays: 5143,
      durationDays: 30,
      dependsOn: ['grade9-start'],
      documents: [],
      prepare: ['List of compulsory credits', 'Credits already planned per grade'],
      ages: { from: 14, to: 15 },
      howTo:
        '1. The OSSD needs 30 credits: 17 compulsory and 13 optional for students who started Grade 9 in 2024 or later; 18 and 12 for earlier starters.\n2. At least 2 credits must be online learning credits; opting out is possible, and the student can opt out themselves at 18.\n3. Other requirements: 40 community hours and the literacy requirement.',
    },
    {
      id: 'osslt',
      title: 'Write the Ontario Secondary School Literacy Test',
      offsetDays: 5658,
      durationDays: 30,
      dependsOn: ['grade9-start'],
      documents: ['OSSLT result'],
      prepare: ['Test date from the school', 'Practice materials from EQAO'],
      ages: { from: 15, to: 16 },
      howTo:
        '1. Students usually write the OSSLT in Grade 10, their second year of high school.\n2. The school sets the date; this due date is an estimate.\n3. Passing it meets the diploma literacy requirement.',
    },
    {
      id: 'osslc',
      title: 'Take the literacy course (OSSLC) instead',
      offsetDays: 6209,
      durationDays: 150,
      dependsOn: ['osslt'],
      documents: ['OSSLC credit'],
      prepare: ['Talk to the guidance counsellor'],
      ages: { from: 16, to: 18 },
      conditions: ['Only if they have had two chances at the OSSLT and were unsuccessful at least once'],
      howTo:
        '1. The Ontario Secondary School Literacy Course meets the literacy requirement for students eligible under the EQAO rule.\n2. Ask the school about other ways to meet the requirement too.',
    },
    {
      id: 'career-studies',
      title: 'Complete Grade 10 Career Studies',
      offsetDays: 5750,
      durationDays: 150,
      dependsOn: ['grade9-start'],
      documents: [],
      prepare: ['Ideas for university, college, apprenticeship or work'],
      ages: { from: 15, to: 16 },
      howTo:
        '1. Career Studies (GLC2O) is a compulsory half-credit course taken in Grade 10.\n2. Schools run it in either semester; this due date assumes the end of Grade 10.',
    },
    {
      id: 'financial-literacy',
      title: 'Pass the financial literacy modules in Career Studies',
      offsetDays: 5750,
      durationDays: 150,
      dependsOn: ['grade9-start'],
      documents: [],
      prepare: [],
      ages: { from: 15, to: 16 },
      conditions: ['Only if they started Grade 9 in 2025–26 or later'],
      howTo:
        '1. Students need at least 70% on the financial literacy modules in Grade 10 Career Studies.\n2. There are 2 attempts.\n3. The requirement is in place from the 2026–27 school year.',
    },
    {
      id: 'grade11-courses',
      title: 'Choose Grade 11 courses to keep post-secondary options open',
      offsetDays: 5628,
      durationDays: 30,
      dependsOn: ['grade9-start'],
      documents: [],
      prepare: [
        'Programs of interest and their admission prerequisites',
        'Current marks',
        'Meeting with the guidance counsellor',
      ],
      ages: { from: 15, to: 16 },
      howTo:
        '1. Grades 11 and 12 courses have types: university (U), university/college (M), college (C), workplace (E) and open (O).\n2. University and college programs list specific Grade 12 U or M courses as prerequisites, which need Grade 11 courses first.\n3. Course selection is usually in the winter of Grade 10; schools set their own dates.',
    },
    {
      id: 'grade12-courses',
      title: 'Choose Grade 12 courses to meet program prerequisites',
      offsetDays: 5994,
      durationDays: 30,
      dependsOn: ['grade11-courses'],
      documents: [],
      prepare: ['Prerequisite list for each program on the shortlist', 'Credit count so far'],
      ages: { from: 16, to: 17 },
      howTo:
        '1. Check each program\'s required Grade 12 courses and minimum marks.\n2. Course selection is usually in the winter of Grade 11.',
    },
    {
      id: 'scholarships',
      title: 'Apply for scholarships and awards',
      offsetDays: 6389,
      durationDays: 180,
      dependsOn: ['grade12-courses'],
      documents: ['Scholarship applications'],
      prepare: ['Reference letters', 'List of volunteering and activities', 'Short personal statements'],
      ages: { from: 17, to: 18 },
      howTo:
        '1. Ask the guidance office for the school\'s award list.\n2. Many universities and colleges consider applicants for entrance awards automatically; others need a separate form.\n3. Deadlines vary widely; this date is an estimate for spring of Grade 12.',
    },
    {
      id: 'ouac',
      title: 'Apply to Ontario universities through OUAC',
      offsetDays: 6344,
      durationDays: 60,
      dependsOn: ['grade12-courses'],
      documents: ['OUAC application', 'Supplementary applications'],
      prepare: ['Program choices', 'Student number from the school', 'Payment card'],
      ages: { from: 17, to: 18 },
      conditions: ['Only if they plan to go to university in Ontario'],
      howTo:
        '1. High school students apply through the OUAC 101 application; the school provides access details.\n2. Applications in by mid-January (January 15 for fall 2027) get equal consideration; check the current OUAC deadline.\n3. Some programs need supplementary forms or portfolios with their own deadlines.\n4. The school sends marks to OUAC; the student does not.',
    },
    {
      id: 'ocas',
      title: 'Apply to Ontario colleges on ontariocolleges.ca',
      offsetDays: 6361,
      durationDays: 60,
      dependsOn: ['grade12-courses'],
      documents: ['ontariocolleges.ca application'],
      prepare: ['Program choices', 'Payment card'],
      ages: { from: 17, to: 18 },
      conditions: ['Only if they plan to go to college in Ontario'],
      howTo:
        '1. Applications for the next academic year open in the fall.\n2. Apply and pay by February 1 for equal consideration; after that, colleges consider applicants first-come, first-served.\n3. Colleges may send offers from November 1; the confirm-by date is May 1.',
    },
    {
      id: 'osap',
      title: 'Apply for OSAP',
      offsetDays: 6514,
      durationDays: 42,
      dependsOn: [],
      documents: ['OSAP application'],
      prepare: ['Social Insurance Number', 'School and program', 'Parents\' SINs and tax information'],
      ages: { from: 17, to: 18 },
      conditions: ['Only if they need student financial aid for college or university'],
      howTo:
        '1. The application for the next school year opens in spring at ontario.ca/osap.\n2. Processing takes about 4 to 6 weeks once documents are in.\n3. Applying at least 2 months before classes is an estimate that lets funding arrive for the first week.',
    },
    {
      id: 'hours-done',
      title: 'Finish and hand in the 40 community involvement hours',
      offsetDays: 6454,
      durationDays: 1340,
      dependsOn: ['hours-start'],
      documents: ['Community involvement log'],
      prepare: ['Signed forms for every activity'],
      ages: { from: 14, to: 18 },
      howTo:
        '1. At least 40 hours are needed to graduate.\n2. Hand forms in as hours are done rather than all at the end; the school records them.',
    },
    {
      id: 'diploma',
      title: 'Graduate with the OSSD',
      offsetDays: 6484,
      durationDays: 30,
      dependsOn: ['ossd-plan', 'osslt', 'career-studies', 'grade12-courses', 'hours-done'],
      documents: ['Ontario Secondary School Diploma'],
      prepare: ['Credit count', 'Graduation ceremony date'],
      ages: { from: 17, to: 18 },
      howTo:
        '1. The Minister grants the diploma on the principal\'s recommendation once all requirements are met.\n2. Most students finish in June of Grade 12; move this step to the real date.',
    },
    {
      id: 'transcript',
      title: 'Keep a copy of the Ontario Student Transcript',
      offsetDays: 6514,
      durationDays: 14,
      dependsOn: ['diploma'],
      documents: ['Ontario Student Transcript'],
      prepare: ['Scan the diploma', 'Store both somewhere safe'],
      ages: { from: 17, to: 18 },
      howTo:
        '1. The OST is the official record of all courses and diploma requirements.\n2. For a copy later, contact the school or school board.',
    },
    {
      id: 'resp-eap',
      title: 'Request Educational Assistance Payments from the RESP',
      offsetDays: 6588,
      durationDays: 30,
      dependsOn: ['diploma'],
      documents: ['Proof of enrolment'],
      prepare: ['RESP promoter contact', 'Tuition and costs estimate'],
      ages: { from: 18, to: 18 },
      conditions: ['Only if they have an RESP', 'Only if they enrol in a qualifying post-secondary program'],
      howTo:
        '1. The subscriber contacts the RESP promoter to request an EAP.\n2. The promoter needs official proof of enrolment.\n3. Full-time programs in Canada must run at least 3 weeks in a row with at least 10 hours a week.\n4. EAPs are taxable income for the student and can be paid up to 6 months after enrolment ends.',
    },
  ],
};
