import type { Playbook } from '../../domain/types';

export const highSchoolCn: Playbook = {
  id: 'high-school-cn',
  title: 'Secondary school · 中考 and 高考 · China',
  summary:
    'Junior middle school, the 中考, senior high school, the gaokao and university enrolment in mainland China. Exams and admissions are run by each province or city; dates assume junior middle school starts in September of the year they turn 12.',
  region: 'China',
  country: 'CN',
  family: 'high-school',
  anchorKind: 'born',
  ages: { from: 12, to: 18 },
  conditions: [
    'For a young person going through junior and senior secondary school in mainland China',
    'Exam subjects, dates and admission rules are set by the province or city where they study',
  ],
  reviewedAt: '2026-09-27',
  version: 1,
  sources: [
    {
      title: 'Compulsory Education Law of the PRC (中华人民共和国义务教育法) — gov.cn',
      url: 'https://www.gov.cn/guoqing/2021-10/29/content_5647617.htm',
    },
    {
      title: 'Guideline on reforming senior high school entrance exams and admissions (2016) — Ministry of Education',
      url: 'http://www.moe.gov.cn/srcsite/A06/s3732/201609/t20160920_281610.html',
    },
    {
      title: 'Opinions on exams for children of migrant workers after compulsory education (国办发〔2012〕46号) — gov.cn',
      url: 'https://www.gov.cn/zwgk/2012-08/31/content_2214566.htm',
    },
    {
      title: 'State Council opinions on deepening exam and admissions reform (2014) — gov.cn',
      url: 'https://www.gov.cn/zhengce/content/2014-09/04/content_9065.htm',
    },
    {
      title: 'Eight provinces publish gaokao reform plans ("3+1+2", 2019) — Ministry of Education',
      url: 'http://www.moe.gov.cn/jyb_xwfb/gzdt_gzdt/s5987/201904/t20190424_379274.html',
    },
    {
      title: 'Progress of exam and admissions reform since 2012 (29 provinces, 2022) — Ministry of Education',
      url: 'http://www.moe.gov.cn/fbh/live/2022/54835/sfcl/202209/t20220915_661172.html',
    },
    {
      title: '2026 gaokao registration opens October 16 (Hunan example) — Hunan Provincial Government',
      url: 'https://www.hunan.gov.cn/hnszf/hnyw/zwdt/202509/t20250927_33815766.html',
    },
    {
      title: '2026 gaokao registration notice (Guangdong example) — Guangdong Education Examinations Authority',
      url: 'https://eea.gd.gov.cn/tzgg/content/post_4776499.html',
    },
    {
      title: 'Notice on 2026 regular university admissions — Ministry of Education',
      url: 'http://www.moe.gov.cn/srcsite/A15/moe_776/s3258/202601/t20260121_1427110.html',
    },
    {
      title: 'Ministry of Education reminds candidates to prepare (2026 exam dates) — Ministry of Education',
      url: 'http://www.moe.gov.cn/jyb_xwfb/gzdt_gzdt/s5987/202606/t20260606_1438986.html',
    },
    {
      title: '2026 gaokao: ten questions and answers — Ministry of Education',
      url: 'http://www.moe.gov.cn/jyb_xwfb/gzdt_gzdt/s5987/202606/t20260605_1438861.html',
    },
    {
      title: '2024 gaokao application choices: ten questions and answers — Ministry of Education',
      url: 'http://www.moe.gov.cn/jyb_xwfb/gzdt_gzdt/s5987/202406/t20240619_1136514.html',
    },
    {
      title: 'Sunshine Gaokao information platform (阳光高考) — CHSI',
      url: 'https://gaokao.chsi.com.cn',
    },
    {
      title: '2025 student-origin credit student loan guide (Shenzhen example) — Shenzhen Education Bureau',
      url: 'https://szeb.sz.gov.cn/home/jyfw/fwxsjz/jyjz/fwxx/content/post_12216899.html',
    },
  ],
  steps: [
    {
      id: 'junior-enrol',
      title: 'Enrol in junior middle school (初中)',
      offsetDays: 4420,
      durationDays: 30,
      dependsOn: [],
      documents: ['Enrolment notice from the school or district'],
      prepare: ['Household register (户口簿)', 'Proof of address', 'Primary school records'],
      ages: { from: 12, to: 12 },
      howTo:
        '1. Junior middle school is the last part of 9 years of compulsory education (义务教育); public schools admit without an entrance exam, near where the child lives.\n2. The local education bureau sets the enrolment dates, the documents and which school serves which address.\n3. Children start school at 6; how the 9 years split between primary and junior middle school varies by place, so check locally.\n4. This date assumes junior middle school starts in September of the year they turn 12 and is an estimate.',
    },
    {
      id: 'junior-start',
      title: 'Start junior middle school (Grade 7, 初一)',
      offsetDays: 4450,
      durationDays: 7,
      dependsOn: ['junior-enrol'],
      documents: ['Student status record (学籍)'],
      prepare: ['Class timetable', 'Name of the class teacher (班主任)'],
      ages: { from: 12, to: 12 },
      howTo:
        '1. The school year starts in September.\n2. The student status record (学籍) follows the student and is checked later for exam registration.',
    },
    {
      id: 'quality-record',
      title: 'Keep the comprehensive quality evaluation record (综合素质评价)',
      offsetDays: 5420,
      durationDays: 900,
      dependsOn: ['junior-start'],
      documents: ['Comprehensive quality evaluation record'],
      prepare: ['Certificates and records of activities', 'Volunteer and social practice records'],
      ages: { from: 12, to: 14 },
      howTo:
        '1. The record covers moral character, academic achievement, physical and mental health, arts, and social practice.\n2. Senior high schools use it as a basis or reference for admission; each place sets how.\n3. Sports and arts talents are recorded here rather than earning extra exam points.',
    },
    {
      id: 'migrant-zhongkao',
      title: 'Check the conditions for sitting the 中考 without a local hukou (随迁子女)',
      offsetDays: 5180,
      durationDays: 60,
      dependsOn: ['junior-start'],
      documents: ['Local rules for non-hukou candidates'],
      prepare: [
        'Parents\' proof of stable work and home (including a lease)',
        'Parents\' social insurance record',
        'Years of schooling in the city',
      ],
      ages: { from: 14, to: 14 },
      conditions: ['Only if their household registration (户口) is outside the city where they go to school'],
      howTo:
        '1. Each province sets the conditions for children of migrant workers to sit exams where they live.\n2. The national guideline lists the factors: the parents\' stable job, stable home (renting counts) and years of social insurance, and the child\'s years of continuous schooling there.\n3. Those who don\'t qualify return to the hukou province for the exam; some cities offer a borrowed exam seat (借考).\n4. Check the education bureau\'s rules early in Grade 9 at the latest; this date is an estimate.',
    },
    {
      id: 'zhongkao-register',
      title: 'Register for the 中考 (中考报名)',
      offsetDays: 5250,
      durationDays: 30,
      dependsOn: ['junior-start'],
      documents: ['中考 registration confirmation'],
      prepare: ['Resident ID card or household register', 'Student status (学籍) details', 'Photo'],
      ages: { from: 14, to: 14 },
      howTo:
        '1. Registration usually goes through the school; the city or province sets the dates.\n2. This date assumes the winter of Grade 9 and is an estimate.',
    },
    {
      id: 'pe-test',
      title: 'Take the PE test counted in the 中考 (体育考试)',
      offsetDays: 5400,
      durationDays: 30,
      dependsOn: ['junior-start'],
      documents: ['PE test result'],
      prepare: ['Event choices, if the city offers them', 'Regular training plan'],
      ages: { from: 14, to: 15 },
      howTo:
        '1. National policy puts PE among the subjects counted for senior high school admission.\n2. The events, points and dates are set locally.\n3. This date assumes spring of Grade 9 and is an estimate.',
    },
    {
      id: 'junior-proficiency',
      title: 'Sit the junior secondary academic proficiency tests (初中学业水平考试)',
      offsetDays: 5420,
      durationDays: 30,
      dependsOn: ['zhongkao-register'],
      documents: ['Proficiency test results'],
      prepare: ['Exam timetable from the school', 'Admission ticket (准考证)'],
      ages: { from: 14, to: 15 },
      howTo:
        '1. The tests cover the subjects in the national curriculum; the results are the basis for junior middle school graduation.\n2. Some subjects may be tested before Grade 9; the province decides.\n3. This date assumes the end of Grade 9 and is an estimate.',
    },
    {
      id: 'zhongkao',
      title: 'Sit the senior high school entrance exam (中考)',
      offsetDays: 5440,
      durationDays: 7,
      dependsOn: ['zhongkao-register'],
      documents: ['中考 score report'],
      prepare: ['Admission ticket (准考证)', 'Resident ID card or other ID the exam office names'],
      ages: { from: 15, to: 15 },
      howTo:
        '1. In most places the 中考 is the admission part of the proficiency tests: besides Chinese, maths and a foreign language, the province picks which other subjects count.\n2. In many places the two are one sitting.\n3. The city or province sets the dates, often near the end of Grade 9; this date is an estimate.',
    },
    {
      id: 'zhongkao-choices',
      title: 'Choose and submit senior high school choices (志愿填报)',
      offsetDays: 5460,
      durationDays: 14,
      dependsOn: ['zhongkao-register'],
      documents: ['Submitted list of school choices'],
      prepare: ['Past admission scores of target schools', 'Visits or open days', 'Talk with the class teacher'],
      ages: { from: 15, to: 15 },
      howTo:
        '1. Graduates go on to either a general senior high school (普通高中) or a secondary vocational school (中等职业学校); both admit through the 中考.\n2. Each place plans how many places go to general and vocational schools, and part of the places at top schools are set aside for each junior middle school (名额分配).\n3. Some cities collect choices before the exam, some after the scores; follow the local timetable.\n4. This date is an estimate.',
    },
    {
      id: 'senior-admission',
      title: 'Receive the admission result and enrol in senior high school',
      offsetDays: 5500,
      durationDays: 30,
      dependsOn: ['zhongkao', 'zhongkao-choices'],
      documents: ['Senior high school admission notice'],
      prepare: ['Documents the school lists for enrolment'],
      ages: { from: 15, to: 15 },
      howTo: '1. Admission results and enrolment dates are published by the city; this date assumes July and is an estimate.',
    },
    {
      id: 'senior-start',
      title: 'Start senior high school (Grade 10, 高一)',
      offsetDays: 5545,
      durationDays: 7,
      dependsOn: ['senior-admission'],
      documents: ['Senior high school student status (学籍)'],
      prepare: ['Class timetable', 'The province\'s gaokao subject rules'],
      ages: { from: 15, to: 15 },
      howTo:
        '1. Senior high school (高中) is usually 3 years, from Grade 10 to Grade 12.\n2. The school year starts in September.',
    },
    {
      id: 'subject-choice',
      title: 'Choose gaokao elective subjects (选科): 3+1+2 or 3+3',
      offsetDays: 5845,
      durationDays: 60,
      dependsOn: ['senior-start'],
      documents: ['Subject choice form'],
      prepare: [
        'Subject requirements of target universities and majors',
        'Grades in each subject',
        'Talk with the class teacher',
      ],
      ages: { from: 16, to: 16 },
      howTo:
        '1. Under the "new gaokao" the score is Chinese, maths and a foreign language from the national exam, plus elective subjects from the senior secondary proficiency tests; there is no arts/science split.\n2. 3+3 (the first reform provinces, such as Shanghai and Zhejiang): any 3 of politics, history, geography, physics, chemistry and biology.\n3. 3+1+2 (most other reform provinces): physics or history first, then 2 of chemistry, biology, politics and geography.\n4. By 2022, 29 provinces had started the reform; the last batch was set to sit its first new gaokao in 2025. Check the province\'s current plan.\n5. Universities publish the subjects each major needs; check them before choosing.\n6. Schools usually ask for the choice during Grade 10 or early Grade 11; this date is an estimate.',
    },
    {
      id: 'senior-proficiency',
      title: 'Sit the senior secondary academic proficiency tests (高中学业水平考试)',
      offsetDays: 6185,
      durationDays: 30,
      dependsOn: ['senior-start'],
      documents: ['Proficiency test results'],
      prepare: ['The province\'s test timetable', 'Admission ticket (准考证)'],
      ages: { from: 16, to: 17 },
      howTo:
        '1. The tests cover every subject in the national curriculum and are a key basis for graduation and admission.\n2. The province runs them and sets when each subject is sat.\n3. Where offered, a subject can be sat twice.\n4. This date assumes the end of Grade 11 and is an estimate.',
    },
    {
      id: 'migrant-gaokao',
      title: 'Check gaokao eligibility where they live without a local hukou (异地高考)',
      offsetDays: 5945,
      durationDays: 60,
      dependsOn: ['senior-start'],
      documents: ['Local rules for non-hukou candidates'],
      prepare: [
        'Parents\' proof of stable work and home',
        'Parents\' social insurance record',
        'Years of high school study and student status (学籍) in the province',
      ],
      ages: { from: 16, to: 16 },
      conditions: ['Only if their household registration (户口) is in a different province from their high school'],
      howTo:
        '1. Each province sets whether and how non-hukou students can sit the gaokao there, based on the parents\' work, home and social insurance and the student\'s years of schooling.\n2. Those who don\'t qualify go back to the hukou province to register and sit the exam.\n3. Provinces check hukou and student status closely to prevent "gaokao migration".\n4. Check by Grade 11; this date is an estimate.',
    },
    {
      id: 'gaokao-register',
      title: 'Register for the gaokao (高考报名)',
      offsetDays: 6335,
      durationDays: 30,
      dependsOn: ['subject-choice'],
      documents: ['Gaokao registration confirmation'],
      prepare: [
        'Valid resident ID card (居民身份证)',
        'Household register and student status details',
      ],
      ages: { from: 17, to: 17 },
      howTo:
        '1. Registration is run by the provincial examinations authority, usually online in October or November of the year before the exam.\n2. Examples for the 2026 exam: Hunan ran it from October 16 to 31, 2025, with no late registration.\n3. The ID card has to be valid; Hunan asked candidates with an expired card to renew it before the check.\n4. Arts and sports candidates have extra registration steps.\n5. This date assumes November of Grade 12 and is an estimate.',
    },
    {
      id: 'gaokao',
      title: 'Sit the gaokao (普通高考) in early June',
      offsetDays: 6555,
      durationDays: 3,
      dependsOn: ['gaokao-register', 'senior-proficiency'],
      documents: ['Admission ticket (准考证)'],
      prepare: ['ID named by the provincial exam office', 'Exam site route', 'Permitted exam items'],
      ages: { from: 17, to: 18 },
      howTo:
        '1. The national exam is held on June 7 and 8; in some provinces other subjects run on June 9 and 10.\n2. Phones, smart watches and other devices that send or receive data count as cheating if taken into the room.\n3. Move this step to June 7 of the exam year.',
    },
    {
      id: 'gaokao-choices',
      title: 'Check results and submit university choices (志愿填报)',
      offsetDays: 6580,
      durationDays: 14,
      dependsOn: ['gaokao'],
      documents: ['Gaokao score report', 'Submitted choices'],
      prepare: [
        'Past admission ranks of target universities',
        'Each university\'s admission rules (招生章程)',
        'Subject requirements of each major',
      ],
      ages: { from: 18, to: 18 },
      howTo:
        '1. Each province publishes the results date and the official way to check scores, usually in the second half of June.\n2. Choices are submitted online in the province\'s system within the window it sets.\n3. The province decides the matching model: parallel choices (平行志愿, by score rank) or sequential choices.\n4. The Sunshine Gaokao platform (gaokao.chsi.com.cn) lists universities, plans and admission rules.\n5. This date is an estimate; follow the provincial window.',
    },
    {
      id: 'admission',
      title: 'Track admission and receive the admission letter (录取通知书)',
      offsetDays: 6625,
      durationDays: 40,
      dependsOn: ['gaokao-choices'],
      documents: ['Admission letter'],
      prepare: ['Working postal address and phone', 'Provincial results site login'],
      ages: { from: 18, to: 18 },
      howTo:
        '1. Admission runs online by province, usually from early July to the end of August.\n2. Universities usually post admission letters about a week after each batch closes.\n3. If the result shows online but no letter arrives, call the university\'s admissions line.\n4. This date is an estimate.',
    },
    {
      id: 'student-loan',
      title: 'Apply for a national student loan (国家助学贷款)',
      offsetDays: 6650,
      durationDays: 21,
      dependsOn: ['admission'],
      documents: ['Loan contract', 'Loan receipt for the university'],
      prepare: ['Admission letter', 'Resident ID cards of student and parent', 'Household register (户口簿)'],
      ages: { from: 18, to: 18 },
      conditions: ['Only if the family needs help with tuition and accommodation'],
      howTo:
        '1. The student-origin credit loan (生源地信用助学贷款) is applied for at the student aid office of the county where the student\'s hukou is, before entering university.\n2. Student and parent or guardian sign as co-borrowers; no collateral is needed.\n3. Example: in 2025 Shenzhen asked new students to fill in the form in the China Development Bank loan system and then sign in person with the admission letter, ID and household register.\n4. Amounts and windows change each year; this date is an estimate.',
    },
    {
      id: 'enrol-docs',
      title: 'Gather the university enrolment documents',
      offsetDays: 6640,
      durationDays: 14,
      dependsOn: ['admission'],
      documents: ['Admission letter', 'Resident ID card', 'Student file (档案) transfer arrangement'],
      prepare: ['The university\'s new-student guide', 'ID photos', 'Whether a hukou transfer applies'],
      ages: { from: 18, to: 18 },
      howTo:
        '1. The admission letter pack lists what the university wants at registration.\n2. Follow the pack for the student file (档案) and any hukou transfer.',
    },
    {
      id: 'enrol',
      title: 'Register at university',
      offsetDays: 6660,
      durationDays: 7,
      dependsOn: ['enrol-docs'],
      documents: ['University student card'],
      prepare: ['Travel to campus', 'Tuition payment or loan receipt'],
      ages: { from: 18, to: 18 },
      howTo: '1. Universities set their own registration dates, usually early to mid-September; this date is an estimate.',
    },
  ],
};
