import type { Playbook } from '../../domain/types';

export const newbornCn: Playbook = {
  id: 'newborn-cn',
  title: 'Newborn · first year · China',
  summary:
    'Paperwork, insurance, vaccines and health checks for a baby born in mainland China, from the birth medical certificate to the 18-month vaccines.',
  region: 'China',
  country: 'CN',
  family: 'newborn',
  anchorKind: 'born',
  ages: { from: 0, to: 1 },
  conditions: [
    'For a baby born in mainland China to parents who are Chinese citizens',
    'Provinces and cities add to or change the national rules',
  ],
  reviewedAt: '2026-09-27',
  version: 1,
  sources: [
    {
      title: 'Hubei Birth Medical Certificate Management Measures (湖北省出生医学证明管理办法)',
      url: 'http://wjw.hubei.gov.cn/zfxxgk/zc/gfwj/202502/t20250227_5557053.shtml',
    },
    {
      title: 'Hubei Health Commission: Newborn birth "one thing" service (新生儿出生一件事)',
      url: 'https://wjw.hubei.gov.cn/bsfw/xseyjs/',
    },
    {
      title: 'Guangdong Healthcare Security Administration: Newborn birth "one thing" guide',
      url: 'https://hsa.gd.gov.cn/gkmlpt/content/4/4506/post_4506071.html',
    },
    {
      title: 'Household Registration Regulations of the PRC (户口登记条例)',
      url: 'http://www.gd.gov.cn/zwgk/wjk/zcfgk/content/post_2531969.html',
    },
    {
      title: 'NHSA: What newborns get from enrolling in medical insurance (新生儿参保都有哪些福利)',
      url: 'https://www.nhsa.gov.cn/art/2025/7/16/art_14_17289.html',
    },
    {
      title: 'National Immunization Program childhood schedule, 2021 edition (国家免疫规划疫苗儿童免疫程序表)',
      url: 'https://www.szft.gov.cn/xxgk/cjwt/ylws/content/post_10929674.html',
    },
    {
      title: 'Notice on adjusting the DTaP and DT schedule from 2025 (百白破疫苗免疫程序调整)',
      url: 'https://www.gov.cn/zhengce/zhengceku/202412/content_6994724.htm',
    },
    {
      title: 'National Immunization Program childhood schedule, 2026 edition, released',
      url: 'https://www.gov.cn/lianbo/202607/content_7074538.htm',
    },
    {
      title: 'National Basic Public Health Service Standards (3rd ed.): Health management for children 0 to 6 (0～6岁儿童健康管理服务规范)',
      url: 'https://www.fxxh.gov.cn/xhq/file/2023-12-12/17023606894344028e4928a108a34188018c5c9aab1a19f5.pdf',
    },
    {
      title: 'State Council: Special Provisions on Labour Protection for Female Employees (女职工劳动保护特别规定)',
      url: 'http://www.gov.cn/zwgk/2012-05/07/content_2131567.htm',
    },
    {
      title: 'Beijing Population and Family Planning Regulations (北京市人口与计划生育条例)',
      url: 'http://www.beijing.gov.cn/zhengce/dfxfg/202111/t20211126_2546761.html',
    },
    {
      title: 'Childcare Subsidy System Implementation Plan (育儿补贴制度实施方案)',
      url: 'https://www.gov.cn/zhengce/202507/content_7034132.htm',
    },
    {
      title: 'gov.cn: How the childcare subsidy works (育儿补贴制度详解)',
      url: 'https://www.gov.cn/zhengce/202508/content_7034793.htm',
    },
    {
      title: 'National Immigration Administration',
      url: 'http://www.nia.gov.cn/',
    },
    {
      title: 'National Immigration Administration: Photo guide for exit-entry documents (出入境证件相片照相指引)',
      url: 'http://www.nia.gov.cn/n741445/n741619/n894511/c896346/content.html',
    },
    {
      title: 'Interim Measures for Individual Income Tax Special Additional Deductions (国发〔2018〕41号) — State Taxation Administration',
      url: 'https://fgk.chinatax.gov.cn/zcfgk/c102440/c5209858/content.html',
    },
  ],
  steps: [
    {
      id: 'vaccines-birth',
      title: 'Birth vaccines: hepatitis B dose 1 and BCG (卡介苗)',
      offsetDays: 1,
      durationDays: 1,
      dependsOn: [],
      documents: ['Vaccination record from the hospital'],
      prepare: ['Keep the hospital\'s vaccination slip for the vaccination certificate'],
      ages: { from: 0, to: 0 },
      howTo:
        '1. The National Immunization Program schedule gives hepatitis B dose 1 and BCG at birth, usually in the birth hospital.\n2. If either is missed, the newborn home visit reminds you to catch up.\n3. National program vaccines are free.',
    },
    {
      id: 'home-visit',
      title: 'Newborn home visit (新生儿家庭访视)',
      offsetDays: 10,
      durationDays: 3,
      dependsOn: [],
      documents: ['Maternal and Child Health Handbook (母子健康手册)'],
      prepare: ['Discharge papers', 'Feeding, sleep and jaundice questions', 'Newborn screening (新生儿疾病筛查) result, if back'],
      ages: { from: 0, to: 0 },
      howTo:
        '1. Under the national basic public health service, a health worker from the community or township health centre visits within 1 week of discharge, with the postnatal visit for the mother.\n2. They weigh and examine the baby and check vaccines and newborn screening.\n3. The centre learns of the birth from the hospital; call them if nobody comes.\n4. This date assumes discharge a few days after the birth.',
    },
    {
      id: 'birth-certificate',
      title: 'Get the birth medical certificate (出生医学证明)',
      offsetDays: 14,
      durationDays: 7,
      dependsOn: [],
      documents: ['Birth medical certificate (出生医学证明)'],
      prepare: ['Both parents\' original ID cards', 'Marriage certificate (结婚证)', 'Baby\'s name in standard characters'],
      ages: { from: 0, to: 0 },
      howTo:
        '1. The birth hospital issues the certificate; it is the base for household registration, insurance and the passport.\n2. Check every character of the baby\'s and parents\' names and the dates before you sign; correcting it later goes back through the hospital.\n3. Example from Hubei: the mother applies within 1 month of the birth, or within 3 months at the county office; she brings both parents\' ID cards and the marriage certificate.\n4. Many provinces take this online through the birth "one thing" service (新生儿出生一件事).',
    },
    {
      id: 'vaccination-certificate',
      title: 'Get the vaccination certificate (预防接种证)',
      offsetDays: 28,
      durationDays: 7,
      dependsOn: ['vaccines-birth'],
      documents: ['Vaccination certificate (预防接种证)'],
      prepare: ['Hospital vaccination slip', 'Find the vaccination clinic (接种门诊) for where you live'],
      ages: { from: 0, to: 0 },
      howTo:
        '1. The vaccination certificate records every dose and is checked at nursery, kindergarten and school entry.\n2. It is part of the birth "one thing" service; some provinces issue an electronic certificate, for example Hubei through its CDC account.\n3. Bring it to every vaccine visit.',
    },
    {
      id: 'hukou',
      title: 'Register the birth in the household register (户口登记)',
      offsetDays: 30,
      durationDays: 7,
      dependsOn: ['birth-certificate'],
      documents: ['Household register (户口簿) with the baby added'],
      prepare: ['Birth medical certificate', 'Parents\' ID cards and household register', 'Marriage certificate', 'Which parent\'s household the baby joins'],
      ages: { from: 0, to: 0 },
      howTo:
        '1. The Household Registration Regulations ask for the birth to be registered within one month, where the baby will normally live.\n2. The baby can join either the father\'s or the mother\'s household.\n3. Many provinces take this through the birth "one thing" service, online or at one window; otherwise go to the local police station (派出所).\n4. Cities set their own hukou rules; check with the local police station, for example in Beijing or Shanghai.',
    },
    {
      id: 'check-1m',
      title: 'One-month check (满月健康管理) and hepatitis B dose 2',
      offsetDays: 30,
      durationDays: 2,
      dependsOn: ['vaccines-birth'],
      documents: ['Vaccination certificate (预防接种证)', 'Maternal and Child Health Handbook (母子健康手册)'],
      prepare: ['Book with the community health centre', 'Feeding and sleep notes'],
      ages: { from: 0, to: 0 },
      howTo:
        '1. The national service gives a check at 28 to 30 days, together with hepatitis B dose 2 at 1 month.\n2. Weight, length and head size are measured.\n3. Move this to the appointment date.',
    },
    {
      id: 'childcare-subsidy',
      title: 'Apply for the childcare subsidy (育儿补贴)',
      offsetDays: 60,
      durationDays: 14,
      dependsOn: ['hukou'],
      documents: ['Subsidy application'],
      prepare: ['Birth medical certificate', 'Household register', 'Bank card or the baby\'s social security card for payment'],
      ages: { from: 0, to: 0 },
      howTo:
        '1. Since 1 January 2025 a national childcare subsidy (育儿补贴) of 3,600 yuan a year is paid for each child under 3, until the third birthday, for first, second and third children alike.\n2. Children born before 2025 who were still under 3 get a pro-rated amount for their months under 3 from 2025 on.\n3. One parent or guardian applies where the baby\'s hukou is registered, mainly online through the national subsidy system, the provincial government service platform, Alipay or WeChat; offline at the township or street office.\n4. It is exempt from income tax; provinces set when it is paid, and some pay more than the national base.\n5. Timing is a planning estimate.',
    },
    {
      id: 'vaccines-2m',
      title: 'Vaccines at 2 months: polio (IPV) dose 1 and DTaP (百白破) dose 1',
      offsetDays: 61,
      durationDays: 1,
      dependsOn: ['check-1m'],
      documents: ['Vaccination certificate (预防接种证)'],
      prepare: ['Book with the vaccination clinic', 'Bring the vaccination certificate'],
      ages: { from: 0, to: 0 },
      howTo:
        '1. Since 2025 the national DTaP schedule starts at 2 months (2, 4, 6 and 18 months and 6 years); the 2026 schedule keeps this.\n2. Inactivated polio vaccine (IPV) dose 1 is at 2 months.\n3. Clinics may offer optional paid vaccines too; ask what is in the national program.\n4. Move this to the appointment date.',
    },
    {
      id: 'return-to-work',
      title: 'Maternity leave ends: return to work',
      offsetDays: 83,
      durationDays: 1,
      dependsOn: [],
      documents: [],
      prepare: ['Childcare arranged', 'Feeding plan', 'Your province\'s extra leave'],
      ages: { from: 0, to: 0 },
      conditions: ['Only if the mother is an employee on maternity leave'],
      howTo:
        '1. National maternity leave is 98 days, up to 15 before the birth, so about 83 days after it; a difficult birth or twins add 15 days each.\n2. Provinces add leave. Example: Beijing adds 60 days, so leave ends about 143 days after the birth.\n3. Until the baby is 1, the employer gives 1 hour a day for breastfeeding and no overtime or night shifts.\n4. Move this to your real date.',
    },
    {
      id: 'medical-insurance',
      title: 'Enrol the baby in resident basic medical insurance (城乡居民医保)',
      offsetDays: 90,
      durationDays: 14,
      dependsOn: ['birth-certificate'],
      documents: ['Medical insurance enrolment'],
      prepare: ['Birth medical certificate or household register', 'Payment channel, often the tax app'],
      ages: { from: 0, to: 0 },
      howTo:
        '1. The NHSA asks for newborns to be enrolled and paid within 90 days of birth; then costs from the day of birth are covered.\n2. Newborns have no waiting period.\n3. The birth certificate alone is enough in many places, and the birth "one thing" service enrols the baby together with the other steps.\n4. Contributions and any free first year are set locally.',
    },
    {
      id: 'vaccines-3m',
      title: '3-month check and polio (IPV) dose 2',
      offsetDays: 91,
      durationDays: 1,
      dependsOn: ['vaccines-2m'],
      documents: ['Vaccination certificate (预防接种证)', 'Maternal and Child Health Handbook (母子健康手册)'],
      prepare: ['Book the health check and the vaccine together if the centre allows'],
      ages: { from: 0, to: 0 },
      howTo:
        '1. The national child health service has a check at 3 months: growth, development and feeding advice.\n2. The immunization schedule gives IPV dose 2 at 3 months.\n3. Move this to the appointment date.',
    },
    {
      id: 'parental-leave',
      title: 'Plan parental leave (育儿假)',
      offsetDays: 90,
      durationDays: 14,
      dependsOn: [],
      documents: [],
      prepare: ['Your province\'s parental leave', 'Dates each parent wants'],
      ages: { from: 0, to: 0 },
      conditions: ['Only if a parent is an employee'],
      howTo:
        '1. There is no national parental leave; each province sets it.\n2. Example: Beijing gives each parent 5 working days a year until the child turns 3, counted by the child\'s birthday year.\n3. Check your province\'s regulations and your employer; timing is a planning estimate.',
    },
    {
      id: 'social-security-card',
      title: 'Apply for the baby\'s social security card (社会保障卡)',
      offsetDays: 120,
      durationDays: 30,
      dependsOn: ['hukou'],
      documents: ['Social security card (社会保障卡)'],
      prepare: ['Household register', 'Photo, if asked', 'Guardian\'s ID card'],
      ages: { from: 0, to: 0 },
      howTo:
        '1. The card is used for medical insurance and can receive the childcare subsidy.\n2. It is part of the birth "one thing" service in many provinces.\n3. Example from Hubei: the card is ready about 30 working days after applying.',
    },
    {
      id: 'passport',
      title: 'Apply for the baby\'s passport (护照)',
      offsetDays: 120,
      durationDays: 30,
      dependsOn: ['hukou'],
      documents: ['Passport (护照)', 'Passport photo'],
      prepare: ['Household register and birth medical certificate', 'Guardian\'s ID card', 'Photo taken to the exit-entry photo guide'],
      ages: { from: 0, to: 0 },
      conditions: ['Only if the baby will travel abroad'],
      howTo:
        '1. Passports are issued by the exit-entry administration (出入境管理机构) of the National Immigration Administration.\n2. A parent or guardian applies with the baby and their own ID; bring the household register and birth medical certificate.\n3. Photos follow the NIA photo guide; many offices take them on site.\n4. The date here is a planning estimate; move it to 2 months before travel.',
    },
    {
      id: 'vaccines-4m',
      title: 'Vaccines at 4 months: polio (bOPV) dose 3 and DTaP dose 2',
      offsetDays: 122,
      durationDays: 1,
      dependsOn: ['vaccines-3m'],
      documents: ['Vaccination certificate (预防接种证)'],
      prepare: ['Book with the vaccination clinic'],
      ages: { from: 0, to: 0 },
      howTo:
        '1. The schedule gives oral polio vaccine (bOPV) dose 3 and DTaP dose 2 at 4 months.\n2. Move this to the appointment date.',
    },
    {
      id: 'check-6m',
      title: '6-month check and vaccines: hepatitis B dose 3, DTaP dose 3, meningococcal A dose 1',
      offsetDays: 183,
      durationDays: 1,
      dependsOn: ['vaccines-4m'],
      documents: ['Vaccination certificate (预防接种证)', 'Maternal and Child Health Handbook (母子健康手册)'],
      prepare: ['Book the health check and vaccines'],
      ages: { from: 0, to: 0 },
      howTo:
        '1. The national child health service has a check at 6 months, with a hearing screen, and a blood test once between 6 and 8 months.\n2. The immunization schedule gives hepatitis B dose 3, DTaP dose 3 and meningococcal A (MPSV-A) dose 1 at 6 months.\n3. Move this to the appointment date.',
    },
    {
      id: 'check-8m',
      title: '8-month check and vaccines: MMR (麻腮风) dose 1 and Japanese encephalitis (乙脑)',
      offsetDays: 244,
      durationDays: 1,
      dependsOn: ['check-6m'],
      documents: ['Vaccination certificate (预防接种证)', 'Maternal and Child Health Handbook (母子健康手册)'],
      prepare: ['Book the health check and vaccines'],
      ages: { from: 0, to: 0 },
      howTo:
        '1. The national child health service has a check at 8 months.\n2. The schedule gives MMR dose 1 and Japanese encephalitis vaccine at 8 months: live vaccine dose 1, or inactivated doses 1 and 2, 7 to 10 days apart.\n3. Move this to the appointment date.',
    },
    {
      id: 'vaccines-9m',
      title: 'Vaccines at 9 months: meningococcal A dose 2',
      offsetDays: 274,
      durationDays: 1,
      dependsOn: ['check-8m'],
      documents: ['Vaccination certificate (预防接种证)'],
      prepare: ['Book with the vaccination clinic'],
      ages: { from: 0, to: 0 },
      howTo:
        '1. The schedule gives meningococcal A (MPSV-A) dose 2 at 9 months.\n2. Move this to the appointment date.',
    },
    {
      id: 'check-12m',
      title: '12-month health check',
      offsetDays: 365,
      durationDays: 7,
      dependsOn: ['check-8m'],
      documents: ['Maternal and Child Health Handbook (母子健康手册)'],
      prepare: ['Book with the community health centre', 'Notes on walking, words and teeth'],
      ages: { from: 1, to: 1 },
      howTo:
        '1. The national child health service has a check at 12 months, with a hearing screen.\n2. Later checks are at 18, 24, 30 and 36 months.\n3. Move this to the appointment date.',
    },
    {
      id: 'vaccines-18m',
      title: '18-month check and vaccines: DTaP dose 4, MMR dose 2, hepatitis A',
      offsetDays: 548,
      durationDays: 1,
      dependsOn: ['vaccines-9m'],
      documents: ['Vaccination certificate (预防接种证)', 'Maternal and Child Health Handbook (母子健康手册)'],
      prepare: ['Book the health check and vaccines'],
      ages: { from: 1, to: 1 },
      howTo:
        '1. The schedule gives DTaP dose 4, MMR dose 2 and hepatitis A (live, one dose; or inactivated dose 1) at 18 months, with a health check and blood test.\n2. Next come Japanese encephalitis, and hepatitis A dose 2 if inactivated, at 2 years.\n3. Move this to the appointment date.',
    },
    {
      id: 'infant-deduction',
      title: 'Claim the infant care tax deduction (3岁以下婴幼儿照护专项附加扣除)',
      offsetDays: 30,
      durationDays: 7,
      ages: { from: 0, to: 0 },
      conditions: ['Only if a parent pays individual income tax'],
      dependsOn: ['birth-certificate'],
      documents: ['Deduction declaration in the app'],
      prepare: ['Birth medical certificate or household register', 'The 个人所得税 app', 'Agree which parent claims it'],
      howTo:
        '1. From the month of birth until the month before the third birthday, parents can deduct 2,000 yuan a month per child (the amount since January 2023).\n2. One parent claims 100%, or each claims 50%; the split cannot change within a tax year.\n3. Declare it in the 个人所得税 app through the employer, or at the annual reconciliation; months missed in the year can be claimed there.',
    },
    {
      id: 'id-card',
      title: 'Consider a resident ID card for the baby (居民身份证)',
      offsetDays: 120,
      durationDays: 30,
      ages: { from: 0, to: 1 },
      conditions: ['Only if you want one; under 16 it is optional'],
      dependsOn: ['hukou'],
      documents: ['Resident ID card'],
      prepare: ['Household register', 'A parent\'s ID card', 'Photo taken at the police station'],
      howTo:
        '1. Children under 16 can get an ID card if a guardian applies at the police station where the hukou is registered; it is valid for 5 years.\n2. It is handy for flights, trains, hotels and some online services; the household register works for most of these too.\n3. Timing is only a prompt.',
    },
    {
      id: 'insurance-renewal',
      title: 'Pay next year\'s resident medical insurance for the baby',
      offsetDays: 300,
      durationDays: 14,
      ages: { from: 0, to: 1 },
      conditions: ['Only if the baby is in resident basic medical insurance (城乡居民医保)'],
      dependsOn: ['medical-insurance'],
      documents: ['Payment record'],
      prepare: ['The payment channel, often the 个人所得税 app, WeChat or Alipay'],
      howTo:
        '1. Resident medical insurance is paid once a year for the next calendar year, usually in a window from September to December; the local medical insurance bureau sets it.\n2. Missing the window can bring a waiting period before costs are covered.\n3. It repeats every year; move this date to the local window.',
    },
  ],
};
