import type { Playbook } from '../../domain/types';

export const travelCa: Playbook = {
  id: 'travel-ca',
  title: 'Travelling abroad from Canada',
  summary:
    'Paperwork plan for a trip abroad while living in Canada: passport and PR card validity, the destination\'s entry rules, a child\'s consent letter, insurance, provincial health coverage while away, and customs on the way back.',
  region: 'Canada',
  country: 'CA',
  family: 'travel-out',
  anchorKind: 'trip',
  leaving: true,
  conditions: [
    'You live in Canada and are travelling abroad for a visit, then coming back',
    'The date is the day you leave Canada',
    'Health coverage steps describe British Columbia and Ontario; other provinces have their own rules',
  ],
  reviewedAt: '2026-09-27',
  version: 1,
  sources: [
    { title: 'Travel advice and advisories — Travel.gc.ca', url: 'https://travel.gc.ca/travelling/advisories' },
    { title: 'Canadian passports — Canada.ca', url: 'https://www.canada.ca/en/immigration-refugees-citizenship/services/canadian-passports.html' },
    { title: 'Permanent resident travel document — Canada.ca', url: 'https://www.canada.ca/en/immigration-refugees-citizenship/services/permanent-residents/travel-document.html' },
    { title: 'Understand PR status — Canada.ca', url: 'https://www.canada.ca/en/immigration-refugees-citizenship/services/new-immigrants/pr-card/understand-pr-status.html' },
    { title: 'Recommended consent letter for children travelling abroad — Travel.gc.ca', url: 'https://travel.gc.ca/travelling/children/consent-letter' },
    { title: 'Travel insurance — Travel.gc.ca', url: 'https://travel.gc.ca/travelling/health-safety/insurance' },
    { title: 'Registration of Canadians Abroad — Travel.gc.ca', url: 'https://travel.gc.ca/travelling/registration' },
    { title: 'Medical Services Plan eligibility — Province of British Columbia', url: 'https://www2.gov.bc.ca/gov/content/health/health-drug-coverage/msp/bc-residents/eligibility-and-enrolment/are-you-eligible' },
    { title: 'Apply for OHIP and get a health card — Ontario.ca', url: 'https://www.ontario.ca/page/apply-ohip-and-get-health-card' },
    { title: 'Guaranteed Income Supplement — Canada.ca', url: 'https://www.canada.ca/en/services/benefits/publicpensions/old-age-security/guaranteed-income-supplement.html' },
    { title: 'Personal exemptions for residents returning to Canada — CBSA', url: 'https://www.cbsa-asfc.gc.ca/travel-voyage/rc-rc-eng.html' },
    { title: 'Crossing the border with $10,000 or more — CBSA', url: 'https://www.cbsa-asfc.gc.ca/travel-voyage/money-argent-eng.html' },
  ],
  steps: [
    {
      id: 'passport',
      title: 'Check the passport is valid well past the return date',
      offsetDays: -120,
      durationDays: 30,
      dependsOn: [],
      documents: ['Passport'],
      prepare: ['Passport expiry date', 'Return date', 'Blank pages'],
      howTo:
        '1. Many countries ask for a passport valid 6 months beyond the stay, and some for blank pages; the destination\'s own rules decide.\n2. A Canadian passport renewal takes a few weeks by standard service; urgent and express service cost more.\n3. Children\'s passports last at most 5 years.\n4. Travellers on a foreign passport renew with that country\'s embassy or consulate, which can take longer.',
    },
    {
      id: 'pr-card',
      title: 'Check the PR card is valid on the return date',
      offsetDays: -120,
      durationDays: 30,
      dependsOn: [],
      documents: ['PR card'],
      prepare: ['PR card expiry date', 'Days spent in Canada in the last 5 years'],
      conditions: ['Only if you are a permanent resident, not yet a citizen'],
      howTo:
        '1. Airlines and other commercial carriers ask for a valid PR card or a permanent resident travel document (PRTD) before boarding for Canada.\n2. A card with less than 9 months left can be renewed from Canada before leaving.\n3. Without a valid card, the PRTD is applied for from abroad.\n4. The 730-days-in-5-years residency obligation is checked when renewing or applying for a PRTD.',
    },
    {
      id: 'entry-rules',
      title: 'Get the destination\'s visa, eTA or ESTA',
      offsetDays: -60,
      durationDays: 21,
      dependsOn: ['passport'],
      documents: ['Visa or electronic travel authorization'],
      prepare: ['Passport details', 'Itinerary and address abroad', 'Travel.gc.ca advice page for the country'],
      howTo:
        '1. Entry rules depend on the passport held, not on living in Canada; Travel.gc.ca lists them for Canadian passports.\n2. Examples: the United States uses ESTA for visa-waiver passports, the UK an ETA, and the EU is bringing in ETIAS; check current.\n3. Transit stops can have their own rules.\n4. Use official sites; look-alike sites charge extra fees.',
    },
    {
      id: 'child-consent',
      title: 'Write a consent letter for a child travelling without both parents',
      offsetDays: -30,
      durationDays: 7,
      dependsOn: [],
      documents: ['Consent letter', "Child's birth certificate", 'Custody or guardianship papers, if any'],
      prepare: ['Names and contact details of the parents not travelling', 'Trip dates and addresses'],
      conditions: ['Only if a child under 18 travels alone, with one parent, or with another adult'],
      howTo:
        '1. Canada recommends a consent letter signed by each parent or guardian not travelling; border officers can ask for one.\n2. Travel.gc.ca has a template; having it witnessed or notarized adds weight.\n3. The destination country can have stricter rules.',
    },
    {
      id: 'insurance',
      title: 'Buy travel medical insurance',
      offsetDays: -30,
      durationDays: 7,
      dependsOn: [],
      documents: ['Travel insurance policy'],
      prepare: ['Trip length', 'Pre-existing conditions', 'Workplace or credit card coverage, to compare'],
      howTo:
        '1. Provincial health plans pay only a small part of emergency costs abroad, often at home-province rates.\n2. Policies usually exclude unstable pre-existing conditions; the stability period is in the wording.\n3. Some workplace plans and credit cards include coverage with day limits.',
    },
    {
      id: 'health-absence',
      title: 'Check provincial health coverage stays in place while away',
      offsetDays: -30,
      durationDays: 7,
      dependsOn: [],
      documents: [],
      prepare: ['Days outside the province this year and in the last 12 months'],
      conditions: ['Only if the trip is long, or you spend much of the year outside your province'],
      howTo:
        '1. British Columbia: MSP expects residents to be in B.C. at least 6 months in a calendar year; citizens and permanent residents away on vacation can be absent up to 7 months in a year. Longer absences, such as work or study abroad, can sometimes be approved by Health Insurance BC in advance; check current.\n2. Ontario: OHIP expects 153 days in Ontario in any 12-month period; after more than 212 days away in 12 months, re-applying may be needed. Longer approved absences exist for work, study or missionary work; check current.\n3. Other provinces set their own limits.',
    },
    {
      id: 'gis',
      title: 'Tell Service Canada about a long stay abroad while on GIS',
      offsetDays: -30,
      durationDays: 7,
      dependsOn: [],
      documents: [],
      prepare: ['My Service Canada Account sign-in', 'Departure and return dates'],
      conditions: ['Only if you receive the Guaranteed Income Supplement or Allowance and will be away more than 6 months'],
      howTo:
        '1. GIS and the Allowance stop after 6 months outside Canada, counted from the month after leaving; they restart after coming back and applying again.\n2. OAS itself can keep being paid abroad in many cases.\n3. Service Canada is the reference for the exact rules.',
    },
    {
      id: 'register',
      title: 'Register the trip with Registration of Canadians Abroad',
      offsetDays: -7,
      durationDays: 1,
      dependsOn: [],
      documents: [],
      prepare: ['Itinerary', 'Emergency contact'],
      conditions: ['Only if you are a Canadian citizen'],
      howTo:
        '1. The free service lets the Government of Canada reach travellers in an emergency abroad.\n2. Travel.gc.ca advisories for the destination are worth a last look before leaving.',
    },
    {
      id: 'day-log',
      title: 'Log the dates you leave and return to Canada',
      offsetDays: 0,
      durationDays: 1,
      dependsOn: [],
      documents: [],
      prepare: ['Boarding passes or passport stamps'],
      conditions: ['Only if you are a permanent resident, or plan to apply for citizenship'],
      howTo:
        '1. The citizenship physical presence calculator and the PR residency obligation both count days in Canada.\n2. Keeping each departure and return date as it happens is easier than rebuilding them later.\n3. This repeats every trip.',
    },
    {
      id: 'customs',
      title: 'Declare goods and cash when coming back',
      offsetDays: 14,
      durationDays: 1,
      dependsOn: [],
      documents: ['Receipts for goods bought abroad'],
      prepare: ['Value of goods bought or received abroad', 'Cash and monetary instruments carried'],
      howTo:
        '1. Residents returning after 24 hours or more have a personal exemption of CAN$200; after 48 hours, CAN$800, with limits on alcohol and tobacco; check current.\n2. Goods over the exemption are declared and taxed; food, plants and animals have their own rules.\n3. Cash or monetary instruments of CAN$10,000 or more are reported to the CBSA.\n4. This date is a placeholder; move it to the return date.',
    },
  ],
};
