import type { Playbook } from '../../domain/types';

const MOFA = 'https://www.mofa.go.jp';

export const visaJpCn: Playbook = {
  id: 'visa-jp-cn',
  title: 'Visiting Japan · Chinese passport',
  summary:
    'Paperwork plan for a short visit to Japan on a Chinese passport, from the tourist or family-visit visa through a designated agency or a consulate abroad to Visit Japan Web, arrival and leaving on time.',
  region: 'Japan',
  country: 'JP',
  family: 'visa-jp',
  citizen: 'CN',
  anchorKind: 'trip',
  ages: { from: 0 },
  conditions: [
    'You hold a passport of the People\'s Republic of China (mainland ordinary passport)',
    'You are visiting Japan for tourism or to see family or friends, for up to 90 days',
    'Not for work, study or long stays; those use other visas',
    'The date is the day you arrive in Japan',
  ],
  reviewedAt: '2026-09-27',
  version: 1,
  sources: [
    { title: 'Exemption of Visa (Short-Term Stay) — Ministry of Foreign Affairs of Japan', url: `${MOFA}/j_info/visit/visa/short/novisa.html` },
    { title: 'Chinese nationals travelling to Japan for a short stay (中国国籍の方が短期滞在を目的として日本へ渡航する場合) — MOFA', url: `${MOFA}/mofaj/toko/visa/tanki/china.html` },
    { title: 'Group and individual tourist visas for Chinese nationals (中国団体観光・個人観光査証) — MOFA', url: `${MOFA}/mofaj/toko/visa/topics/china.html` },
    { title: 'Single-entry short-stay visa: procedure for Chinese nationals in China, April 2025 (PDF) — MOFA', url: `${MOFA}/mofaj/files/100584186.pdf` },
    { title: 'Single-entry short-stay visa: Chinese nationals living outside China, April 2025 (PDF) — MOFA', url: `${MOFA}/mofaj/files/000472940.pdf` },
    { title: 'Multiple-entry short-stay visa for Chinese nationals: business and cultural figures (PDF) — MOFA', url: `${MOFA}/mofaj/files/100584187.pdf` },
    { title: 'Visa application form (English, PDF) — MOFA', url: `${MOFA}/mofaj/files/000124525.pdf` },
    { title: 'Letter of guarantor (身元保証書, PDF) — MOFA', url: `${MOFA}/mofaj/files/000472926.pdf` },
    { title: 'Letter of invitation (招へい理由書, PDF) — MOFA', url: `${MOFA}/mofaj/files/000472928.pdf` },
    { title: 'Itinerary (滞在予定表, PDF) — MOFA', url: `${MOFA}/mofaj/files/000472934.pdf` },
    { title: 'The JAPAN eVISA system (electronic visa) — MOFA', url: `${MOFA}/j_info/visit/visa/visaonline.html` },
    { title: 'Japanese embassies and consulates — MOFA', url: `${MOFA}/mofaj/annai/zaigai/list/index.html` },
    { title: 'Embassy of Japan in China: visas (签证) — Embassy of Japan', url: 'https://www.cn.emb-japan.go.jp/itpr_zh/visa-top.html' },
    { title: 'Visit Japan Web — Digital Agency', url: 'https://www.vjw.digital.go.jp/' },
    { title: 'Extension of period of stay — Immigration Services Agency of Japan', url: 'https://www.moj.go.jp/isa/applications/procedures/16-3.html' },
  ],
  steps: [
    {
      id: 'entry-check',
      title: 'Check whether you need a visa for Japan',
      offsetDays: -150,
      durationDays: 7,
      dependsOn: [],
      documents: ['Passport'],
      prepare: ['Passport expiry date', 'Purpose of the trip and how long you plan to stay', 'Where you live now: mainland China or another country'],
      howTo:
        "1. Japan's visa exemption list (MOFA, updated September 2025) covers 74 countries and regions, including Hong Kong and Macao SAR passports, but not the mainland Chinese passport.\n2. So a mainland Chinese passport holder needs a short-stay visa (短期滞在査証) for tourism or family visits; check the MOFA list again before booking, since it changes.\n3. The visa itself is valid 3 months from issue and cannot be extended; the stay (15, 30 or 90 days) is decided at landing.\n4. Short-stay status does not allow paid work in Japan.\n5. Not immigration advice; MOFA and the Japanese embassy or consulate are the reference.",
    },
    {
      id: 'visa-route',
      title: 'Pick the visa type: tourist, family visit or multiple entry',
      offsetDays: -140,
      durationDays: 7,
      dependsOn: ['entry-check'],
      documents: [],
      prepare: [
        'Whether you are joining a tour, travelling on your own, or staying with family or friends in Japan',
        'Your income and past trips to Japan, for the multiple-entry options',
        'Whether you live in mainland China or legally in a third country',
      ],
      howTo:
        '1. Tourism, living in China: apply through a travel agency in China that handles Japan visas; group tours (団体観光) allow a stay of up to 15 days with a guide, individual tourist visas (個人観光) 15 or 30 days.\n2. Individual tourist visas come as single entry for people with a certain level of income and their family, or multiple entry (3 years, 30 days per stay, or 5 years, 90 days per stay for high earners) under income and travel-history tiers; the tiers were changing in 2025 to 2026, so check current rules with the agency.\n3. Visiting relatives or friends (including a tourist trip where you sleep at their home): a short-stay visa based on documents from the person inviting you (招へい人) and a guarantor (身元保証人) in Japan; relatives here means a spouse and blood or in-law relatives within three degrees.\n4. Chinese nationals living in China can get a tourist eVISA (15 or 30 days, single entry) through an accredited agency; an eVISA is shown online at the airport, as a "visa issuance notice", not as a screenshot or printout.\n5. Living legally outside China: apply to the Japanese embassy or consulate for your place of residence, not in China (see the third-country step).',
    },
    {
      id: 'child-docs',
      title: "Gather a child's papers",
      offsetDays: -120,
      durationDays: 14,
      ages: { from: 0, to: 17 },
      conditions: ['Only if a child under 18 is travelling'],
      dependsOn: ['visa-route'],
      documents: ['Birth certificate', 'Passport'],
      prepare: [
        "Birth medical certificate (出生医学证明) or notarial certificate of kinship (亲属关系公证书) to show the parents",
        "The child's own passport and photo",
        'A consent letter signed by the parent who is not travelling, if the child travels with one parent or neither (check current with the agency or consulate)',
        "Parents' employment and bank papers, since a child's finances are shown through them",
      ],
      howTo:
        "1. Each child applies with their own passport and application form; a parent signs for a young child.\n2. MOFA's family-visit list accepts a notarial certificate of kinship or the birth medical certificate as proof of relationship; these do not expire.\n3. A consent letter from the absent parent is commonly asked for by agencies and airlines; confirm with the agency or consulate.\n4. For a family group, the agency can file the applications together with one list of applicants (申請人名簿).",
    },
    {
      id: 'host-docs',
      title: 'Ask your host in Japan for the invitation and guarantor papers',
      offsetDays: -100,
      durationDays: 30,
      conditions: ['Only if visiting family or friends in Japan, or staying at their home'],
      dependsOn: ['visa-route'],
      documents: ['Letter of invitation', 'Proof of relationship'],
      prepare: [
        "Letter of invitation (招へい理由書) and itinerary (滞在予定表), filled in by the host, addressed to the embassy or consulate you apply to",
        'Letter of guarantor (身元保証書): the guarantor covers your stay, return fare and compliance with the law',
        "Host's and guarantor's residence record for the whole household with relationships (住民票)",
        "Guarantor's employment certificate and latest income certificate (課税証明書) or tax certificate (納税証明書 その2)",
        'Copy of the residence card (在留カード), both sides, if the host or guarantor is not Japanese',
        'Proof of the reason for the trip if any, e.g. a wedding booking or medical note',
      ],
      howTo:
        "1. The host (招へい人) and guarantor (身元保証人) prepare these in Japan and send them to you, not to MOFA or the embassy; copies are accepted, but the consulate can ask for originals.\n2. Documents need to be issued within 3 months of the application.\n3. A foreign guarantor generally holds a status such as permanent resident, spouse of a Japanese national or an employment status with a period of stay of 3 years or more, and is not a dependant.\n4. If host and guarantor are the same person, the host's residence record, employment and residence-card copies are not repeated.\n5. A guarantor with no job (e.g. a pensioner) adds a short letter explaining why there is no employment certificate.",
    },
    {
      id: 'own-docs',
      title: 'Gather your own documents',
      offsetDays: -75,
      durationDays: 21,
      dependsOn: ['visa-route'],
      documents: ['Passport', 'Passport photo', 'Bank statements', 'Employment letter'],
      prepare: [
        'Visa application form, signed, with a photo 45 x 35 mm taken within 6 months',
        'Copy of the household register (户口簿)',
        "Residence permit (居住证) or residence certificate, if your hukou is outside the consulate's area",
        'Employment certificate (在职证明) with position, salary and dates, or student certificate',
        'Bank statements or deposit certificate (存款证明), and income or tax records for the multiple-entry tiers',
        'Flight booking and hotel bookings or itinerary, for tourist visas',
      ],
      howTo:
        '1. For a family visit from China, MOFA lists: application form, photo, passport, household register copy, residence permit if applicable, and proof of the relationship with the person in Japan.\n2. Tourist visa papers are set by the travel agency; ask it for its current list.\n3. Living outside China: add proof of legal residence in that country (residence permit, PR card or visa), a flight booking and proof of funds (bank balance or income certificate).\n4. Keep documents issued within the last 3 months.',
    },
    {
      id: 'apply-china',
      title: 'Apply through a designated agency in China',
      offsetDays: -50,
      durationDays: 14,
      conditions: ['Only if you live in mainland China'],
      dependsOn: ['own-docs', 'host-docs', 'child-docs'],
      documents: ['Passport', 'Visa application form'],
      prepare: [
        'Which Japanese mission covers where you live: Beijing embassy, or the consulates in Shanghai, Guangzhou, Shenyang, Chongqing, Qingdao or the Dalian office',
        'A travel agency or application agency (代理申请机构) designated by that mission',
        'Check the current visa and agency fees',
      ],
      howTo:
        '1. Applications from China go in, as a rule, through an agency designated by the embassy or consulate for your place of residence; you do not walk in to the embassy.\n2. Tourist visas: the agency books the trip or itinerary, prepares the Japanese guarantor papers and files the application; eVISA tourist applications also go through accredited agencies.\n3. Family visits: hand the agency your documents plus the host and guarantor papers from Japan.\n4. MOFA says checks take about 1 week once filed when nothing is missing, plus agency and courier time; allow longer, and apply early.\n5. The consulate can ask for more papers or an interview; submitting everything does not mean a visa will be issued.',
    },
    {
      id: 'apply-abroad',
      title: 'Apply from the country where you live',
      offsetDays: -50,
      durationDays: 14,
      conditions: ['Only if you live legally outside mainland China, e.g. in Canada'],
      dependsOn: ['own-docs', 'host-docs', 'child-docs'],
      documents: ['Passport', 'Residence permit', 'Visa application form'],
      prepare: [
        'Proof of legal residence (PR card, residence permit or long-term visa) valid for the whole trip',
        'The Japanese embassy or consulate covering your address, from the MOFA list',
        'Whether your country of residence is on the JAPAN eVISA list',
      ],
      howTo:
        "1. MOFA's procedure for Chinese nationals living outside China: apply to the Japanese embassy or consulate for your place of residence, or its visa agency; applications cannot be made inside Japan.\n2. Residents of Australia, Brazil, Cambodia, Canada, Saudi Arabia, South Africa, Taiwan, the United Kingdom and the United States (list as of May 15, 2026) can apply online for a single-entry tourist eVISA on the JAPAN eVISA website, arriving by air or on the listed ferries.\n3. Family visits and multiple-entry visas still go to the embassy or consulate as a paper application with a visa sticker.\n4. The document list is shorter for residents of North America, Western Europe, Australia, New Zealand and some Asian places; check the mission's page.\n5. MOFA estimates about 1 week after all papers are in; the mission can ask for an interview.",
    },
    {
      id: 'decision',
      title: 'Collect the visa and check its details',
      offsetDays: -30,
      durationDays: 14,
      validForDays: 90,
      dependsOn: ['apply-china', 'apply-abroad'],
      documents: ['Visa', 'Passport'],
      prepare: ['Name and passport number on the visa', 'Single or multiple entry, and the stay allowed', 'Date the visa expires'],
      howTo:
        '1. A sticker visa comes back in the passport; an eVISA arrives as a visa issuance notice in your eVISA account.\n2. The visa is valid 3 months for entry and cannot be extended, so enter within that window.\n3. The consulate does not give reasons for a refusal.\n4. With a multiple-entry visa, check the first-trip conditions, e.g. an agency-arranged first trip.',
    },
    {
      id: 'flights',
      title: 'Book flights and travel medical insurance',
      offsetDays: -21,
      durationDays: 7,
      dependsOn: ['decision'],
      documents: ['Flight itinerary', 'Travel insurance policy'],
      prepare: ['Trip dates within the stay the visa allows', 'Return or onward ticket'],
      howTo:
        '1. Book after the visa is issued so a refusal or delay does not cost the fare.\n2. Japanese public health insurance does not cover short-term visitors; travel medical insurance is worth having, though not a visa condition.\n3. eVISA holders enter by air, or by the scheduled ferries named by MOFA.',
    },
    {
      id: 'vjw',
      title: 'Register on Visit Japan Web before you fly',
      offsetDays: -3,
      durationDays: 3,
      dependsOn: ['flights'],
      documents: ['Passport', 'Flight itinerary'],
      prepare: ['Passport details', 'Flight number and address in Japan', 'A phone with the QR codes saved'],
      howTo:
        '1. Visit Japan Web is the Digital Agency site for entering immigration and customs details online before arrival; it gives QR codes to show at the airport.\n2. It is optional; paper cards on the plane still work.\n3. Register each traveller, including children, in one account if you like.',
    },
    {
      id: 'arrival',
      title: 'Arrival: landing examination',
      offsetDays: 0,
      durationDays: 1,
      dependsOn: ['vjw'],
      documents: ['Passport', 'Visa', 'Flight itinerary'],
      prepare: ['Address and phone number of your hotel or host', 'Return ticket', 'eVISA holders: the visa issuance notice open online, not a screenshot'],
      howTo:
        "1. The immigration officer takes fingerprints and a face photo, checks the visa and decides the period of stay (15, 30 or 90 days); holding a visa does not mean entry is assured.\n2. The landing sticker in the passport shows the status (Temporary Visitor) and the last day of the stay.\n3. Note that date; the rest of this plan uses it.",
    },
    {
      id: 'extend',
      title: 'Ask the immigration bureau for more time',
      offsetDays: 10,
      durationDays: 7,
      conditions: ['Only if something like illness or an accident keeps you in Japan past the date you were given'],
      dependsOn: ['arrival'],
      documents: ['Passport'],
      prepare: ['Reason and proof, e.g. a doctor\'s letter', 'Return ticket and proof of funds', 'Check the current fee'],
      howTo:
        "1. Extensions of a period of stay are filed at the regional immigration bureau (出入国在留管理局) for where you are staying, before the stay ends.\n2. For Temporary Visitor status they are the exception, for reasons such as illness or accidents (check current); a wish to stay longer is not usually enough.\n3. The Immigration Services Agency lists the fee as a revenue stamp (6,000 yen, or 5,500 yen online, check current).\n4. The date here is an estimate; move it to before the last day on your landing sticker.",
    },
    {
      id: 'leave',
      title: 'Leave on time and keep the records',
      offsetDays: 30,
      durationDays: 1,
      dependsOn: ['arrival'],
      documents: ['Passport', 'Boarding pass'],
      prepare: ['The last day on the landing sticker', 'Copies of the visa and boarding passes'],
      howTo:
        '1. Leave by the last day of your period of stay; overstaying can lead to removal and a ban on returning.\n2. Keep the visa, stamps and boarding passes; multiple-entry tiers and later applications look at past trips to Japan.\n3. The 30 days here is an estimate; move it to your real date.',
    },
  ],
};
