import type { Playbook } from '../../domain/types';

const GOV = 'https://www.gov.uk';

export const visaGbPh: Playbook = {
  id: 'visa-gb-ph',
  title: 'Visiting the United Kingdom · Philippine passport',
  summary:
    'Paperwork plan for a Philippine passport holder visiting the UK for tourism, family or a business trip on a Standard Visitor visa: online form, biometrics at VFS in Manila, Cebu or abroad, long-term visit visas, leaving the Philippines, arrival and coming home.',
  region: 'United Kingdom',
  country: 'GB',
  citizen: 'PH',
  family: 'visa-gb',
  anchorKind: 'trip',
  ages: { from: 0 },
  conditions: [
    'You hold a Philippine passport and are not a British or Irish citizen',
    'You are visiting for tourism, family or friends, or a permitted business activity, for up to 6 months',
    'The date is the day you arrive in the United Kingdom',
    'This is a planning aid, not immigration advice; the GOV.UK and Philippine agency pages are the reference',
  ],
  reviewedAt: '2026-09-27',
  version: 1,
  sources: [
    { title: 'Check if you need a UK visa — GOV.UK', url: `${GOV}/check-uk-visa` },
    { title: 'Visit the UK as a Standard Visitor — GOV.UK', url: `${GOV}/standard-visitor` },
    { title: 'Standard Visitor: Apply for a Standard Visitor visa — GOV.UK', url: `${GOV}/standard-visitor/apply-standard-visitor-visa` },
    { title: 'Standard Visitor: If you\'re under 18 — GOV.UK', url: `${GOV}/standard-visitor/if-youre-under-18` },
    { title: 'Standard Visitor: Extend your stay — GOV.UK', url: `${GOV}/standard-visitor/extend-your-stay` },
    { title: 'Visa processing times: applications outside the UK — GOV.UK', url: `${GOV}/guidance/visa-processing-times-applications-outside-the-uk` },
    { title: 'UK visa application centres in the Philippines — VFS Global', url: 'https://visa.vfsglobal.com/phl/en/gbr' },
    { title: 'Philippine passport appointments — Department of Foreign Affairs', url: 'https://consular.dfa.gov.ph/' },
    { title: 'Travel tax — TIEZA', url: 'https://tieza.gov.ph/travel-tax/' },
    { title: 'Bureau of Immigration — Philippines', url: 'https://immigration.gov.ph/' },
    { title: 'Commission on Filipinos Overseas', url: 'https://cfo.gov.ph/' },
    { title: 'Travel clearance for minors — DSWD', url: 'https://www.dswd.gov.ph/' },
    { title: 'eTravel — Philippine travel information system', url: 'https://etravel.gov.ph/' },
  ],
  steps: [
    {
      id: 'entry-document',
      title: 'Check which UK visa fits the trip',
      offsetDays: -150,
      durationDays: 7,
      dependsOn: [],
      documents: ['Passport'],
      prepare: ['Purpose of the trip', 'How long you plan to stay', 'How often you expect to visit over the next few years'],
      howTo:
        '1. The GOV.UK visa checker says a Philippine citizen coming for tourism or to visit family or friends needs a visa: the Standard Visitor visa.\n2. The UK electronic travel authorisation (ETA) is for visa-free nationalities, so it does not replace the visa on a Philippine passport.\n3. A Standard Visitor can usually stay up to 6 months per visit; work and study longer than the visitor rules allow need other visas.\n4. Frequent visitors can apply for a long-term Standard Visitor visa valid for 2, 5 or 10 years, still up to 6 months per visit.\n5. Coming to marry or join a partner, or passing through the UK, has other routes; check the GOV.UK visa checker for those.',
    },
    {
      id: 'passport',
      title: 'Renew the Philippine passport if it runs short',
      offsetDays: -120,
      durationDays: 30,
      conditions: ['Only if your passport expires before the end of the trip, or soon after, or has no blank page'],
      dependsOn: [],
      documents: ['Passport', 'PSA birth certificate'],
      prepare: ['DFA online appointment', 'Old passport', 'A valid government ID'],
      howTo:
        '1. GOV.UK asks for a passport valid for the whole stay, with a blank page for the visa.\n2. A long-term visa cannot outlast the passport, so renew first if you want a 2, 5 or 10-year visa.\n3. Book a renewal on the DFA online appointment system.',
    },
    {
      id: 'documents',
      title: 'Gather proof of ties and funds',
      offsetDays: -120,
      durationDays: 21,
      dependsOn: ['entry-document'],
      documents: ['Certificate of employment', 'Bank statements', 'Income tax return'],
      prepare: [
        'Certificate of employment with position, salary and approved leave dates',
        'Recent bank statements showing funds for the trip',
        'Income tax return (BIR Form 2316 or 1701)',
        'Business registration (DTI or SEC) if self-employed',
        'Property titles or other ties to the Philippines',
        'Travel history for the last 10 years and old passports',
        'Accommodation details and travel dates',
      ],
      howTo:
        '1. The decision weighs whether you will leave at the end of the visit, can pay for the trip, and are not living in the UK through repeated visits.\n2. Documents not in English or Welsh need a certified translation.\n3. Upload or bring copies as the online checklist says; originals may be asked for.',
    },
    {
      id: 'host-invitation',
      title: 'Get an invitation letter and your host\'s status proof',
      offsetDays: -120,
      durationDays: 21,
      conditions: ['Only if visiting family or friends'],
      dependsOn: ['entry-document'],
      documents: ['Letter of invitation', "Copy of host's UK passport or visa, or eVisa share code details"],
      prepare: [
        'Host name, UK address, phone and immigration status',
        'Your relationship, with PSA birth or marriage certificates if family',
        'Dates, where you will stay and who pays',
        "Host's proof of accommodation and bank statements if they support the trip",
      ],
      howTo:
        '1. An invitation letter is not a set requirement, but it supports the stated purpose of the visit.\n2. The host signs a letter with their details and status, your relationship, the dates, where you will stay and who pays.\n3. If the host pays or houses you, add their bank statements and proof they can accommodate you, such as a tenancy or ownership record.',
    },
    {
      id: 'child-documents',
      title: 'Prepare a child\'s application papers',
      offsetDays: -120,
      durationDays: 21,
      conditions: ['Only if a child under 18 is travelling'],
      dependsOn: ['entry-document'],
      documents: ['PSA birth certificate', 'Consent letter'],
      prepare: [
        "Parents' or guardian's written consent for the child to travel to the UK, with full contact details",
        'Details of who will care for the child in the UK: name, date of birth, address and relationship',
        'Consent for the child to stay with that person',
      ],
      howTo:
        '1. Each child has their own application and visa.\n2. GOV.UK asks for a parent or guardian\'s written consent and contact details, and proof of suitable care and accommodation in the UK.\n3. Children can travel without an adult if the consent and care arrangements are in place.\n4. The PSA birth certificate shows who the parents are; the Philippine departure side is in the DSWD step below.',
    },
    {
      id: 'apply',
      title: 'Apply online and pay the visa fee',
      offsetDays: -80,
      durationDays: 7,
      dependsOn: ['passport', 'documents', 'host-invitation', 'child-documents'],
      documents: ['Passport', 'Application confirmation', 'Bank statements'],
      prepare: [
        'Check the current fee: GBP 135 for up to 6 months when this plan was reviewed',
        'Long-term visas: GBP 506 for 2 years, GBP 903 for 5 years, GBP 1,128 for 10 years when this plan was reviewed',
        'Answers on work, finances, criminal history and 10 years of travel',
      ],
      howTo:
        '1. The earliest you can apply is 3 months before you travel; the date here is about 12 weeks ahead.\n2. Apply on GOV.UK; it books the biometrics appointment through the visa application centre provider.\n3. Pay the fee online; priority services cost extra where offered.\n4. A long-term visa costs more up front; check current rules on what happens if a shorter visa is issued instead.',
    },
    {
      id: 'biometrics-ph',
      title: 'Give biometrics at VFS in Manila or Cebu',
      offsetDays: -65,
      durationDays: 14,
      conditions: ['Only if you are applying from the Philippines'],
      dependsOn: ['apply'],
      documents: ['Passport', 'Appointment confirmation', 'Application confirmation'],
      prepare: ['Supporting documents as the checklist says', 'Check current VFS centre locations and optional services'],
      howTo:
        '1. UK visa application centres in the Philippines are run by VFS Global; check current locations, which have included Manila and Cebu.\n2. Fingerprints and a photo are taken at the appointment.\n3. GOV.UK says the passport is returned the same day; check current practice at your centre.',
    },
    {
      id: 'biometrics-abroad',
      title: 'Apply from the country where you are living',
      offsetDays: -65,
      durationDays: 14,
      conditions: ['Only if you are living or staying legally outside the Philippines'],
      dependsOn: ['apply'],
      documents: ['Passport', 'Residence permit', 'Appointment confirmation'],
      prepare: ['Proof of legal status in that country', 'The nearest UK visa application centre there'],
      howTo:
        '1. GOV.UK notes the visa application centre can be in another country, so you can apply where you are rather than returning to the Philippines.\n2. Bring proof of your status there; the decision may consider your ties to that country as well as the Philippines.\n3. Processing times and priority options differ by country; check the GOV.UK processing times page.',
    },
    {
      id: 'decision',
      title: 'Wait for the decision and check the visa',
      offsetDays: -35,
      durationDays: 21,
      dependsOn: ['biometrics-ph', 'biometrics-abroad'],
      documents: ['Visa vignette', 'Decision letter'],
      prepare: ['Check the visa: name, dates, visa type'],
      howTo:
        '1. GOV.UK says a decision usually comes within 3 weeks after the biometrics appointment.\n2. Check the visa for errors right away and report them.\n3. Book flights once the visa is issued, so a refusal or delay does not cost the fare.',
    },
    {
      id: 'dswd-clearance',
      title: 'Get a DSWD travel clearance for a child',
      offsetDays: -10,
      durationDays: 14,
      conditions: ['Only if a Filipino child under 18 is leaving without a parent, or with someone other than a parent'],
      dependsOn: ['decision'],
      documents: ['DSWD travel clearance', 'PSA birth certificate'],
      prepare: ["Parents' written consent", 'Details of the adult travelling with the child', 'Photos of the child'],
      howTo:
        '1. The Department of Social Welfare and Development (DSWD) issues travel clearances for Filipino minors travelling abroad alone or with an adult who is not a parent.\n2. A child travelling with a parent generally does not need one; check current exemptions on the DSWD site.\n3. Apply online or at a DSWD field office; check current processing time and validity, and apply earlier if you can.',
    },
    {
      id: 'cfo',
      title: 'Check whether a CFO certificate applies',
      offsetDays: -7,
      durationDays: 21,
      conditions: [
        'Only if you are going to join a foreign spouse, partner or fiancé(e), or emigrating, rather than just visiting',
      ],
      dependsOn: ['decision'],
      documents: ['CFO certificate'],
      prepare: ['Marriage certificate or proof of relationship', "Partner's passport copy", 'Visa'],
      howTo:
        '1. The Commission on Filipinos Overseas (CFO) runs guidance and counselling for Filipinos leaving to join a foreign spouse, partner or fiancé(e), and registration for emigrants; the Bureau of Immigration checks the CFO certificate at departure.\n2. A short visit on a Standard Visitor visa is generally not an emigrant departure, but visiting a foreign partner can prompt questions at the counter; check with the CFO which case yours is before flying.\n3. Moving to the UK on a family visa is outside this plan.',
    },
    {
      id: 'travel-tax',
      title: 'Pay the Philippine travel tax or check the exemption',
      offsetDays: -14,
      durationDays: 7,
      dependsOn: ['decision'],
      documents: ['Travel tax receipt'],
      prepare: ['Ticket and booking reference', 'Proof of exemption or reduced rate, if any'],
      howTo:
        '1. Filipinos and some residents leaving the Philippines pay travel tax to TIEZA: PHP 1,620 economy or PHP 2,700 first class at the full rate when this plan was reviewed.\n2. Many airline tickets bought in the Philippines include it; check the fare breakdown.\n3. Reduced rates and exemptions exist, for example for some minors and overseas Filipino workers; check TIEZA.\n4. If not included, pay online on the TIEZA site or at the airport counter before check-in.',
    },
    {
      id: 'departure-documents',
      title: 'Pack papers for the Bureau of Immigration departure check',
      offsetDays: -7,
      durationDays: 5,
      dependsOn: ['decision'],
      documents: ['Passport', 'Visa vignette', 'Return ticket', 'Certificate of employment'],
      prepare: [
        'Return or onward ticket',
        'Hotel booking or host address',
        'Proof of work, approved leave, business or school',
        'Proof of funds',
        'Invitation letter and relationship proof if visiting family or friends',
        'Affidavit of support from the sponsor if someone else pays',
      ],
      howTo:
        '1. At departure, a Bureau of Immigration (BI) officer checks the passport, visa, boarding pass and return ticket, following inter-agency (IACAT) departure guidelines meant to stop trafficking and illegal recruitment.\n2. Some travellers are sent to secondary inspection and asked for supporting papers; being refused departure is called offloading.\n3. Keep the papers in the carry-on, not the checked bag.\n4. Check the current IACAT guidelines on the BI site before the trip.',
    },
    {
      id: 'departure',
      title: 'Leave the Philippines',
      offsetDays: -1,
      durationDays: 1,
      dependsOn: ['departure-documents', 'travel-tax', 'cfo', 'dswd-clearance'],
      documents: ['Passport', 'Visa vignette', 'Boarding pass', 'Travel tax receipt'],
      prepare: ['Arrive at the airport early for immigration lines', 'Check any eTravel or e-Gate registration the BI currently asks departing travellers for'],
      howTo:
        '1. Check in, then go through BI departure; answer questions about the trip plainly.\n2. If referred to secondary inspection, show the papers from the previous step.\n3. The date here is the day before arrival; move it to the real flight.',
    },
    {
      id: 'arrival',
      title: 'Arrival: UK Border Force',
      offsetDays: 0,
      durationDays: 1,
      dependsOn: ['departure'],
      documents: ['Passport', 'Visa vignette', 'Return ticket'],
      prepare: ['UK address for the stay', 'Return ticket, proof of funds and invitation letter in carry-on'],
      howTo:
        '1. A Border Force officer checks the visa and may ask about the visit; carry the key supporting papers.\n2. Visa holders generally use the staffed desks; check current eGate eligibility for your passport.\n3. A Standard Visitor can usually stay up to 6 months per visit, and not beyond the visa end date.',
    },
    {
      id: 'extend',
      title: 'Check whether the stay can be extended',
      offsetDays: 150,
      durationDays: 14,
      conditions: ['Only if you need to stay longer than planned, while still in the UK'],
      dependsOn: ['arrival'],
      documents: ['Passport', 'Visa vignette'],
      prepare: ['Reason for staying longer', 'Proof of funds', 'Check the current fee (GBP 1,172 when this plan was reviewed)'],
      howTo:
        '1. A Standard Visitor can extend only up to a total of 6 months in the UK, so a visit already granted 6 months usually cannot be extended.\n2. Longer stays are only for specific cases such as private medical treatment, some academics, and PLAB test or clinical attachment candidates.\n3. Apply from inside the UK before the current permission ends.\n4. Switching from visitor to most other visas from inside the UK is not allowed; check GOV.UK.',
    },
    {
      id: 'etravel',
      title: 'Register on eTravel before flying home',
      offsetDays: 27,
      durationDays: 3,
      dependsOn: ['arrival'],
      documents: ['eTravel QR code'],
      prepare: ['Passport', 'Flight number', 'Address in the Philippines'],
      howTo:
        '1. eTravel is the Philippine government\'s free online travel declaration; arriving travellers, Filipinos included, register before landing, usually within 72 hours of the flight; check the current window.\n2. Use etravel.gov.ph or the eGovPH app only; look-alike sites charge fees.\n3. Show the QR code on arrival in the Philippines.',
    },
    {
      id: 'return',
      title: 'Leave the UK on time and keep the records',
      offsetDays: 30,
      durationDays: 1,
      dependsOn: ['etravel'],
      documents: ['Passport', 'Boarding pass'],
      prepare: ['Copies of the visa and boarding passes'],
      howTo:
        '1. Leave before the 6-month limit and the visa end date.\n2. Keep boarding passes; later UK applications ask about travel history, and a clean record helps long-term visa applications.\n3. The 30 days here is an estimate; move it to the real return flight.',
    },
  ],
};
