import type { Playbook } from '../../domain/types';

const TSG = 'https://travel.state.gov/content/travel/en/us-visas';

export const visaUsPh: Playbook = {
  id: 'visa-us-ph',
  title: 'Visiting the United States · Philippine passport',
  summary:
    'Paperwork plan for a Philippine passport holder visiting the US for tourism, family or a business trip on a B1/B2 visa: DS-160, the interview in Manila or abroad, leaving the Philippines, arrival, extensions and coming home.',
  region: 'United States',
  country: 'US',
  citizen: 'PH',
  family: 'visa-us',
  anchorKind: 'trip',
  ages: { from: 0 },
  conditions: [
    'You hold a Philippine passport and no US passport or green card',
    'You are visiting for tourism, family or friends, or a short business trip, not to work or study',
    'The date is the day you arrive in the United States',
    'This is a planning aid, not immigration advice; the State Department, US Embassy Manila and Philippine agency pages are the reference',
  ],
  reviewedAt: '2026-09-27',
  version: 1,
  sources: [
    { title: 'Visitor visa — travel.state.gov', url: `${TSG}/tourism-visit/visitor.html` },
    { title: 'DS-160: Online nonimmigrant visa application — travel.state.gov', url: `${TSG}/visa-information-resources/forms/ds-160-online-nonimmigrant-visa-application.html` },
    { title: 'Photo requirements — travel.state.gov', url: `${TSG}/visa-information-resources/photos.html` },
    { title: 'Fees for visa services — travel.state.gov', url: `${TSG}/visa-information-resources/fees/fees-visa-services.html` },
    { title: 'Visa appointment wait times — travel.state.gov', url: `${TSG}/visa-information-resources/global-visa-wait-times.html` },
    { title: 'Visa Waiver Program — travel.state.gov', url: `${TSG}/tourism-visit/visa-waiver-program.html` },
    { title: 'Nonimmigrant visas — U.S. Embassy in the Philippines', url: 'https://ph.usembassy.gov/visas/nonimmigrant-visas/' },
    { title: 'I-94 arrival/departure record — U.S. Customs and Border Protection', url: 'https://i94.cbp.dhs.gov/' },
    { title: 'I-539, Application to Extend/Change Nonimmigrant Status — USCIS', url: 'https://www.uscis.gov/i-539' },
    { title: 'Philippine passport appointments — Department of Foreign Affairs', url: 'https://consular.dfa.gov.ph/' },
    { title: 'Travel tax — TIEZA', url: 'https://tieza.gov.ph/travel-tax/' },
    { title: 'Bureau of Immigration — Philippines', url: 'https://immigration.gov.ph/' },
    { title: 'Commission on Filipinos Overseas', url: 'https://cfo.gov.ph/' },
    { title: 'Travel clearance for minors — DSWD', url: 'https://www.dswd.gov.ph/' },
    { title: 'eTravel — Philippine travel information system', url: 'https://etravel.gov.ph/' },
  ],
  steps: [
    {
      id: 'entry-document',
      title: 'Check which US visa fits the trip',
      offsetDays: -300,
      durationDays: 7,
      dependsOn: [],
      documents: ['Passport'],
      prepare: ['Purpose of the trip', 'How long you plan to stay', 'Any earlier US visa, and when it expired'],
      howTo:
        '1. The Philippines is not in the US Visa Waiver Program, so ESTA is not an option on a Philippine passport; a visitor visa is needed.\n2. The B1/B2 visitor visa covers tourism, visiting family or friends, medical treatment and business meetings; work and study need other visas.\n3. If you hold an unexpired B1/B2 visa in a valid or old passport, you can travel on it; carry both passports if the visa is in the old one.\n4. The officer decides the visa length and entries; check the reciprocity table on travel.state.gov for what is typical for the Philippines.\n5. Holders of another passport that is in the Visa Waiver Program can check ESTA instead of this plan.',
    },
    {
      id: 'passport',
      title: 'Renew the Philippine passport if it runs short',
      offsetDays: -270,
      durationDays: 30,
      conditions: ['Only if your passport expires within about 6 months after the trip, or has few blank pages'],
      dependsOn: [],
      documents: ['Passport', 'PSA birth certificate'],
      prepare: ['DFA online appointment', 'Old passport', 'A valid government ID'],
      howTo:
        '1. Book a renewal on the DFA online appointment system; walk-in lanes exist for some groups.\n2. The US generally expects the passport to be valid for 6 months past the stay unless the country has an agreement; check the current rule for the Philippines on travel.state.gov.\n3. Renew before the DS-160, since the form asks for the passport number.\n4. Processing times vary by site; check current.',
    },
    {
      id: 'documents',
      title: 'Gather proof of ties and funds',
      offsetDays: -240,
      durationDays: 30,
      dependsOn: ['entry-document'],
      documents: ['Certificate of employment', 'Bank statements', 'Income tax return'],
      prepare: [
        'Certificate of employment with position, salary and approved leave dates',
        'Recent bank statements or a bank certificate',
        'Income tax return (BIR Form 2316 or 1701)',
        'Business registration (DTI or SEC) if self-employed',
        'Property titles, school enrolment or other ties to home',
        'Rough itinerary and where you will stay',
      ],
      howTo:
        '1. A B1/B2 interview mainly weighs whether you will return home: work, family, property and study in the Philippines.\n2. The officer may not look at papers; bring them anyway, organised so you can hand over one quickly.\n3. Old passports with earlier US or other visas help show travel history.\n4. If someone else pays, bring their letter and proof of funds.',
    },
    {
      id: 'host-invitation',
      title: 'Get an invitation letter and your host\'s status proof',
      offsetDays: -240,
      durationDays: 21,
      conditions: ['Only if visiting family or friends'],
      dependsOn: ['entry-document'],
      documents: ['Letter of invitation', "Copy of host's US passport, green card or visa"],
      prepare: [
        'Host name, US address, phone and status in the US',
        'Your relationship, with PSA birth or marriage certificates if family',
        'Dates of the visit and who pays for what',
        "Host's proof of income if they are supporting the trip",
      ],
      howTo:
        '1. The US does not ask for an invitation letter for a B2 visa, but it can back up the purpose of the trip.\n2. The host writes a short signed letter: who you are, the relationship, dates, where you will stay and who pays.\n3. If the host sponsors the trip, add their recent bank statement or tax return; Form I-134 is not used for ordinary visitor visas.\n4. Relationship documents help if the officer asks how you are related.',
    },
    {
      id: 'child-documents',
      title: 'Prepare a child\'s application papers',
      offsetDays: -240,
      durationDays: 30,
      conditions: ['Only if a child under 18 is travelling'],
      dependsOn: ['entry-document'],
      documents: ['PSA birth certificate', 'School certificate of enrolment'],
      prepare: [
        "Both parents' passports and visas, or proof of their status",
        'Written consent from a parent who is not travelling or not attending',
        'School enrolment and the school break dates',
      ],
      howTo:
        '1. Each child, including babies, needs their own passport, DS-160 and visa.\n2. A parent or legal guardian fills in the DS-160 for a young child and usually attends with them; check current rules on which children still need to appear in person.\n3. The PSA birth certificate shows who the parents are.\n4. If only one parent travels, bring a signed consent letter from the other; the Philippine departure side is in the DSWD step below.',
    },
    {
      id: 'ds160',
      title: 'Fill in the DS-160 and pay the visa fee',
      offsetDays: -200,
      durationDays: 14,
      dependsOn: ['passport', 'documents', 'host-invitation', 'child-documents'],
      documents: ['DS-160 confirmation page', 'Visa fee receipt', 'Photo'],
      prepare: [
        'Passport, travel history for the last 5 years, and past US visas',
        'Work and education history, family details, US address',
        'A recent photo meeting the State Department photo rules',
        'Check the current B1/B2 fee (MRV fee) and whether a separate visa integrity fee applies',
      ],
      howTo:
        '1. Complete the DS-160 online and save the application ID; the form times out, so save often.\n2. Answers are checked against the interview, so keep them consistent and truthful.\n3. Create a profile on the embassy\'s appointment site, then pay the application fee; it is not refundable and is usually valid for a limited time to book, so check the current rule.\n4. US law passed in 2025 added a visa integrity fee paid when a visa is issued; check current status and amount on travel.state.gov.\n5. Each traveller, including children, has their own DS-160 and fee.',
    },
    {
      id: 'appointment',
      title: 'Book the interview, or check for an interview waiver',
      offsetDays: -190,
      durationDays: 7,
      dependsOn: ['ds160'],
      documents: ['Appointment confirmation'],
      prepare: [
        'The current appointment wait for Manila on travel.state.gov',
        'Whether your last B1/B2 visa qualifies for renewal without an interview',
      ],
      howTo:
        '1. Waits for a first visitor-visa interview in Manila have often been many months; the 300 days this plan starts ahead is an estimate, so check the current wait tool and book as early as you can.\n2. Since 2025 the State Department has narrowed interview waivers; the main remaining case is renewing a full-validity B1/B2 that expired within the last 12 months and was issued when you were 18 or older. Check current eligibility on the appointment site.\n3. If a waiver applies, the site gives a document drop-off option instead of an interview.\n4. Expedited appointments exist for urgent reasons such as a family emergency; a tourist trip normally does not qualify.',
    },
    {
      id: 'interview-manila',
      title: 'Attend the interview at the US Embassy in Manila',
      offsetDays: -120,
      durationDays: 1,
      conditions: ['Only if you are applying in the Philippines and need an interview'],
      dependsOn: ['appointment'],
      documents: ['Passport', 'DS-160 confirmation page', 'Appointment confirmation', 'Certificate of employment', 'Bank statements'],
      prepare: [
        'Old passports with earlier US visas',
        'The supporting papers from the earlier steps, in one folder',
        'Check the embassy list of items not allowed inside; bags and electronics are restricted',
      ],
      howTo:
        '1. Visa interviews in the Philippines take place at the consular section of the US Embassy on Roxas Boulevard, Manila.\n2. Fingerprints are taken, then a short interview; answer briefly and truthfully.\n3. If approved, the passport stays for visa printing and is sent back by courier or held for pick-up as chosen on the appointment site.\n4. A refusal under section 214(b) means the officer was not convinced of ties to home; you can reapply with a new fee when circumstances change.\n5. A 221(g) slip means more papers or administrative processing; follow its instructions.',
    },
    {
      id: 'interview-abroad',
      title: 'Apply at a US embassy in the country where you live',
      offsetDays: -120,
      durationDays: 1,
      conditions: ['Only if you live legally in a country other than the Philippines'],
      dependsOn: ['appointment'],
      documents: ['Passport', 'Residence permit', 'DS-160 confirmation page', 'Appointment confirmation'],
      prepare: [
        'Residence permit or visa for that country, valid well past the interview',
        'Proof of work or study there',
        "That country's appointment site and its local fee payment method",
      ],
      howTo:
        '1. Since September 2025 the State Department asks nonimmigrant visa applicants to apply in their country of nationality or of residence; check current rules.\n2. If you live legally in, for example, Canada, Japan or the UK, you can apply at the US embassy or consulate there and show proof of residence.\n3. A short stay somewhere as a tourist is generally not residence for this purpose; check with that post before booking.\n4. Ties the officer weighs are then to the country where you live, plus the Philippines.\n5. Wait times differ by post; check the wait tool for that city.',
    },
    {
      id: 'waiver',
      title: 'Drop off documents for a renewal without interview',
      offsetDays: -150,
      durationDays: 30,
      conditions: ['Only if the appointment site confirms you qualify for an interview waiver'],
      dependsOn: ['ds160'],
      documents: ['Passport', 'Previous US visa', 'DS-160 confirmation page', 'Photo'],
      prepare: ['The drop-off appointment and its document list', 'Old passport with the previous visa'],
      howTo:
        '1. Deliver the passport and documents to the drop-off location the appointment site names.\n2. The consular officer may still call you in for an interview.\n3. Processing time varies; plan without the passport for several weeks.',
    },
    {
      id: 'visa-back',
      title: 'Get the passport back and check the visa',
      offsetDays: -90,
      durationDays: 21,
      dependsOn: ['interview-manila', 'interview-abroad', 'waiver'],
      documents: ['Passport', 'US visa'],
      prepare: ['Check name, date of birth, passport number, visa type, entries and expiry'],
      howTo:
        '1. Check the visa foil for errors right away and report them to the embassy.\n2. The visa expiry date is the last day to enter, not how long you can stay; the stay is set at the border.\n3. Book flights only once the visa is in hand, so a refusal or delay does not cost the fare.',
    },
    {
      id: 'dswd-clearance',
      title: 'Get a DSWD travel clearance for a child',
      offsetDays: -45,
      durationDays: 21,
      conditions: ['Only if a Filipino child under 18 is leaving without a parent, or with someone other than a parent'],
      dependsOn: ['visa-back'],
      documents: ['DSWD travel clearance', 'PSA birth certificate'],
      prepare: ["Parents' written consent", 'Details of the adult travelling with the child', 'Photos of the child'],
      howTo:
        '1. The Department of Social Welfare and Development (DSWD) issues travel clearances for Filipino minors travelling abroad alone or with an adult who is not a parent.\n2. A child travelling with a parent generally does not need one; check current exemptions on the DSWD site.\n3. Apply online or at a DSWD field office; check current processing time and validity.',
    },
    {
      id: 'cfo',
      title: 'Check whether a CFO certificate applies',
      offsetDays: -60,
      durationDays: 30,
      conditions: [
        'Only if you are going to join a foreign spouse, partner or fiancé(e), or emigrating, rather than just visiting',
      ],
      dependsOn: ['visa-back'],
      documents: ['CFO certificate'],
      prepare: ['Marriage certificate or proof of relationship', "Partner's passport copy", 'Visa'],
      howTo:
        '1. The Commission on Filipinos Overseas (CFO) runs guidance and counselling for Filipinos leaving to join a foreign spouse, partner or fiancé(e), and registration for emigrants; the Bureau of Immigration checks the CFO certificate at departure.\n2. A short visit on a B1/B2 visitor visa is generally not an emigrant departure, but visiting a foreign partner can prompt questions at the counter; check with the CFO which case yours is before flying.\n3. Registration is booked online on the CFO site; check current requirements and fees.',
    },
    {
      id: 'travel-tax',
      title: 'Pay the Philippine travel tax or check the exemption',
      offsetDays: -30,
      durationDays: 7,
      dependsOn: ['visa-back'],
      documents: ['Travel tax receipt'],
      prepare: ['Ticket and booking reference', 'Proof of exemption or reduced rate, if any'],
      howTo:
        '1. Filipinos and some residents leaving the Philippines pay travel tax to TIEZA: PHP 1,620 economy or PHP 2,700 first class at the full rate when this plan was reviewed.\n2. Many airline tickets bought in the Philippines include it; check the fare breakdown.\n3. Reduced rates and exemptions exist, for example for some minors and overseas Filipino workers; check TIEZA.\n4. If not included, pay online on the TIEZA site or at the airport counter before check-in.',
    },
    {
      id: 'departure-documents',
      title: 'Pack papers for the Bureau of Immigration departure check',
      offsetDays: -7,
      durationDays: 5,
      dependsOn: ['visa-back'],
      documents: ['Passport', 'US visa', 'Return ticket', 'Certificate of employment'],
      prepare: [
        'Return or onward ticket',
        'Hotel booking or host address',
        'Proof of work, approved leave, business or school',
        'Proof of funds',
        'Invitation letter and relationship proof if visiting family or friends',
        'Affidavit of support from the sponsor if someone else pays',
      ],
      howTo:
        '1. At departure, a Bureau of Immigration (BI) officer checks the passport, visa, boarding pass and return ticket, following inter-agency (IACAT) departure guidelines meant to stop trafficking and illegal recruitment.\n2. Some travellers are sent to secondary inspection and asked for supporting papers; being refused departure is called offloading.\n3. Keep the papers in the carry-on, not the checked bag.\n4. Check the current IACAT guidelines on the BI site before the trip.',
    },
    {
      id: 'departure',
      title: 'Leave the Philippines',
      offsetDays: -1,
      durationDays: 1,
      dependsOn: ['departure-documents', 'travel-tax', 'cfo', 'dswd-clearance'],
      documents: ['Passport', 'US visa', 'Boarding pass', 'Travel tax receipt'],
      prepare: ['Arrive at the airport early for immigration lines', 'Check any eTravel or e-Gate registration the BI currently asks departing travellers for'],
      howTo:
        '1. Check in, then go through BI departure; answer questions about the trip plainly.\n2. If referred to secondary inspection, show the papers from the previous step.\n3. The date here is the day before arrival; move it to the real flight.',
    },
    {
      id: 'arrival',
      title: 'Arrival: meet US Customs and Border Protection',
      offsetDays: 0,
      durationDays: 1,
      dependsOn: ['departure'],
      documents: ['Passport', 'US visa', 'Return ticket'],
      prepare: ['US address for the stay', 'Return ticket and proof of funds in carry-on'],
      howTo:
        '1. A visa lets you ask to enter; the Customs and Border Protection (CBP) officer decides admission and the length of stay.\n2. B2 visitors are often admitted for up to 6 months; the date is on the electronic I-94 record.\n3. Look up the I-94 on the CBP site after arrival and note the admit-until date; the rest of this plan uses it.\n4. Declare food, cash over USD 10,000 and other items as the customs form asks.',
    },
    {
      id: 'extend',
      title: 'File I-539 to extend the stay',
      offsetDays: 150,
      durationDays: 30,
      conditions: ['Only if you need to stay past the I-94 date'],
      dependsOn: ['arrival'],
      documents: ['I-539', 'I-94 record', 'Passport'],
      prepare: ['Reason for staying longer', 'Proof of funds for the extra time', 'Return ticket', 'Check the current USCIS fee'],
      howTo:
        '1. File Form I-539 with USCIS before the I-94 date passes; USCIS suggests filing well ahead, at least 45 days before if possible.\n2. Changing from B1/B2 to another status, such as student, is filed on the same form but has its own limits; check USCIS.\n3. Staying past the I-94 date without a pending timely application can void the visa and lead to bars on returning.\n4. The date here assumes a 6-month admission; move it to 45 days before the real I-94 date.',
    },
    {
      id: 'etravel',
      title: 'Register on eTravel before flying home',
      offsetDays: 27,
      durationDays: 3,
      dependsOn: ['arrival'],
      documents: ['eTravel QR code'],
      prepare: ['Passport', 'Flight number', 'Address in the Philippines'],
      howTo:
        '1. eTravel is the Philippine government\'s free online travel declaration; arriving travellers, Filipinos included, register before landing, usually within 72 hours of the flight; check the current window.\n2. Use etravel.gov.ph or the eGovPH app only; look-alike sites charge fees.\n3. Show the QR code on arrival in the Philippines.',
    },
    {
      id: 'return',
      title: 'Leave the US on time and keep the records',
      offsetDays: 30,
      durationDays: 1,
      dependsOn: ['etravel'],
      documents: ['Passport', 'Boarding pass', 'I-94 record'],
      prepare: ['Copies of the visa, I-94 and boarding passes'],
      howTo:
        '1. Leave by the I-94 date; the airline reports the departure to CBP.\n2. Keep boarding passes and the I-94 printout; later visa applications ask about US travel history.\n3. A multiple-entry visa can be used again while it is valid, but each entry has its own I-94 date.\n4. The 30 days here is an estimate; move it to the real return flight.',
    },
  ],
};
