import type { Playbook } from '../../domain/types';

const HOME = 'https://home-affairs.ec.europa.eu/policies/schengen';

export const visaSchengenPh: Playbook = {
  id: 'visa-schengen-ph',
  title: 'Visiting the Schengen area · Philippine passport',
  summary:
    'Paperwork plan for a Philippine passport holder visiting the Schengen area for tourism or family on a short-stay (C) visa, from choosing the consulate of the main destination and €30,000 insurance to VFS or TLS in Manila or abroad, leaving the Philippines, the EES border check, the 90/180 rule and coming home.',
  region: 'Schengen area',
  country: 'SCHENGEN',
  citizen: 'PH',
  family: 'visa-schengen',
  anchorKind: 'trip',
  ages: { from: 0 },
  conditions: [
    'You hold a Philippine passport',
    'You are visiting one or more Schengen countries for tourism or to see family or friends, up to 90 days in any 180',
    'Not for work, study or moving to Europe; those use national long-stay visas',
    'The date is the day you arrive in the Schengen area',
    "This is a planning aid, not immigration advice; the EU and the main destination's consulate pages are the reference",
  ],
  reviewedAt: '2026-09-27',
  version: 1,
  sources: [
    { title: 'Applying for a Schengen visa — European Commission, Migration and Home Affairs', url: `${HOME}/visa-policy/applying-schengen-visa_en` },
    { title: 'Short-stay calculator — European Commission', url: `${HOME}/border-crossing/short-stay-calculator_en` },
    { title: 'Visa Code, Regulation (EC) No 810/2009, consolidated — EUR-Lex', url: 'https://eur-lex.europa.eu/legal-content/AUTO/?uri=CELEX%3A02009R0810-20200202' },
    { title: 'Entry/Exit System (EES) and ETIAS — Travel to Europe, European Union', url: 'https://travel-europe.europa.eu/ees_en' },
    { title: 'Philippine passport appointments — Department of Foreign Affairs', url: 'https://consular.dfa.gov.ph/' },
    { title: 'Travel tax — TIEZA', url: 'https://tieza.gov.ph/travel-tax/' },
    { title: 'Reduced travel tax — TIEZA', url: 'https://tieza.gov.ph/reduced-travel-tax/' },
    { title: 'Bureau of Immigration — Philippines', url: 'https://immigration.gov.ph/' },
    { title: 'Commission on Filipinos Overseas', url: 'https://cfo.gov.ph/' },
    { title: 'Travel clearance for minors — DSWD', url: 'https://www.dswd.gov.ph/' },
    { title: 'eTravel — Philippine travel information system', url: 'https://etravel.gov.ph/' },
  ],
  steps: [
    {
      id: 'entry-check',
      title: 'Check the visa and the Schengen rules',
      offsetDays: -180,
      durationDays: 7,
      dependsOn: [],
      documents: ['Passport'],
      prepare: ['Countries you will visit and nights in each', 'Past Schengen visas and how you used them'],
      howTo:
        "1. Philippine citizens are on the EU list of nationalities that need a short-stay (type C) Schengen visa.\n2. It covers up to 90 days in any 180-day period across all Schengen countries, for tourism, visiting family or friends, or business; it can be single or multiple entry.\n3. ETIAS is for visa-exempt nationalities, so it does not apply to a Philippine passport; it is not running yet anyway.\n4. Ireland and Cyprus are EU members outside Schengen and issue their own visas.\n5. Not immigration advice; the EU site and the consulate of your main destination are the reference.",
    },
    {
      id: 'passport',
      title: 'Renew the Philippine passport if it runs short',
      offsetDays: -180,
      durationDays: 30,
      conditions: ['Only if your passport would expire less than 3 months after you leave the Schengen area, is over 10 years old, or has too few blank pages'],
      dependsOn: [],
      documents: ['Passport', 'PSA birth certificate'],
      prepare: ['DFA online appointment', 'Old passport', 'A valid government ID'],
      howTo:
        '1. The EU asks for a passport valid at least 3 months after the planned departure from the Schengen area; the Visa Code also asks that it was issued within the last 10 years and has at least 2 blank pages.\n2. For a multiple-entry visa, the 3 months count from the last planned departure.\n3. Book a renewal on the DFA online appointment system.',
    },
    {
      id: 'main-destination',
      title: 'Work out which country\'s consulate handles the application',
      offsetDays: -150,
      durationDays: 7,
      dependsOn: ['entry-check'],
      documents: [],
      prepare: ['Itinerary with nights per country', 'Where you legally live now'],
      howTo:
        "1. One country: apply to its consulate.\n2. Several countries: apply to the one where you spend the longest time; if the stays are equal, to the country you enter first.\n3. As a rule, you apply at that country's consulate responsible for the country where you legally live.\n4. Each consulate has its own checklist and appointment channel; read it before gathering papers.",
    },
    {
      id: 'documents',
      title: 'Gather proof of purpose, funds and ties',
      offsetDays: -120,
      durationDays: 21,
      dependsOn: ['main-destination'],
      documents: ['Visa application form', 'Passport photo', 'Bank statements', 'Certificate of employment', 'Flight reservation'],
      prepare: [
        'Harmonised application form, signed',
        'ICAO-standard photo',
        'Recent bank statements and income tax return (BIR Form 2316 or 1701)',
        'Certificate of employment with approved leave, or business registration (DTI or SEC) if self-employed',
        'Round-trip flight reservation and hotel bookings or host address',
        'Day-by-day itinerary',
        'PSA birth and marriage certificates if the consulate asks',
      ],
      howTo:
        '1. The EU lists the passport, application form, ICAO photo, travel medical insurance and papers showing the purpose, funds, accommodation and your intention to return home.\n2. Consulates may ask for more; the local checklist decides.\n3. Many consulates prefer flight reservations rather than paid tickets until the visa is issued; check yours.',
    },
    {
      id: 'insurance',
      title: 'Buy travel medical insurance with €30,000 cover',
      offsetDays: -100,
      durationDays: 7,
      dependsOn: ['main-destination'],
      documents: ['Travel insurance'],
      prepare: ['Exact travel dates', 'Check cover for emergency care, hospital and repatriation'],
      howTo:
        "1. The Visa Code asks for travel medical insurance with at least €30,000 cover, valid in all Schengen countries for the whole stay, including emergency care, hospitalisation and repatriation (including after death).\n2. For a multiple-entry visa, the first trip's cover is usually enough at application, with a signature that later trips will be covered too; check the consulate's rule.\n3. Pick a policy that refunds or can be moved if the visa is refused or dates change.",
    },
    {
      id: 'host-invitation',
      title: 'Get an invitation and your host\'s papers',
      offsetDays: -120,
      durationDays: 21,
      conditions: ['Only if visiting family or friends'],
      dependsOn: ['main-destination'],
      documents: ['Invitation letter', "Copy of host's passport or residence permit"],
      prepare: [
        "Host's name, address, phone and status in that country",
        'Relationship proof, e.g. PSA birth or marriage certificates',
        "If the host pays or houses you: their proof of funds and of the home",
        'Any official host form the country uses (check current)',
      ],
      howTo:
        "1. The host writes an invitation with your details, the dates, where you will stay, your relationship and who pays, and adds a copy of their ID or residence permit.\n2. Some countries have an official form done at a local office, for example France's attestation d'accueil or Germany's Verpflichtungserklärung, which can stand in for your own proof of funds.\n3. Start early; those forms take an appointment with the host's town hall or foreigners' office.",
    },
    {
      id: 'child-documents',
      title: "Prepare a child's application",
      offsetDays: -120,
      durationDays: 21,
      conditions: ['Only if a child under 18 is travelling'],
      dependsOn: ['main-destination'],
      documents: ['PSA birth certificate', 'Consent letter', 'Passport'],
      prepare: [
        "Both parents' signatures on the form, or a guardianship document",
        'Notarised consent from a parent who is not travelling',
        "Copies of both parents' passports or IDs",
      ],
      howTo:
        "1. Each child needs their own application.\n2. The EU fee is €45 for children aged 6 to 12; the Visa Code waives it for children under 6.\n3. Consulates usually ask for both parents' consent and the PSA birth certificate; check the checklist.\n4. The Philippine departure side for minors is in the DSWD step below.",
    },
    {
      id: 'apply-ph',
      title: 'Book and lodge the application in the Philippines',
      offsetDays: -75,
      durationDays: 7,
      conditions: ['Only if you are applying from the Philippines'],
      dependsOn: ['passport', 'documents', 'insurance', 'host-invitation', 'child-documents'],
      documents: ['Passport', 'Visa application form', 'Appointment confirmation', 'Travel insurance'],
      prepare: [
        'Visa fee: €90 for adults when this plan was reviewed, plus the service provider fee',
        'Appointment with the provider the consulate uses (for example VFS Global or TLScontact)',
        'Originals and copies as the checklist says',
      ],
      howTo:
        "1. Apply no earlier than 6 months and no later than 15 days before the trip; with Manila appointment waits, earlier is safer.\n2. Most Schengen embassies in Manila take applications through an external provider such as VFS Global or TLScontact; the embassy site names which one and where (some also have centres outside Metro Manila).\n3. Fingerprints are taken in person; if you gave them for a Schengen visa in the last 59 months, they may be reused.\n4. You may be asked to an interview at the embassy.",
    },
    {
      id: 'apply-abroad',
      title: 'Apply from the country where you live',
      offsetDays: -75,
      durationDays: 7,
      conditions: ['Only if you live legally outside the Philippines, e.g. working in Canada, Singapore or the Gulf'],
      dependsOn: ['passport', 'documents', 'insurance', 'host-invitation', 'child-documents'],
      documents: ['Passport', 'Residence permit', 'Visa application form', 'Travel insurance'],
      prepare: ['Residence permit valid well beyond the trip (check the local rule)', 'Proof of work or study there'],
      howTo:
        "1. The EU rule is to apply at the main destination's consulate responsible for the country where you legally live.\n2. Bring proof of that residence; the consulate weighs your ties there as well as to the Philippines.\n3. Applying while only visiting a third country is possible only if that consulate accepts a justified reason; check first.\n4. Fees are the same in euros, charged in local currency.",
    },
    {
      id: 'decision',
      title: 'Collect the passport and check the visa sticker',
      offsetDays: -50,
      durationDays: 21,
      dependsOn: ['apply-ph', 'apply-abroad'],
      documents: ['Schengen visa', 'Passport'],
      prepare: ['Check the dates, number of entries, duration of stay and territorial validity'],
      howTo:
        "1. The EU says a decision normally takes 15 days, up to 45 if more checks are needed.\n2. Check the sticker: valid from and until, entries (1, 2 or MULT), days allowed and 'Schengen States'.\n3. Frequent travellers with past visas used lawfully can get multiple-entry visas of longer validity under the Visa Code's cascade; check current.\n4. A refusal gives the reasons and the way to appeal.\n5. Book flights once the visa is issued.",
    },
    {
      id: 'dswd-clearance',
      title: 'Get a DSWD travel clearance for a child',
      offsetDays: -10,
      durationDays: 14,
      conditions: ['Only if a Filipino child under 18 is leaving without a parent, or with someone other than a parent'],
      dependsOn: ['decision'],
      documents: ['DSWD travel clearance', 'PSA birth certificate'],
      prepare: ["Parents' written consent", 'Details of the adult travelling with the child', 'Photos of the child'],
      howTo:
        '1. The Department of Social Welfare and Development (DSWD) issues travel clearances for Filipino minors travelling abroad alone or with an adult who is not a parent.\n2. A child travelling with a parent generally does not need one; check current exemptions on the DSWD site.\n3. Apply online or at a DSWD field office; check current processing time and validity, and apply earlier if you can.',
    },
    {
      id: 'cfo',
      title: 'Check whether a CFO certificate applies',
      offsetDays: -7,
      durationDays: 21,
      conditions: ['Only if you are going to join a foreign spouse, partner or fiancé(e), or emigrating, rather than just visiting'],
      dependsOn: ['decision'],
      documents: ['CFO certificate'],
      prepare: ['Marriage certificate or proof of relationship', "Partner's passport copy", 'Visa'],
      howTo:
        '1. The Commission on Filipinos Overseas (CFO) runs guidance and counselling for Filipinos leaving to join a foreign spouse, partner or fiancé(e), and registration for emigrants; the Bureau of Immigration checks the CFO certificate at departure.\n2. A short Schengen visit is generally not an emigrant departure, but visiting a European partner can prompt questions at the counter; check with the CFO which case yours is.\n3. Moving to Europe on a family or long-stay visa is outside this plan.',
    },
    {
      id: 'travel-tax',
      title: 'Pay the Philippine travel tax or check the exemption',
      offsetDays: -14,
      durationDays: 7,
      dependsOn: ['decision'],
      documents: ['Travel tax receipt'],
      prepare: ['Ticket and booking reference', 'Proof of exemption or reduced rate, if any'],
      howTo:
        '1. Filipinos and some residents leaving the Philippines pay travel tax to TIEZA: PHP 1,620 economy or PHP 2,700 first class at the full rate when this plan was reviewed.\n2. Many airline tickets bought in the Philippines include it; check the fare breakdown.\n3. Children over 2 and under 12 pay the reduced rate, infants up to 2 are exempt, and overseas Filipino workers and some permanent residents abroad are exempt; check TIEZA.\n4. If not included, pay online on the TIEZA site or at the airport counter before check-in.',
    },
    {
      id: 'departure-documents',
      title: 'Pack papers for the Bureau of Immigration departure check',
      offsetDays: -7,
      durationDays: 5,
      dependsOn: ['decision'],
      documents: ['Passport', 'Schengen visa', 'Return ticket', 'Certificate of employment', 'Travel insurance'],
      prepare: [
        'Return ticket',
        'Hotel bookings or host address',
        'Proof of work, approved leave, business or school',
        'Proof of funds',
        'Invitation letter and relationship proof if visiting family or friends',
      ],
      howTo:
        '1. At departure, a Bureau of Immigration (BI) officer checks the passport, visa, boarding pass and return ticket, following inter-agency (IACAT) departure guidelines meant to stop trafficking and illegal recruitment.\n2. Some travellers are sent to secondary inspection and asked for supporting papers; being refused departure is called offloading.\n3. Keep the papers in the carry-on, not the checked bag.\n4. Check the current IACAT guidelines on the BI site before the trip.',
    },
    {
      id: 'departure',
      title: 'Leave the Philippines',
      offsetDays: -1,
      durationDays: 1,
      dependsOn: ['departure-documents', 'travel-tax', 'cfo', 'dswd-clearance'],
      documents: ['Passport', 'Schengen visa', 'Boarding pass', 'Travel tax receipt'],
      prepare: ['Arrive at the airport early for immigration lines', 'Check any eTravel or e-Gate registration the BI currently asks departing travellers for'],
      howTo:
        '1. Check in, then go through BI departure; answer questions about the trip plainly.\n2. If referred to secondary inspection, show the papers from the previous step.\n3. The date here is the day before arrival; move it to the real flight.',
    },
    {
      id: 'arrival',
      title: 'Arrival: border check and EES registration',
      offsetDays: 0,
      durationDays: 1,
      dependsOn: ['departure'],
      documents: ['Passport', 'Schengen visa', 'Return ticket', 'Travel insurance'],
      prepare: ['Hotel bookings or host address', 'Proof of funds and invitation letter in the carry-on'],
      howTo:
        '1. The Entry/Exit System (EES) records non-EU short-stay travellers at the external border with fingerprints and a face photo, in place of passport stamps (started October 2025; check current).\n2. The border guard may ask about the purpose, funds, accommodation and return; a visa does not assure entry.\n3. Entering first through the main destination is usual but the visa is valid across Schengen; keep the itinerary close to what you declared.\n4. Use the EU short-stay calculator to track days against the 90/180 limit.',
    },
    {
      id: 'extend',
      title: 'Ask the local authorities about an extension',
      offsetDays: 20,
      durationDays: 7,
      conditions: ['Only if something like illness, a flight cancellation or a serious family reason keeps you past your visa'],
      dependsOn: ['arrival'],
      documents: ['Passport', 'Schengen visa'],
      prepare: ["Proof of the reason, e.g. a doctor's letter", 'Proof of funds and insurance for the extra days'],
      howTo:
        "1. Schengen visas are generally not extended; the Visa Code allows it only for force majeure, humanitarian or serious personal reasons.\n2. Apply to the immigration authorities of the country where you are, before the visa ends.\n3. Switching to a long-stay visa from inside is generally not possible; those are applied for from home.\n4. The date here is an estimate; move it to before the last day allowed.",
    },
    {
      id: 'etravel',
      title: 'Register on eTravel before flying home',
      offsetDays: 27,
      durationDays: 3,
      dependsOn: ['arrival'],
      documents: ['eTravel QR code'],
      prepare: ['Passport', 'Flight number', 'Address in the Philippines'],
      howTo:
        "1. eTravel is the Philippine government's free online travel declaration; arriving travellers, Filipinos included, register before landing, usually within 72 hours of the flight; check the current window.\n2. Use etravel.gov.ph or the eGovPH app only; look-alike sites charge fees.\n3. Show the QR code on arrival in the Philippines.",
    },
    {
      id: 'return',
      title: 'Leave the Schengen area on time and keep the records',
      offsetDays: 30,
      durationDays: 1,
      dependsOn: ['etravel'],
      documents: ['Passport', 'Boarding pass'],
      prepare: ['Days used in the last 180', 'Copies of the visa and boarding passes'],
      howTo:
        '1. Leave by the visa end date and within 90 days in any 180; EES records the exit, and overstays show up on later applications.\n2. Keep the visa and boarding passes; lawful use of past visas helps later multiple-entry applications.\n3. The 30 days here is an estimate; move it to the real return flight.',
    },
  ],
};
