import type { Playbook } from '../../domain/types';

const IRCC = 'https://www.canada.ca/en/immigration-refugees-citizenship/services';

export const visaCaPh: Playbook = {
  id: 'visa-ca-ph',
  title: 'Visiting Canada · Philippine passport',
  summary:
    'Paperwork plan for a Philippine passport holder visiting Canada for tourism or family: eTA or visitor visa, biometrics in Manila, Cebu or abroad, the super visa for parents, leaving the Philippines, arrival, visitor record and coming home.',
  region: 'Canada',
  country: 'CA',
  citizen: 'PH',
  family: 'visa-ca',
  anchorKind: 'trip',
  ages: { from: 0 },
  conditions: [
    'You hold a Philippine passport and are not a Canadian citizen or permanent resident',
    'You are visiting for tourism or to see family or friends, not to work, study or immigrate',
    'The date is the day you arrive in Canada',
    'This is a planning aid, not immigration advice; the IRCC and Philippine agency pages are the reference',
  ],
  reviewedAt: '2026-09-27',
  version: 1,
  sources: [
    { title: 'Find out if you need a visa or eTA — Canada.ca', url: `${IRCC}/visit-canada/check-visa-eta.html` },
    { title: 'eTA for certain visa-required travellers — Canada.ca', url: `${IRCC}/visit-canada/eta/eligibility/eta-x.html` },
    { title: 'Apply for a visitor visa — Canada.ca', url: `${IRCC}/visit-canada/apply-visitor-visa.html` },
    { title: 'Letter of invitation — Canada.ca', url: `${IRCC}/visit-canada/letter-invitation.html` },
    { title: 'Parent and grandparent super visa — Canada.ca', url: `${IRCC}/visit-canada/parent-grandparent-super-visa/about.html` },
    { title: 'Biometrics: Where to give them — Canada.ca', url: `${IRCC}/biometrics/where-to-give.html` },
    { title: 'Fee list — IRCC', url: 'https://ircc.canada.ca/english/information/fees/fees.asp' },
    { title: 'Check processing times — Canada.ca', url: `${IRCC}/application/check-processing-times.html` },
    { title: 'Minor children travelling to Canada — Canada.ca', url: `${IRCC}/visit-canada/minor-children-travelling-canada.html` },
    { title: 'Extend your stay in Canada as a visitor — Canada.ca', url: `${IRCC}/visit-canada/extend-stay.html` },
    { title: 'Canada visa application centres in the Philippines — VFS Global', url: 'https://visa.vfsglobal.com/phl/en/can' },
    { title: 'Philippine passport appointments — Department of Foreign Affairs', url: 'https://consular.dfa.gov.ph/' },
    { title: 'Travel tax — TIEZA', url: 'https://tieza.gov.ph/travel-tax/' },
    { title: 'Bureau of Immigration — Philippines', url: 'https://immigration.gov.ph/' },
    { title: 'Commission on Filipinos Overseas', url: 'https://cfo.gov.ph/' },
    { title: 'Travel clearance for minors — DSWD', url: 'https://www.dswd.gov.ph/' },
    { title: 'eTravel — Philippine travel information system', url: 'https://etravel.gov.ph/' },
  ],
  steps: [
    {
      id: 'entry-document',
      title: 'Check whether you can use an eTA or need a visitor visa',
      offsetDays: -200,
      durationDays: 7,
      dependsOn: [],
      documents: ['Passport'],
      prepare: [
        'Whether you held a Canadian visitor visa in the past 10 years',
        'Whether you hold a US non-immigrant visa that is valid today',
        'Whether you are flying in, or coming by land or sea',
      ],
      howTo:
        "1. The Philippines is a visa-required country for Canada, but it is on IRCC's list of countries whose citizens can get an electronic travel authorization (eTA) instead, when all conditions are met.\n2. The eTA route: you held a Canadian visitor visa (temporary resident visa, TRV) in the past 10 years, or you hold a valid US non-immigrant visa when you apply, and you fly to or through a Canadian airport.\n3. Arriving by car, bus, train or boat, including a cruise, needs a visitor visa even if you qualify for the eTA.\n4. Everyone else on a Philippine passport applies for a visitor visa; it can be valid for up to 10 years, or until the passport or biometrics expire.\n5. A parent or grandparent of a Canadian citizen or permanent resident wanting to stay longer than 6 months at a time can look at the super visa next.",
    },
    {
      id: 'passport',
      title: 'Renew the Philippine passport if it runs short',
      offsetDays: -180,
      durationDays: 30,
      conditions: ['Only if your passport expires within 6 months of the travel date'],
      dependsOn: [],
      documents: ['Passport', 'PSA birth certificate'],
      prepare: ['DFA online appointment', 'Old passport', 'A valid government ID'],
      howTo:
        '1. IRCC asks for a passport valid for at least 6 months from the date you plan to travel, and a visa is not issued past the passport expiry.\n2. Book a renewal on the DFA online appointment system.\n3. An eTA is linked to the passport number, so a new passport needs a new eTA.',
    },
    {
      id: 'eta',
      title: 'Apply for the eTA online',
      offsetDays: -60,
      durationDays: 7,
      validForDays: 1826,
      conditions: [
        'Only if you are flying and held a Canadian visitor visa in the past 10 years or hold a valid US non-immigrant visa',
      ],
      dependsOn: ['entry-document', 'passport'],
      documents: ['eTA approval email', 'Passport'],
      prepare: ['Passport', 'US visa or old Canadian visa details', 'A credit or debit card', 'Check the current fee (CAD 7 when this plan was reviewed)'],
      howTo:
        '1. Apply only on the official Government of Canada eTA page; other sites charge extra.\n2. Most approvals come by email within minutes, but some take several days and ask for documents.\n3. The eTA is valid for up to 5 years or until the passport expires, whichever comes first.\n4. Skip the visitor visa steps below, apart from the invitation letter if visiting family.',
    },
    {
      id: 'super-visa',
      title: 'Decide on a super visa',
      offsetDays: -180,
      durationDays: 14,
      conditions: ['Only if you are a parent or grandparent of a Canadian citizen or permanent resident and want to stay longer than 6 months at a time'],
      dependsOn: ['entry-document'],
      documents: ['Letter of invitation', 'Proof of private medical insurance'],
      prepare: [
        "Your child or grandchild's proof of income for their family size",
        'A 1-year Canadian or approved medical insurance policy',
        'An immigration medical exam with a panel physician in the Philippines',
      ],
      howTo:
        '1. The super visa lets a parent or grandparent stay up to 5 years at a time, with multiple entries for up to 10 years.\n2. The host in Canada meets a minimum income, signs a promise of financial support, and sends an invitation letter.\n3. You buy private medical insurance valid for at least 1 year with at least CAD 100,000 of emergency coverage, and take an immigration medical exam.\n4. The host side is covered in detail in the "Visitors to Canada" plan; for 6 months or less, the regular visitor visa is the usual route.',
    },
    {
      id: 'documents',
      title: 'Gather proof of ties and funds',
      offsetDays: -150,
      durationDays: 21,
      conditions: ['Only if you need a visitor visa or super visa'],
      dependsOn: ['entry-document'],
      documents: ['Certificate of employment', 'Bank statements', 'Income tax return'],
      prepare: [
        'Certificate of employment with position, salary and approved leave dates',
        'Bank statements with at least 6 months of history',
        'Income tax return (BIR Form 2316 or 1701)',
        'Business registration (DTI or SEC) if self-employed',
        'Property titles or other ties to the Philippines',
        'Previous passports and visas used in the last 10 years',
        'Travel itinerary',
      ],
      howTo:
        '1. The officer weighs whether you will leave Canada at the end of the visit: work, family, property and funds.\n2. Scan everything clearly; IRCC takes these as uploads, not paper.\n3. Translate documents that are not in English or French and include the translator\'s declaration.',
    },
    {
      id: 'invitation',
      title: 'Get an invitation letter and your host\'s status proof',
      offsetDays: -150,
      durationDays: 14,
      conditions: ['Only if visiting family or friends'],
      dependsOn: ['entry-document'],
      documents: ['Letter of invitation', "Copy of host's Canadian passport, PR card or permit"],
      prepare: [
        'Host name, date of birth, address, phone, job and status in Canada',
        'Your relationship, with PSA birth or marriage certificates if family',
        'Purpose, dates, where you will stay and who pays',
        "Host's proof of income if they are supporting the trip",
      ],
      howTo:
        '1. IRCC says an invitation letter may help but does not decide the application.\n2. The host writes and signs it, covering your details, theirs, the purpose and length of the trip, where you will stay and how it is paid for.\n3. For a super visa, the letter adds a signed promise of financial support and the host\'s family size.\n4. The host sends a signed scan for you to upload.',
    },
    {
      id: 'child-documents',
      title: 'Prepare a child\'s travel papers',
      offsetDays: -150,
      durationDays: 21,
      conditions: ['Only if a child under 18 is travelling'],
      dependsOn: ['entry-document'],
      documents: ['PSA birth certificate', 'Consent letter'],
      prepare: [
        'A consent letter signed by any parent not travelling, with their contact details and ID copy',
        'Custody or guardianship papers if they apply',
        "The accompanying adult's passport copy",
      ],
      howTo:
        '1. Each child has their own passport and their own eTA or visa application.\n2. IRCC says a child under 18 may need a letter authorizing the travel, plus custody or adoption papers where they apply, when travelling alone or with only one parent or another adult; officers can ask for it.\n3. The PSA birth certificate shows who the parents are.\n4. Children under 14 do not give biometrics.',
    },
    {
      id: 'medical',
      title: 'Take the immigration medical exam',
      offsetDays: -140,
      durationDays: 21,
      validForDays: 365,
      conditions: ['Only if you are applying for a super visa, or staying over 6 months in some cases'],
      dependsOn: ['super-visa'],
      documents: ['Medical exam confirmation'],
      prepare: ['An IRCC panel physician in the Philippines, from the IRCC list', 'Passport and medical records'],
      howTo:
        '1. Super visa applicants take an upfront immigration medical exam with an IRCC panel physician; the clinic sends results to IRCC.\n2. Results are valid for 12 months, so book close to the application.',
    },
    {
      id: 'apply',
      title: 'Submit the visitor visa application online',
      offsetDays: -120,
      durationDays: 7,
      conditions: ['Only if you need a visitor visa or super visa'],
      dependsOn: ['passport', 'documents', 'invitation', 'child-documents', 'medical'],
      documents: ['Passport', 'Photo', 'Bank statements', 'Letter of invitation'],
      prepare: [
        'An IRCC secure account',
        'Digital photo meeting the IRCC specifications',
        'Check the current fees (CAD 100 visa plus CAD 85 biometrics per person when this plan was reviewed)',
      ],
      howTo:
        '1. Apply online through the IRCC account; paper applications are only for people who cannot apply online, such as for a disability.\n2. The questionnaire builds a personalised document checklist.\n3. Pay the visa and biometrics fees together to avoid delays; a family applying together pays capped amounts.\n4. You can apply online from wherever you are; the country you apply from sets which visa office and processing time apply.',
    },
    {
      id: 'biometrics-ph',
      title: 'Give biometrics at VFS in Manila or Cebu',
      offsetDays: -85,
      durationDays: 30,
      validForDays: 3652,
      conditions: ['Only if you need a visitor visa or super visa, are aged 14 to 79, apply from the Philippines, and have no biometrics on file from the last 10 years'],
      dependsOn: ['apply'],
      documents: ['Biometric instruction letter', 'Passport'],
      prepare: ['Book a VFS appointment as soon as the biometric instruction letter arrives'],
      howTo:
        '1. After the fee is paid, IRCC sends a biometric instruction letter; you have 30 days to give fingerprints and a photo.\n2. The Philippines has Canada visa application centres in Manila and Cebu, run by VFS Global.\n3. Bring the letter and passport; VFS can also handle passport submission later for a fee.\n4. Biometrics count for 10 years for visitor applications.',
    },
    {
      id: 'biometrics-abroad',
      title: 'Give biometrics in the country where you are',
      offsetDays: -85,
      durationDays: 30,
      validForDays: 3652,
      conditions: ['Only if you need a visitor visa or super visa, are aged 14 to 79, and are living or staying outside the Philippines'],
      dependsOn: ['apply'],
      documents: ['Biometric instruction letter', 'Passport', 'Residence permit'],
      prepare: [
        'The nearest visa application centre that offers biometrics',
        'Proof of legal status in that country, such as a residence or work permit',
      ],
      howTo:
        '1. Biometrics can be given at any visa application centre worldwide that offers the service; check the centre on the IRCC list before booking.\n2. In the US, Application Support Centers take IRCC biometrics, but only for people already legally in the US.\n3. Applying from a country where you live legally is common; IRCC may look at your status and ties there as well as in the Philippines.\n4. The processing time is the one for the country you apply from; check it on the IRCC page.',
    },
    {
      id: 'decision',
      title: 'Wait for the decision and send the passport for the visa',
      offsetDays: -30,
      durationDays: 50,
      conditions: ['Only if you applied for a visitor visa or super visa'],
      dependsOn: ['biometrics-ph', 'biometrics-abroad'],
      documents: ['Visitor visa', 'Passport'],
      prepare: ['Check the IRCC processing time for the Philippines or your country of residence', 'Watch the IRCC account for requests'],
      howTo:
        '1. Processing times change often; the 50 days here is only an estimate, so move this date to the posted time.\n2. If approved, IRCC asks for the passport; submit it through VFS in Manila or Cebu, or the centre where you are.\n3. Check the visa counterfoil: name, dates, number of entries.\n4. Book flights once the visa is in the passport.',
    },
    {
      id: 'dswd-clearance',
      title: 'Get a DSWD travel clearance for a child',
      offsetDays: -10,
      durationDays: 14,
      conditions: ['Only if a Filipino child under 18 is leaving without a parent, or with someone other than a parent'],
      dependsOn: ['decision', 'eta'],
      documents: ['DSWD travel clearance', 'PSA birth certificate'],
      prepare: ["Parents' written consent", 'Details of the adult travelling with the child', 'Photos of the child'],
      howTo:
        '1. The Department of Social Welfare and Development (DSWD) issues travel clearances for Filipino minors travelling abroad alone or with an adult who is not a parent.\n2. A child travelling with a parent generally does not need one; check current exemptions on the DSWD site.\n3. Apply online or at a DSWD field office; check current processing time and validity, and apply earlier if you can.',
    },
    {
      id: 'cfo',
      title: 'Check whether a CFO certificate applies',
      offsetDays: -5,
      durationDays: 21,
      conditions: [
        'Only if you are going to join a foreign spouse, partner or fiancé(e), or emigrating, rather than just visiting',
      ],
      dependsOn: ['decision', 'eta'],
      documents: ['CFO certificate'],
      prepare: ['Marriage certificate or proof of relationship', "Partner's passport copy", 'Visa or eTA'],
      howTo:
        '1. The Commission on Filipinos Overseas (CFO) runs guidance and counselling for Filipinos leaving to join a foreign spouse, partner or fiancé(e), and registration for emigrants; the Bureau of Immigration checks the CFO certificate at departure.\n2. A short visit on a visitor visa or eTA is generally not an emigrant departure, but visiting a foreign partner can prompt questions at the counter; check with the CFO which case yours is before flying.\n3. Moving to Canada as a permanent resident is outside this plan.',
    },
    {
      id: 'travel-tax',
      title: 'Pay the Philippine travel tax or check the exemption',
      offsetDays: -14,
      durationDays: 7,
      dependsOn: ['decision', 'eta'],
      documents: ['Travel tax receipt'],
      prepare: ['Ticket and booking reference', 'Proof of exemption or reduced rate, if any'],
      howTo:
        '1. Filipinos and some residents leaving the Philippines pay travel tax to TIEZA: PHP 1,620 economy or PHP 2,700 first class at the full rate when this plan was reviewed.\n2. Many airline tickets bought in the Philippines include it; check the fare breakdown.\n3. Reduced rates and exemptions exist, for example for some minors and overseas Filipino workers; check TIEZA.\n4. If not included, pay online on the TIEZA site or at the airport counter before check-in.',
    },
    {
      id: 'departure-documents',
      title: 'Pack papers for the Bureau of Immigration departure check',
      offsetDays: -7,
      durationDays: 5,
      dependsOn: ['decision', 'eta'],
      documents: ['Passport', 'Visitor visa', 'Return ticket', 'Certificate of employment'],
      prepare: [
        'eTA approval email, if travelling on an eTA',
        'Return or onward ticket',
        'Hotel booking or host address',
        'Proof of work, approved leave, business or school',
        'Proof of funds',
        'Invitation letter and relationship proof if visiting family or friends',
        'Affidavit of support from the sponsor if someone else pays',
      ],
      howTo:
        '1. At departure, a Bureau of Immigration (BI) officer checks the passport, visa or eTA, boarding pass and return ticket, following inter-agency (IACAT) departure guidelines meant to stop trafficking and illegal recruitment.\n2. Some travellers are sent to secondary inspection and asked for supporting papers; being refused departure is called offloading.\n3. Keep the papers in the carry-on, not the checked bag.\n4. Check the current IACAT guidelines on the BI site before the trip.',
    },
    {
      id: 'departure',
      title: 'Leave the Philippines',
      offsetDays: -1,
      durationDays: 1,
      dependsOn: ['departure-documents', 'travel-tax', 'cfo', 'dswd-clearance'],
      documents: ['Passport', 'Boarding pass', 'Travel tax receipt'],
      prepare: ['Arrive at the airport early for immigration lines', 'Check any eTravel or e-Gate registration the BI currently asks departing travellers for'],
      howTo:
        '1. Check in, then go through BI departure; answer questions about the trip plainly.\n2. If referred to secondary inspection, show the papers from the previous step.\n3. The date here is the day before arrival; move it to the real flight.',
    },
    {
      id: 'arrival',
      title: 'Arrival: meet the border officer',
      offsetDays: 0,
      durationDays: 1,
      dependsOn: ['departure'],
      documents: ['Passport', 'Visitor visa', 'Letter of invitation', 'Return ticket'],
      prepare: ['Host address and phone', 'Proof of funds in carry-on', 'For a super visa, the insurance policy'],
      howTo:
        '1. A Canada Border Services Agency (CBSA) officer decides entry and the length of stay.\n2. Most visitors can stay up to 6 months; the officer may stamp the passport or issue a visitor record with a leave-by date.\n3. With no stamp, the stay ends 6 months after arrival, or when the passport expires if sooner.\n4. A super visa holder can stay up to 5 years at a time; ask for a passport stamp as proof of entry.',
    },
    {
      id: 'extend',
      title: 'Apply for a visitor record to extend the stay',
      offsetDays: 150,
      durationDays: 14,
      conditions: ['Only if you want to stay past the date the officer gave you'],
      dependsOn: ['arrival'],
      documents: ['Visitor record', 'Passport'],
      prepare: ['The leave-by date', 'Reason for staying longer', 'Proof of funds and insurance for the extra time', 'Check the current fee (CAD 100 when this plan was reviewed)'],
      howTo:
        '1. To stay longer as a visitor, apply online for a visitor record from inside Canada.\n2. IRCC asks for the application at least 30 days before the current status expires; you can stay while it is processed if applied for in time.\n3. A visitor record is not a visa; to re-enter Canada after leaving, a valid visa or eTA is still needed.\n4. The date here assumes a 6-month stay; move it to 30 days before the real leave-by date.',
    },
    {
      id: 'etravel',
      title: 'Register on eTravel before flying home',
      offsetDays: 27,
      durationDays: 3,
      dependsOn: ['arrival'],
      documents: ['eTravel QR code'],
      prepare: ['Passport', 'Flight number', 'Address in the Philippines'],
      howTo:
        '1. eTravel is the Philippine government\'s free online travel declaration; arriving travellers, Filipinos included, register before landing, usually within 72 hours of the flight; check the current window.\n2. Use etravel.gov.ph or the eGovPH app only; look-alike sites charge fees.\n3. Show the QR code on arrival in the Philippines.',
    },
    {
      id: 'return',
      title: 'Leave Canada on time and keep the records',
      offsetDays: 30,
      durationDays: 1,
      dependsOn: ['etravel'],
      documents: ['Passport', 'Boarding pass'],
      prepare: ['Copies of the visa, eTA, stamps and visitor record'],
      howTo:
        '1. Leave by the stamped or visitor record date, or 6 months after arrival if there is neither.\n2. Keep the visa, stamps and boarding passes; a Canadian visa held in the past 10 years is what makes a later eTA possible.\n3. The 30 days here is an estimate; move it to the real return flight.',
    },
  ],
};
