import type { Playbook } from '../../domain/types';

const TSG = 'https://travel.state.gov/content/travel/en';

export const visaUsCn: Playbook = {
  id: 'visa-us-cn',
  title: 'Visiting the United States · Chinese passport',
  summary:
    'Paperwork plan for a short US visit on a Chinese passport: the B1/B2 visitor visa, DS-160, interview in China or a third country, EVUS, arrival, extending the stay and leaving on time.',
  region: 'United States',
  country: 'US',
  citizen: 'CN',
  family: 'visa-us',
  anchorKind: 'trip',
  ages: { from: 0 },
  conditions: [
    'You travel on a passport of the People\'s Republic of China',
    'The visit is short: tourism, visiting family or friends, or business on the same B1/B2 visa',
    'Not for study, work or moving to the United States',
    'The date is the day you arrive in the United States',
  ],
  reviewedAt: '2026-09-27',
  version: 1,
  sources: [
    { title: 'Visitor visa — U.S. Department of State', url: `${TSG}/us-visas/tourism-visit/visitor.html` },
    { title: 'Online Nonimmigrant Visa Application (DS-160) — U.S. Department of State', url: `${TSG}/us-visas/forms/ds-160-online-nonimmigrant-visa-application.html` },
    { title: 'Photo requirements — U.S. Department of State', url: `${TSG}/us-visas/visa-information-resources/photos.html` },
    { title: 'Fees for visa services — U.S. Department of State', url: `${TSG}/us-visas/visa-information-resources/fees/fees-visa-services.html` },
    { title: 'Visa reciprocity: China — U.S. Department of State', url: `${TSG}/us-visas/Visa-Reciprocity-and-Civil-Documents-by-Country/China.html` },
    { title: 'Global visa wait times — U.S. Department of State', url: `${TSG}/us-visas/visa-information-resources/global-visa-wait-times.html` },
    { title: 'Nonimmigrant visas — U.S. Embassy and Consulates in China', url: 'https://china.usembassy-china.org.cn/visas/' },
    { title: 'Electronic Visa Update System (EVUS) — U.S. Customs and Border Protection', url: 'https://www.evus.gov/' },
    { title: 'I-94 arrival record — U.S. Customs and Border Protection', url: 'https://i94.cbp.dhs.gov/' },
    { title: 'Form I-539, Application to Extend/Change Nonimmigrant Status — USCIS', url: 'https://www.uscis.gov/i-539' },
    { title: 'Fee schedule (G-1055) — USCIS', url: 'https://www.uscis.gov/g-1055' },
  ],
  steps: [
    {
      id: 'entry-check',
      title: 'Check which visa the trip needs',
      offsetDays: -280,
      durationDays: 7,
      dependsOn: [],
      documents: ['Passport'],
      prepare: ['Purpose of the trip', 'How long you plan to stay', 'Any earlier US visas, refusals or overstays'],
      howTo:
        "1. China is not in the Visa Waiver Program, so ESTA is not an option on a Chinese passport; a short visit for tourism, family or business uses the B1/B2 visitor visa.\n2. The same applies when only changing planes in the US: transit uses a C visa or a valid B1/B2 visa; check current.\n3. The State Department reciprocity page for China lists B1/B2 visas for Chinese nationals as multiple entry for up to 10 years; the officer decides what is issued.\n4. A valid B1/B2 visa already in an old passport can still be used with the new passport; check that it has not expired.\n5. Birth tourism is not a permitted purpose on a visitor visa.",
    },
    {
      id: 'documents',
      title: 'Gather passport, photo and supporting papers',
      offsetDays: -255,
      durationDays: 14,
      dependsOn: ['entry-check'],
      documents: ['Passport', 'Visa photo', 'Bank statements', 'Employment or leave letter'],
      prepare: [
        'Passport valid at least 6 months beyond the planned stay',
        'A digital photo meeting the State Department photo rules',
        'Recent bank statements, property or deposit certificates',
        'Employment letter with approved leave, or school or retirement papers',
        'Rough itinerary and where you will stay',
        'Previous passports with US or other visas',
      ],
      howTo:
        '1. The State Department asks for a passport valid at least 6 months beyond the stay, unless a country agreement exempts it; renew first if it will be close.\n2. The photo is uploaded in the DS-160; it follows the State Department photo rules.\n3. The interview focuses on the purpose of the trip, the ability to pay, and ties that bring you back to China or the country where you live: job, family, property, study.\n4. Supporting papers are not always asked for, but having them ready at the interview helps; bring originals.',
    },
    {
      id: 'host-letter',
      title: 'Ask your host for an invitation letter and status proof',
      offsetDays: -255,
      durationDays: 14,
      conditions: ['Only if visiting family or friends in the United States'],
      dependsOn: ['entry-check'],
      documents: ['Letter of invitation', "Copy of host's US status document"],
      prepare: [
        "Host's full name, address, phone and relationship to you",
        "Copy of the host's US passport, green card, or visa and I-94",
        'Dates of the visit and where you will stay',
        "Host's proof of income, if the host is paying for the trip",
      ],
      howTo:
        "1. The State Department does not list an invitation letter as a requirement; officers decide mainly on the interview and the applicant's own ties.\n2. A short letter from the host with the relationship, dates and where you will stay, plus a copy of the host's status, still helps explain the trip.\n3. If the host is paying, add their recent pay slips, tax return or bank statement.\n4. For the host: keep the letter factual; the visitor answers the questions at the interview.",
    },
    {
      id: 'child-docs',
      title: "Prepare a child's birth certificate and parents' consent",
      offsetDays: -255,
      durationDays: 14,
      ages: { from: 0, to: 17 },
      conditions: ['Only if a child under 18 is travelling'],
      dependsOn: [],
      documents: ["Child's passport", 'Birth certificate (出生医学证明)', 'Parental consent letter'],
      prepare: [
        "Both parents' passports or ID cards and household register (户口簿)",
        'Signed consent from the parent not travelling, or from both if the child travels with someone else',
        "The travelling parents' visas, if the child is going with them",
      ],
      howTo:
        '1. Each traveller, including a baby, needs their own passport, DS-160 and visa.\n2. Bring the birth certificate to show the parents; with one parent absent, a signed consent letter with a copy of their ID answers the usual question.\n3. The June 2025 State Department page said an interview is generally not asked of applicants 13 and younger; check current, as waiver rules changed in 2025.\n4. A parent usually goes with the child to the appointment.',
    },
    {
      id: 'ds160',
      title: 'Fill in the DS-160 online',
      offsetDays: -240,
      durationDays: 7,
      dependsOn: ['documents', 'host-letter', 'child-docs'],
      documents: ['DS-160 confirmation page'],
      prepare: [
        'Passport and previous passports',
        'Travel history for the last 5 years',
        'Education and work history',
        'US address or hotel for the stay',
        'Social media handles used in the last 5 years',
      ],
      howTo:
        '1. Fill in Form DS-160 in English on the State Department Consular Electronic Application Center; save the application ID, as the session times out.\n2. Choose the post where you will be interviewed; it matches the next step.\n3. Upload the photo in the form.\n4. Print or save the confirmation page with the barcode; the appointment and interview use it.\n5. Answers are checked against earlier applications and the interview; keep them consistent.',
    },
    {
      id: 'book-china',
      title: 'Pay the fee and book the interview in China',
      offsetDays: -235,
      durationDays: 5,
      conditions: ['Only if you are applying in mainland China'],
      dependsOn: ['ds160'],
      documents: ['Visa fee receipt', 'Appointment confirmation'],
      prepare: [
        'DS-160 confirmation number',
        'The consular district for where you live or your hukou',
        'Check current wait times at each post',
      ],
      howTo:
        "1. In mainland China the embassy in Beijing and the consulates (such as Shanghai, Guangzhou and Shenyang) handle visitor visas; check current which posts are interviewing.\n2. Register on the appointment website linked from the embassy's visa pages, pay the application fee, then pick a date.\n3. The B1/B2 application fee was US$185 when the State Department page was checked in 2025; a separate visa integrity fee has also been legislated, so check current fees before paying.\n4. Waits for an interview can run to months; the 280-day start in this plan is an estimate to cover that. Check the State Department wait-time tool.\n5. Renewals of an earlier B1/B2 visa may qualify for an interview waiver (dropbox); the rules changed in 2025, so check current eligibility.",
    },
    {
      id: 'book-third',
      title: 'Pay the fee and book the interview where you live abroad',
      offsetDays: -235,
      durationDays: 5,
      conditions: ['Only if you live legally in another country, such as Canada, and are applying there'],
      dependsOn: ['ds160'],
      documents: ['Visa fee receipt', 'Appointment confirmation', 'Residence permit or visa for that country'],
      prepare: [
        'Proof of legal status there: permit, PR card or long-stay visa',
        'Proof of ties there: job, study, lease',
        'Check the local embassy page for third-country nationals',
      ],
      howTo:
        '1. A Chinese citizen living legally abroad (for example in Canada) can apply at a US embassy or consulate in that country; register on that country\'s appointment website and pay the fee in its currency.\n2. The State Department has tightened where applicants may apply; applying in a country where you are only visiting may not be accepted. Check the local embassy page for the current rule.\n3. Bring your residence permit; the officer weighs ties to where you live, not only to China.\n4. Wait times differ by city; compare them with the wait-time tool.',
    },
    {
      id: 'interview',
      title: 'Attend the visa interview',
      offsetDays: -90,
      durationDays: 1,
      dependsOn: ['book-china', 'book-third'],
      documents: ['Passport', 'DS-160 confirmation page', 'Appointment confirmation', 'Visa photo'],
      prepare: [
        'Old passports with earlier visas',
        'Bank statements, employment letter, itinerary',
        'Invitation letter and host documents, if visiting family',
        'Short, honest answers about the trip and when you come back',
      ],
      howTo:
        '1. Fingerprints are taken and a consular officer asks about the trip, money and ties at home.\n2. At the end the officer approves, refuses (usually under section 214(b)), or hands a form for administrative processing (section 221(g)).\n3. If approved, the passport stays with the post for the visa to be printed; delivery or pickup follows the embassy instructions.\n4. The 90-day date is an estimate; move it to your real appointment.',
    },
    {
      id: 'visa-issued',
      title: 'Get the passport back and check the visa',
      offsetDays: -75,
      durationDays: 14,
      dependsOn: ['interview'],
      documents: ['Passport', 'B1/B2 visa'],
      prepare: ['Delivery address or pickup location', 'Check name, date of birth, visa type, entries and expiry'],
      howTo:
        '1. Check the printed visa for mistakes before booking; report errors to the post straight away.\n2. Administrative processing (221(g)) can take weeks or longer; wait for the result before paying for flights.\n3. The visa lets you ask to enter; the border officer decides entry and length of stay.',
    },
    {
      id: 'evus',
      title: 'Enrol in EVUS before flying',
      offsetDays: -30,
      durationDays: 3,
      validForDays: 730,
      dependsOn: ['visa-issued'],
      documents: ['EVUS enrolment confirmation'],
      prepare: ['Passport with the 10-year B1/B2 visa', 'Email address', 'Check the current EVUS fee'],
      howTo:
        '1. Holders of a PRC passport with a 10-year B1/B2 visa update their details through EVUS on the official site evus.gov before travel.\n2. The State Department says an enrolment lasts 2 years, or until a new passport or new B1/B2 visa, whichever comes first.\n3. Airlines check EVUS before boarding; without it you can be denied boarding.\n4. Use only evus.gov; third-party sites charge extra. Check the current fee there.\n5. It repeats: enrol again every 2 years or after a new passport or visa.',
    },
    {
      id: 'flights',
      title: 'Book flights and travel medical insurance',
      offsetDays: -30,
      durationDays: 7,
      dependsOn: ['visa-issued'],
      documents: ['Flight itinerary', 'Travel insurance policy'],
      prepare: ['Return date inside the planned stay', 'Insurance covering US medical costs for the whole stay'],
      howTo:
        '1. Book after the visa is in hand, so a refusal or delay does not cost the fare.\n2. US medical care is expensive and visitors are generally not covered by any public plan; travel medical insurance is not asked for by the visa but is widely bought.\n3. Keep the return booking consistent with what you said at the interview.',
    },
    {
      id: 'arrival',
      title: 'Arrival: entry inspection and the I-94 record',
      offsetDays: 0,
      durationDays: 1,
      dependsOn: ['evus', 'flights'],
      documents: ['Passport', 'B1/B2 visa', 'EVUS enrolment confirmation', 'I-94 record'],
      prepare: [
        'US address for the stay',
        'Return ticket and proof of funds in carry-on',
        'Invitation letter and host contact, if visiting family',
      ],
      howTo:
        '1. A CBP officer asks about the purpose and length of the trip and decides whether to admit you and until when.\n2. B2 visitors are commonly admitted for up to 6 months; the real limit is the date on the electronic I-94, not the visa expiry.\n3. Look up the I-94 on the CBP site a few days after arrival and check the admit-until date.\n4. The visa can outlast the stay; each entry gets its own I-94.',
    },
    {
      id: 'extend',
      title: 'File Form I-539 to extend the stay',
      offsetDays: 135,
      durationDays: 14,
      conditions: ['Only if you need to stay past the I-94 admit-until date'],
      dependsOn: ['arrival'],
      documents: ['Form I-539', 'I-94 record', 'Passport', 'Bank statements'],
      prepare: [
        'Reason for staying longer, with papers such as medical letters',
        'Proof of funds for the extra time',
        'Return ticket or plan to leave',
        'Current USCIS fee from the G-1055 fee schedule',
      ],
      howTo:
        '1. Extending a B1/B2 stay, or changing to another status, is filed with USCIS on Form I-539 from inside the US.\n2. It is filed before the admit-until date on the I-94; USCIS suggests at least 45 days before.\n3. The date here assumes a 6-month admission; move it to 45 days before your real I-94 date.\n4. Check the fee on the USCIS fee schedule; processing can outlast the extra time asked for.\n5. Not immigration advice; the USCIS page is the reference.',
    },
    {
      id: 'leave',
      title: 'Leave on time and keep the records',
      offsetDays: 180,
      durationDays: 1,
      dependsOn: ['arrival'],
      documents: ['Passport', 'Boarding pass', 'I-94 record'],
      prepare: ['Copy of the I-94 and travel history from the CBP site', 'Boarding passes'],
      howTo:
        '1. Leave by the I-94 date, or by the date USCIS grants if an extension was approved.\n2. Staying past it, even by a day, voids the visa and makes later visas harder to get.\n3. Keep boarding passes and the I-94 history; the next DS-160 asks about earlier trips.\n4. The 180 days here is an estimate; move it to your real departure.',
    },
  ],
};
