import type { Playbook } from '../../domain/types';

const EMB = 'https://ph.china-embassy.gov.cn/eng/lsfw';
const NIA = 'https://en.nia.gov.cn/n147418';

export const visaCnPh: Playbook = {
  id: 'visa-cn-ph',
  title: 'Visiting China · Philippine passport',
  summary:
    'Paperwork plan for a Philippine passport holder visiting mainland China for tourism or family, from checking the few visa-free options to the L or Q2 visa in Manila or abroad, leaving the Philippines, the arrival card, registration, extensions and coming home.',
  region: 'China',
  country: 'CN',
  citizen: 'PH',
  family: 'visa-cn',
  anchorKind: 'trip',
  ages: { from: 0 },
  conditions: [
    'You hold a Philippine passport',
    'You are visiting mainland China for tourism or to see family or friends',
    'Not for work, study or moving to China; those use other visas',
    'The date is the day you arrive in China',
    'This is a planning aid, not immigration advice; the Chinese embassy, NIA and Philippine agency pages are the reference',
  ],
  reviewedAt: '2026-09-27',
  version: 1,
  sources: [
    {
      title: 'List of Countries Covered by Unilateral Visa Exemption Policies (as of February 17, 2026) — National Immigration Administration',
      url: `${NIA}/n147463/c183390/content.html`,
    },
    { title: 'Visa-Free Transit Policies (August 20, 2026) — National Immigration Administration', url: `${NIA}/n147463/c183412/content.html` },
    { title: 'Visa for China (Mainland Only) — Chinese Embassy in the Philippines', url: `${EMB}/visas/201208/t20120814_1336195.htm` },
    {
      title: 'China Expands Allowed Purposes of Visa-Free Entry to Hainan for 59 Countries — Chinese Embassy in the Philippines',
      url: `${EMB}/202408/t20240802_11465477.htm`,
    },
    {
      title: 'Notice on the Opening of the Chinese Visa Application Service Center in Manila — Chinese Embassy in the Philippines',
      url: `${EMB}/visas/202401/t20240119_11229433.htm`,
    },
    {
      title: 'Notice on Launching the China Online Visa Processing System — Chinese Embassy in the Philippines',
      url: `${EMB}/visas/202509/t20250929_11720134.htm`,
    },
    { title: 'Notice: reduced visa fees until December 31, 2026 — Chinese Embassy in the Philippines', url: `${EMB}/visas/202606/t20260611_11942336.htm` },
    { title: 'Chinese Visa Application Service Center, Manila', url: 'https://www.visaforchina.cn/MNL4_EN/' },
    { title: 'Online Arrival Card Filling — National Immigration Administration', url: 'https://s.nia.gov.cn/ArrivalCardFillingPC/' },
    {
      title: 'Policy Interpretation of the Nationwide Online Accommodation Registration for Foreigners — National Immigration Administration',
      url: `${NIA}/n147463/c237273/content.html`,
    },
    { title: 'Exit and Entry Administration Law of the PRC — National Immigration Administration', url: `${NIA}/n147458/c155978/content.html` },
    { title: 'Philippine passport appointments — Department of Foreign Affairs', url: 'https://consular.dfa.gov.ph/' },
    { title: 'Travel tax — TIEZA', url: 'https://tieza.gov.ph/travel-tax/' },
    { title: 'Reduced travel tax — TIEZA', url: 'https://tieza.gov.ph/reduced-travel-tax/' },
    { title: 'Bureau of Immigration — Philippines', url: 'https://immigration.gov.ph/' },
    { title: 'Commission on Filipinos Overseas', url: 'https://cfo.gov.ph/' },
    { title: 'Travel clearance for minors — DSWD', url: 'https://www.dswd.gov.ph/' },
    { title: 'eTravel — Philippine travel information system', url: 'https://etravel.gov.ph/' },
  ],
  steps: [
    {
      id: 'visa-free',
      title: 'Check whether any visa-free entry covers the trip',
      offsetDays: -90,
      durationDays: 7,
      dependsOn: [],
      documents: ['Passport'],
      prepare: ['Purpose of the trip and number of days', 'Which cities you will visit', 'Onward ticket, if only passing through'],
      howTo:
        "1. China's unilateral visa exemption (免签, miǎnqiān) list from the National Immigration Administration (NIA), as of February 17, 2026, does not include the Philippines; check the list again before booking, since it changes often.\n2. The 240-hour visa-free transit (过境免签, guòjìng miǎnqiān) list (NIA, August 20, 2026, 57 countries) does not include the Philippines either.\n3. Any nationality can transit for up to 24 hours without a visa if staying in the airport's restricted area with a confirmed onward ticket to a third country.\n4. The embassy lists Hainan visa-free entry for 59 countries including the Philippines: up to 30 days in Hainan province only, arriving directly or via a third country, Hong Kong or Macao (announced 2024; check current).\n5. For the rest of the mainland, plan on an L (tourism) or Q2 (visiting relatives) visa. If a visa-free option fits, mark the visa steps \"Not for me\".",
    },
    {
      id: 'passport',
      title: 'Check passport validity and blank pages',
      offsetDays: -90,
      durationDays: 30,
      conditions: ['Only if your passport has less than 6 months left or no blank visa pages'],
      dependsOn: [],
      documents: ['Passport', 'PSA birth certificate'],
      prepare: ['DFA online appointment', 'Old passport', 'A valid government ID'],
      howTo:
        '1. Chinese missions generally ask for a passport with at least 6 months of validity and blank visa pages (check the current checklist).\n2. Book a renewal on the DFA online appointment system before applying.',
    },
    {
      id: 'visa-type',
      title: 'Choose L or Q2 and gather your documents',
      offsetDays: -70,
      durationDays: 14,
      conditions: ['Only if you need a visa'],
      dependsOn: ['visa-free', 'passport'],
      documents: ['Passport', 'Passport photo', 'Flight itinerary', 'Bank statements'],
      prepare: [
        'L (tourism): round-trip booking and hotel reservations, or an invitation from someone in China',
        'Q2 (visiting relatives): the invitation letter and the relative\'s ID (next step)',
        'Copy of the passport data page and any previous Chinese visas',
        'Proof of work or funds if the centre checklist asks',
      ],
      howTo:
        "1. L is for tourism, including visiting friends; Q2 is for short visits to relatives who are Chinese citizens or foreigners with permanent residence in China (up to 180 days).\n2. The embassy decides the validity, stay per entry and number of entries; the duration printed on the visa is what counts.\n3. Check the Manila centre's current checklist; lists for Philippine applicants may differ from other countries'.",
    },
    {
      id: 'host-invitation',
      title: 'Get the invitation letter and the inviter\'s ID copy',
      offsetDays: -70,
      durationDays: 14,
      conditions: ['Only if visiting family or friends in China'],
      dependsOn: ['visa-free'],
      documents: ['Invitation letter', "Copy of inviter's Chinese ID card or permanent residence card"],
      prepare: [
        'Your details, the visit (purpose, dates, places, relationship, who pays)',
        "The inviter's name, phone, address and signature",
        'Proof of the family relationship for Q2: PSA birth or marriage certificate, or a kinship certificate',
      ],
      howTo:
        "1. The inviter writes a letter with your details, the visit and their own details, and adds a copy of their Chinese ID card (身份证, shēnfènzhèng) or foreign permanent residence card.\n2. For Q2, proof of the family relationship is usually asked for; check whether your centre also asks for the relative's household register (户口本, hùkǒu běn).\n3. The same host usually registers your stay after arrival (see below).",
    },
    {
      id: 'child-documents',
      title: "Prepare a child's application",
      offsetDays: -70,
      durationDays: 14,
      conditions: ['Only if a child under 18 is travelling'],
      dependsOn: ['visa-free'],
      documents: ['PSA birth certificate', 'Passport', 'Passport photo'],
      prepare: ["Copies of both parents' passports or IDs", "A parent's signature on the child's form", 'Consent letter if a parent is not travelling (check current)'],
      howTo:
        "1. Each child has their own application.\n2. The PSA birth certificate shows the parents; a parent signs a minor's form.\n3. A child with a Chinese-citizen parent may be treated as a Chinese citizen and not get a visa; check with the embassy first.\n4. The Philippine departure side for minors is in the DSWD step below.",
    },
    {
      id: 'apply-ph',
      title: 'Fill in the online form and submit at the Manila visa centre',
      offsetDays: -45,
      durationDays: 7,
      conditions: ['Only if you need a visa and are applying from the Philippines'],
      dependsOn: ['visa-type', 'host-invitation', 'child-documents'],
      documents: ['Visa application form', 'Passport'],
      prepare: [
        'Printed and signed form and confirmation page',
        'Scans of the documents to upload',
        'Visa fee (reduced rates in PHP until December 31, 2026) plus the centre service fee',
      ],
      howTo:
        "1. Since October 13, 2025, the embassy's China Online Visa Processing System lets applicants fill in the form and upload documents on visaforchina.cn (Manila site), then go to the centre.\n2. Since January 29, 2024, the Chinese Visa Application Service Center in Manila (Noble Square, Ayala Avenue, Makati) takes ordinary-passport applications; the embassy no longer does, and says it has entrusted no other agent.\n3. Living near Cebu, Davao or Laoag: check which centre or consulate serves your district.\n4. Short-term applicants have been exempt from fingerprints until December 31, 2026 under China's global measure; check current at the centre.\n5. Express and rush services cost extra; the centre may ask for more papers or an interview.",
    },
    {
      id: 'apply-abroad',
      title: 'Apply where you live outside the Philippines',
      offsetDays: -45,
      durationDays: 7,
      conditions: ['Only if you need a visa and live legally outside the Philippines, e.g. working in Canada or the Gulf'],
      dependsOn: ['visa-type', 'host-invitation', 'child-documents'],
      documents: ['Visa application form', 'Passport', 'Residence permit'],
      prepare: ['Proof of legal status there (work, study or residence permit)', 'The Chinese embassy or consulate that covers where you live'],
      howTo:
        '1. Chinese missions generally accept applications from foreigners living legally in their country, with a copy of that status document; check the local checklist.\n2. Many now use the same online form and a local Chinese Visa Application Service Center.\n3. Fees are set in local currency and differ from the Philippine rates.',
    },
    {
      id: 'visa-collect',
      title: 'Collect the passport and check the visa',
      offsetDays: -30,
      durationDays: 10,
      conditions: ['Only if you need a visa'],
      dependsOn: ['apply-ph', 'apply-abroad'],
      documents: ['Chinese visa', 'Passport'],
      prepare: ['Pickup receipt', 'Check entries, "enter before" date and duration of each stay'],
      howTo:
        '1. Processing time is an estimate; check the centre site for regular, express and rush times.\n2. Check the visa: entries, the date to enter by, and the duration of each stay (often counted from the day after entry).\n3. Book flights once the visa is issued.',
    },
    {
      id: 'dswd-clearance',
      title: 'Get a DSWD travel clearance for a child',
      offsetDays: -10,
      durationDays: 14,
      conditions: ['Only if a Filipino child under 18 is leaving without a parent, or with someone other than a parent'],
      dependsOn: ['visa-collect'],
      documents: ['DSWD travel clearance', 'PSA birth certificate'],
      prepare: ["Parents' written consent", 'Details of the adult travelling with the child', 'Photos of the child'],
      howTo:
        '1. The Department of Social Welfare and Development (DSWD) issues travel clearances for Filipino minors travelling abroad alone or with an adult who is not a parent.\n2. A child travelling with a parent generally does not need one; check current exemptions on the DSWD site.\n3. Apply online or at a DSWD field office; check current processing time and validity, and apply earlier if you can.',
    },
    {
      id: 'cfo',
      title: 'Check whether a CFO certificate applies',
      offsetDays: -7,
      durationDays: 21,
      conditions: ['Only if you are going to join a foreign spouse, partner or fiancé(e), or emigrating, rather than just visiting'],
      dependsOn: ['visa-collect'],
      documents: ['CFO certificate'],
      prepare: ['Marriage certificate or proof of relationship', "Partner's passport copy", 'Visa'],
      howTo:
        '1. The Commission on Filipinos Overseas (CFO) runs guidance and counselling for Filipinos leaving to join a foreign spouse, partner or fiancé(e), and registration for emigrants; the Bureau of Immigration checks the CFO certificate at departure.\n2. A short L or Q2 visit is generally not an emigrant departure, but visiting a Chinese partner can prompt questions at the counter; check with the CFO which case yours is.\n3. Moving to China on a Q1 family-reunion visa is outside this plan.',
    },
    {
      id: 'travel-tax',
      title: 'Pay the Philippine travel tax or check the exemption',
      offsetDays: -14,
      durationDays: 7,
      dependsOn: ['visa-collect'],
      documents: ['Travel tax receipt'],
      prepare: ['Ticket and booking reference', 'Proof of exemption or reduced rate, if any'],
      howTo:
        '1. Filipinos and some residents leaving the Philippines pay travel tax to TIEZA: PHP 1,620 economy or PHP 2,700 first class at the full rate when this plan was reviewed.\n2. Many airline tickets bought in the Philippines include it; check the fare breakdown.\n3. Children over 2 and under 12 pay the reduced rate, infants up to 2 are exempt, and overseas Filipino workers and some permanent residents abroad are exempt; check TIEZA.\n4. If not included, pay online on the TIEZA site or at the airport counter before check-in.',
    },
    {
      id: 'departure-documents',
      title: 'Pack papers for the Bureau of Immigration departure check',
      offsetDays: -7,
      durationDays: 5,
      dependsOn: ['visa-collect'],
      documents: ['Passport', 'Chinese visa', 'Return ticket', 'Certificate of employment'],
      prepare: [
        'Return ticket',
        'Hotel booking or host address in China',
        'Proof of work, approved leave, business or school',
        'Proof of funds',
        'Invitation letter and relationship proof if visiting family or friends',
      ],
      howTo:
        '1. At departure, a Bureau of Immigration (BI) officer checks the passport, visa, boarding pass and return ticket, following inter-agency (IACAT) departure guidelines meant to stop trafficking and illegal recruitment.\n2. Some travellers are sent to secondary inspection and asked for supporting papers; being refused departure is called offloading.\n3. Keep the papers in the carry-on, not the checked bag.\n4. Check the current IACAT guidelines on the BI site before the trip.',
    },
    {
      id: 'departure',
      title: 'Leave the Philippines',
      offsetDays: -1,
      durationDays: 1,
      dependsOn: ['departure-documents', 'travel-tax', 'cfo', 'dswd-clearance'],
      documents: ['Passport', 'Chinese visa', 'Boarding pass', 'Travel tax receipt'],
      prepare: ['Arrive at the airport early for immigration lines', 'Check any eTravel or e-Gate registration the BI currently asks departing travellers for'],
      howTo:
        '1. Check in, then go through BI departure; answer questions about the trip plainly.\n2. If referred to secondary inspection, show the papers from the previous step.\n3. The date here is the day before arrival; move it to the real flight.',
    },
    {
      id: 'arrival-card',
      title: 'Fill in the arrival card online',
      offsetDays: -3,
      durationDays: 3,
      dependsOn: ['visa-collect'],
      documents: ['Arrival card'],
      prepare: ['Passport and visa details', 'Flight number', 'Address of your first night'],
      howTo:
        '1. Since November 20, 2025, foreigners can submit the arrival card (入境卡, rùjìng kǎ) before travelling on the NIA website, the "NIA 12367" app, or WeChat and Alipay mini-programs.\n2. It is free; use only the official channels.\n3. Kiosks and paper cards are still available at the port.',
    },
    {
      id: 'entry',
      title: 'Enter China and note your stay limit',
      offsetDays: 0,
      durationDays: 1,
      dependsOn: ['departure', 'arrival-card'],
      documents: ['Passport', 'Chinese visa', 'Arrival card'],
      prepare: ['Return ticket', 'Address and phone of where you stay', 'Invitation letter, if any'],
      howTo:
        '1. The border officer checks the passport, visa and arrival card, and may take fingerprints.\n2. The stay is the duration printed on the visa; Hainan visa-free stays are 30 days counted from the day after arrival.\n3. Write down the last day you can stay; the rest of this plan uses it.',
    },
    {
      id: 'registration',
      title: 'Register where you stay within 24 hours',
      offsetDays: 1,
      durationDays: 1,
      dependsOn: ['entry'],
      documents: ['Passport'],
      prepare: ["Your host's name and address", 'The "NIA 12367" app or mini-program'],
      howTo:
        '1. Accommodation registration (住宿登记, zhùsù dēngjì): hotels register guests for you.\n2. Staying with family or friends, you or your host register within 24 hours of arrival, online through NIA channels or at the local police station.\n3. Missing it can bring a warning or a fine; register again after each move to a private home.',
    },
    {
      id: 'extend',
      title: 'Extend the stay at the exit-entry office',
      offsetDays: 20,
      durationDays: 7,
      conditions: ['Only if you need to stay longer than your visa allows'],
      dependsOn: ['entry'],
      documents: ['Passport', 'Stay permit'],
      prepare: ['Reason for staying longer', 'Accommodation registration record', 'Passport photo'],
      howTo:
        "1. Apply at the exit-entry administration of the local public security bureau (公安局出入境管理, gōng'ānjú chūrùjìng guǎnlǐ) where you are staying.\n2. The Exit and Entry Administration Law asks for the application at least 7 days before the stay runs out, and the total extension cannot exceed the original stay.\n3. Leaving Hainan for the rest of China on visa-free entry also needs a visa from Hainan's exit-entry office before the stay ends.\n4. The date here assumes a 30-day stay; move it to at least 7 days before your real last day.",
    },
    {
      id: 'etravel',
      title: 'Register on eTravel before flying home',
      offsetDays: 26,
      durationDays: 3,
      dependsOn: ['entry'],
      documents: ['eTravel QR code'],
      prepare: ['Passport', 'Flight number', 'Address in the Philippines'],
      howTo:
        "1. eTravel is the Philippine government's free online travel declaration; arriving travellers, Filipinos included, register before landing, usually within 72 hours of the flight; check the current window.\n2. Use etravel.gov.ph or the eGovPH app only; look-alike sites charge fees.\n3. Show the QR code on arrival in the Philippines.",
    },
    {
      id: 'return',
      title: 'Leave China before the permitted stay ends',
      offsetDays: 29,
      durationDays: 1,
      dependsOn: ['etravel'],
      documents: ['Passport', 'Boarding pass'],
      prepare: ['Your last permitted day', 'Copies of the visa and boarding passes'],
      howTo:
        '1. Leave by the last day of your visa stay or extension; overstaying brings fines or detention and can affect later visas.\n2. Keep the visa and boarding passes; later applications ask about past trips.\n3. The date here assumes a 30-day stay; move it to the real return flight.',
    },
  ],
};
