import type { Playbook } from '../../domain/types';

const MOFA = 'https://www.mofa.go.jp';
const EMB = 'https://www.ph.emb-japan.go.jp/itpr_en';

export const visaJpPh: Playbook = {
  id: 'visa-jp-ph',
  title: 'Visiting Japan · Philippine passport',
  summary:
    'Paperwork plan for a Philippine passport holder visiting Japan for tourism or family, from the temporary visitor visa through the Japan Visa Application Centre, an accredited agency or a consulate abroad to leaving the Philippines, Visit Japan Web, arrival and coming home.',
  region: 'Japan',
  country: 'JP',
  citizen: 'PH',
  family: 'visa-jp',
  anchorKind: 'trip',
  ages: { from: 0 },
  conditions: [
    'You hold a Philippine passport',
    'You are visiting Japan for tourism or to see family or friends, for up to 90 days',
    'Not for work, study or long stays; those use other visas',
    'The date is the day you arrive in Japan',
    'This is a planning aid, not immigration advice; MOFA, the Japanese embassy and the Philippine agency pages are the reference',
  ],
  reviewedAt: '2026-09-27',
  version: 1,
  sources: [
    { title: 'Visa — Ministry of Foreign Affairs of Japan', url: `${MOFA}/j_info/visit/visa/index.html` },
    { title: 'Nationals of the Philippines who wish to come to Japan for a short-term stay — MOFA', url: `${MOFA}/j_info/visit/visa/short/philippine.html` },
    { title: 'Checklist for single-entry short-term stay visa, Philippine nationals applying in the Philippines, April 2025 (PDF) — MOFA', url: `${MOFA}/files/000121323.pdf` },
    { title: 'Multiple-entry visa for nationals of Indonesia, the Philippines and Viet Nam (PDF) — MOFA', url: `${MOFA}/files/000433548.pdf` },
    { title: 'Visa application form (English, PDF) — MOFA', url: `${MOFA}/files/000124525.pdf` },
    { title: 'Letter of guarantor (身元保証書, PDF) — MOFA', url: `${MOFA}/files/000262545.pdf` },
    { title: 'Letter of invitation, single entry (PDF) — MOFA', url: `${MOFA}/files/000137089.pdf` },
    { title: 'Travel itinerary (PDF) — MOFA', url: `${MOFA}/files/000262548.pdf` },
    { title: 'Documents for Filipino parents of Japanese-Filipino children — MOFA', url: `${MOFA}/j_info/visit/visa/short/jfc.html` },
    { title: 'The JAPAN eVISA system (electronic visa) — MOFA', url: `${MOFA}/j_info/visit/visa/visaonline.html` },
    { title: 'Visa / Consular Services — Embassy of Japan in the Philippines', url: `${EMB}/00_000035.html` },
    { title: 'General information on visa application — Embassy of Japan in the Philippines', url: `${EMB}/00_000261.html` },
    { title: 'Japan Visa Application Centre in the Philippines — VFS Global', url: 'https://visa.vfsglobal.com/phl/en/jpn/' },
    { title: 'Visit Japan Web — Digital Agency', url: 'https://www.vjw.digital.go.jp/' },
    { title: 'Extension of period of stay — Immigration Services Agency of Japan', url: 'https://www.moj.go.jp/isa/applications/procedures/16-3.html' },
    { title: 'Philippine passport appointments — Department of Foreign Affairs', url: 'https://consular.dfa.gov.ph/' },
    { title: 'Travel tax — TIEZA', url: 'https://tieza.gov.ph/travel-tax/' },
    { title: 'Reduced travel tax — TIEZA', url: 'https://tieza.gov.ph/reduced-travel-tax/' },
    { title: 'Bureau of Immigration — Philippines', url: 'https://immigration.gov.ph/' },
    { title: 'Commission on Filipinos Overseas', url: 'https://cfo.gov.ph/' },
    { title: 'Travel clearance for minors — DSWD', url: 'https://www.dswd.gov.ph/' },
    { title: 'eTravel — Philippine travel information system', url: 'https://etravel.gov.ph/' },
  ],
  steps: [
    {
      id: 'entry-check',
      title: 'Check which Japanese visa fits the trip',
      offsetDays: -120,
      durationDays: 7,
      dependsOn: [],
      documents: ['Passport'],
      prepare: [
        'Purpose of the trip and number of days',
        'Where you live now: the Philippines or another country',
        'Past visits to Japan and G7 countries in the last 3 years',
      ],
      howTo:
        "1. MOFA lists the Philippines among the nationalities that need a visa for a short-term stay (up to 90 days for tourism, business or visiting relatives or friends, with no paid work).\n2. The Embassy of Japan says the temporary visitor visa for Philippine nationals is free of charge (gratis); the visa centre or agency charges its own handling fee.\n3. Single entry is the usual visa. A multiple-entry visa, up to 30 days per stay, is open to Filipinos with an ICAO-standard passport who visited Japan in the last 3 years and can pay for the trip, who visited Japan and a G7 country in that time, who have ample finances, or who are the spouse or child of the last group; the visa may still be issued as single entry.\n4. JAPAN eVISA (MOFA, May 15, 2026): Filipinos living in the Philippines can get one only on a packaged tour through a designated travel agency, with a 15-day stay; residents of listed countries such as Australia, Canada, the United Kingdom and the United States apply online there.\n5. MOFA's lists change; check them again before booking.",
    },
    {
      id: 'passport',
      title: 'Renew the Philippine passport if it runs short',
      offsetDays: -120,
      durationDays: 30,
      conditions: ['Only if your passport expires during or soon after the trip, or has no blank page'],
      dependsOn: [],
      documents: ['Passport', 'PSA birth certificate'],
      prepare: ['DFA online appointment', 'Old passport', 'A valid government ID'],
      howTo:
        '1. The visa goes on a valid passport; a multiple-entry visa needs a machine-readable or e-passport to the ICAO standard.\n2. Book a renewal on the DFA online appointment system; renew before applying so the visa is not on a passport about to lapse.',
    },
    {
      id: 'own-docs',
      title: 'Gather your own documents',
      offsetDays: -95,
      durationDays: 21,
      dependsOn: ['entry-check'],
      documents: ['Passport', 'Visa application form', 'Passport photo', 'PSA birth certificate', 'Bank certificate'],
      prepare: [
        'PSA birth certificate; if it is illegible, also the local civil registrar copy',
        'PSA marriage certificate, if married',
        'Income certificate or income tax return, or a bank balance certificate or statement',
        'Itinerary in Japan on the MOFA form (tourism)',
        'Certificate of employment and approved leave, for the departure check later',
      ],
      howTo:
        '1. The MOFA checklist for Filipinos applying in the Philippines lists passport, one application form, one photo, PSA birth certificate (and marriage certificate if married) and proof you can pay for the trip.\n2. For a late-registered birth, it also asks for a baptismal certificate, an elementary or high school record and a yearbook.\n3. Documents must be issued within the last 3 months.\n4. Flight and hotel bookings are not needed at application; the itinerary lists dates, where you stay and what you plan to do.',
    },
    {
      id: 'host-docs',
      title: 'Get the invitation and guarantor papers from Japan',
      offsetDays: -95,
      durationDays: 21,
      conditions: ['Only if visiting family or friends in Japan'],
      dependsOn: ['entry-check'],
      documents: ['Letter of invitation', "Guarantor's letter", 'Certificate of residence (Juminhyo)'],
      prepare: [
        'Relationship proof: PSA birth or marriage certificates, or the Japanese family register (Koseki tohon); for friends, photos, e-mails or call history',
        'A document showing the reason, e.g. a wedding or graduation invitation or a medical certificate',
        "Host's itinerary for you and a list of applicants if more than one",
        "If the host is a foreign resident: copy of both sides of the residence card, full Juminhyo and passport copy",
        "If the host pays: the guarantor's letter and an income or tax certificate, or a bank balance certificate",
      ],
      howTo:
        "1. The host in Japan prepares these and sends them to you, not to the embassy.\n2. The invitation letter is addressed to the Ambassador of Japan in the Philippines and describes the planned activities in detail; just 'tourism' or 'visiting relatives' is not accepted.\n3. The guarantor's letter (身元保証書, mimoto hoshōsho) is for whoever in Japan covers your costs; MOFA says a withholding tax slip is not accepted as proof of their funds.\n4. Copies of documents issued in Japan are accepted, issued within the last 3 months; seals on these forms are no longer needed.",
    },
    {
      id: 'child-docs',
      title: "Prepare a child's application",
      offsetDays: -95,
      durationDays: 21,
      conditions: ['Only if a child under 18 is travelling'],
      dependsOn: ['entry-check'],
      documents: ['PSA birth certificate', 'Passport', 'Passport photo'],
      prepare: [
        "Each child's own application form and photo",
        "Parents' marriage certificate and proof of the parents' funds",
        'A parent\'s written consent if the child travels without both parents (check the current checklist)',
      ],
      howTo:
        '1. Each child needs their own visa; family members travelling together on the same schedule usually apply together.\n2. The PSA birth certificate shows the parents and links the child to the funds and invitation.\n3. A Filipino parent travelling with a Japanese-Filipino child uses the separate MOFA list for JFC families.\n4. The Philippine departure side for minors is in the DSWD step below.',
    },
    {
      id: 'apply-ph',
      title: 'Apply through the Japan Visa Application Centre or an accredited agency',
      offsetDays: -60,
      durationDays: 7,
      conditions: ['Only if you are applying from the Philippines'],
      dependsOn: ['passport', 'own-docs', 'host-docs', 'child-docs'],
      documents: ['Passport', 'Visa application form', 'Appointment confirmation'],
      prepare: [
        'Book on the VFS Global Japan site, or go through a travel agency the embassy has accredited',
        'Handling fee for the centre or agency (the visa itself is gratis)',
        'The 8-digit acceptance number on your receipt',
      ],
      howTo:
        "1. Since April 7, 2025, the embassy takes ordinary applications through its Japan Visa Application Centre run by VFS Global, with centres in Parañaque, Makati, Quezon City, Cebu and Davao; accredited travel agencies also lodge applications there.\n2. Only special cases, such as government invitees or humanitarian cases, apply directly at the embassy or the consulates in Cebu and Davao.\n3. Processing takes at least 5 working days after the embassy accepts the file; the embassy may ask for more documents or an interview and does not release passports early for a flight date.\n4. After a refusal, the same purpose can be reapplied for only after 6 months, and reasons are not given.",
    },
    {
      id: 'evisa-tour',
      title: 'Join a packaged tour that includes the eVISA',
      offsetDays: -60,
      durationDays: 7,
      conditions: ['Only if you live in the Philippines and join a packaged tour from a designated travel agency'],
      dependsOn: ['entry-check', 'passport'],
      documents: ['Passport', 'Visa issuance notice'],
      prepare: ['Tour booking with the designated agency', 'Documents the agency asks for'],
      howTo:
        '1. MOFA lets Filipinos living in the Philippines get a tourism eVISA through designated travel agencies for packaged tours; the stay is 15 days.\n2. The agency applies; an interview at the embassy may still be requested.\n3. At the airport the visa issuance notice is shown online; a PDF, screenshot or printout is not accepted.\n4. eVISA is for air or scheduled sea travel only.',
    },
    {
      id: 'apply-abroad',
      title: 'Apply from the country where you live',
      offsetDays: -60,
      durationDays: 7,
      conditions: ['Only if you live legally outside the Philippines, e.g. working in Canada or the Gulf'],
      dependsOn: ['passport', 'own-docs', 'host-docs', 'child-docs'],
      documents: ['Passport', 'Residence permit', 'Visa application form'],
      prepare: [
        'Proof of legal residence there (residence card or visa)',
        "The Japanese embassy or consulate that covers where you live, and its own checklist",
      ],
      howTo:
        "1. MOFA says visas are applied for at the Japanese mission with jurisdiction over your place of residence, or through its accredited agency, visa centre or online system.\n2. As of May 15, 2026, residents of Australia, Brazil, Cambodia, Canada, Saudi Arabia, South Africa, Taiwan, the United Kingdom and the United States can apply for a single-entry tourism eVISA online at JAPAN eVISA; Hong Kong, India, Indonesia, Macau, Mongolia, Korea, Singapore and the UAE go through accredited agencies.\n3. The Philippine checklist above is for applications in the Philippines; the documents abroad may differ, so use that mission's list.\n4. Family visits and multiple-entry visas still go to the mission as a paper application.",
    },
    {
      id: 'decision',
      title: 'Collect the passport and check the visa',
      offsetDays: -45,
      durationDays: 14,
      dependsOn: ['apply-ph', 'evisa-tour', 'apply-abroad'],
      documents: ['Visa', 'Passport'],
      prepare: ['Check name, passport number, number of entries, validity and stay'],
      howTo:
        '1. The passport comes back through the centre or agency, with the visa if issued.\n2. Check the visa right away; a single-entry visa has an expiry date to enter by (check the date printed on it).\n3. Book flights once the visa is issued, so a refusal or delay does not cost the fare.',
    },
    {
      id: 'dswd-clearance',
      title: 'Get a DSWD travel clearance for a child',
      offsetDays: -10,
      durationDays: 14,
      conditions: ['Only if a Filipino child under 18 is leaving without a parent, or with someone other than a parent'],
      dependsOn: ['decision'],
      documents: ['DSWD travel clearance', 'PSA birth certificate'],
      prepare: ["Parents' written consent", 'Details of the adult travelling with the child', 'Photos of the child'],
      howTo:
        '1. The Department of Social Welfare and Development (DSWD) issues travel clearances for Filipino minors travelling abroad alone or with an adult who is not a parent.\n2. A child travelling with a parent generally does not need one; check current exemptions on the DSWD site.\n3. Apply online or at a DSWD field office; check current processing time and validity, and apply earlier if you can.',
    },
    {
      id: 'cfo',
      title: 'Check whether a CFO certificate applies',
      offsetDays: -7,
      durationDays: 21,
      conditions: ['Only if you are going to join a foreign spouse, partner or fiancé(e), or emigrating, rather than just visiting'],
      dependsOn: ['decision'],
      documents: ['CFO certificate'],
      prepare: ['Marriage certificate or proof of relationship', "Partner's passport copy", 'Visa'],
      howTo:
        '1. The Commission on Filipinos Overseas (CFO) runs guidance and counselling for Filipinos leaving to join a foreign spouse, partner or fiancé(e), and registration for emigrants; the Bureau of Immigration checks the CFO certificate at departure.\n2. A short visit on a temporary visitor visa is generally not an emigrant departure, but visiting a Japanese partner can prompt questions at the counter; check with the CFO which case yours is.\n3. Moving to Japan as a spouse uses a Certificate of Eligibility and is outside this plan.',
    },
    {
      id: 'travel-tax',
      title: 'Pay the Philippine travel tax or check the exemption',
      offsetDays: -14,
      durationDays: 7,
      dependsOn: ['decision'],
      documents: ['Travel tax receipt'],
      prepare: ['Ticket and booking reference', 'Proof of exemption or reduced rate, if any'],
      howTo:
        '1. Filipinos and some residents leaving the Philippines pay travel tax to TIEZA: PHP 1,620 economy or PHP 2,700 first class at the full rate when this plan was reviewed.\n2. Many airline tickets bought in the Philippines include it; check the fare breakdown.\n3. Children over 2 and under 12 pay the reduced rate, infants up to 2 are exempt, and overseas Filipino workers and some permanent residents abroad are exempt; check TIEZA.\n4. If not included, pay online on the TIEZA site or at the airport counter before check-in.',
    },
    {
      id: 'departure-documents',
      title: 'Pack papers for the Bureau of Immigration departure check',
      offsetDays: -7,
      durationDays: 5,
      dependsOn: ['decision'],
      documents: ['Passport', 'Visa', 'Return ticket', 'Certificate of employment'],
      prepare: [
        'Return ticket',
        'Hotel booking or host address in Japan',
        'Proof of work, approved leave, business or school',
        'Proof of funds',
        "Copies of the invitation letter, guarantor's letter and relationship proof if visiting family or friends",
      ],
      howTo:
        '1. At departure, a Bureau of Immigration (BI) officer checks the passport, visa, boarding pass and return ticket, following inter-agency (IACAT) departure guidelines meant to stop trafficking and illegal recruitment.\n2. Some travellers are sent to secondary inspection and asked for supporting papers; being refused departure is called offloading.\n3. Keep the papers in the carry-on, not the checked bag.\n4. Check the current IACAT guidelines on the BI site before the trip.',
    },
    {
      id: 'departure',
      title: 'Leave the Philippines',
      offsetDays: -1,
      durationDays: 1,
      dependsOn: ['departure-documents', 'travel-tax', 'cfo', 'dswd-clearance'],
      documents: ['Passport', 'Visa', 'Boarding pass', 'Travel tax receipt'],
      prepare: ['Arrive at the airport early for immigration lines', 'Check any eTravel or e-Gate registration the BI currently asks departing travellers for'],
      howTo:
        '1. Check in, then go through BI departure; answer questions about the trip plainly.\n2. If referred to secondary inspection, show the papers from the previous step.\n3. The date here is the day before arrival; move it to the real flight.',
    },
    {
      id: 'vjw',
      title: 'Register on Visit Japan Web before you fly',
      offsetDays: -2,
      durationDays: 3,
      dependsOn: ['decision'],
      documents: ['Passport', 'Flight itinerary'],
      prepare: ['Passport details', 'Flight number and address in Japan', 'A phone with the QR codes saved'],
      howTo:
        '1. The Embassy of Japan points travellers to Visit Japan Web, the Digital Agency site for entering immigration and customs details before arrival; it gives QR codes to show at the airport.\n2. It is optional; paper cards on the plane still work.\n3. eVISA holders also keep the visa issuance notice open online for the airport.',
    },
    {
      id: 'arrival',
      title: 'Arrival: landing examination',
      offsetDays: 0,
      durationDays: 1,
      dependsOn: ['departure', 'vjw'],
      documents: ['Passport', 'Visa', 'Return ticket'],
      prepare: ['Address and phone number of your hotel or host', 'Return ticket', 'Invitation letter copy, if visiting family'],
      howTo:
        '1. The immigration officer takes fingerprints and a face photo, checks the visa and decides the period of stay; holding a visa does not mean entry is assured.\n2. The landing sticker shows the status (Temporary Visitor) and the last day of the stay; eVISA tour stays are 15 days.\n3. Short-term visitors carry their passport while in Japan.\n4. Note the last day; the rest of this plan uses it.',
    },
    {
      id: 'extend',
      title: 'Ask the immigration bureau for more time',
      offsetDays: 10,
      durationDays: 7,
      conditions: ['Only if something like illness or an accident keeps you in Japan past the date you were given'],
      dependsOn: ['arrival'],
      documents: ['Passport'],
      prepare: ["Reason and proof, e.g. a doctor's letter", 'Return ticket and proof of funds', 'Check the current fee'],
      howTo:
        '1. Extensions of a period of stay are filed at the regional immigration bureau (出入国在留管理局) for where you are staying, before the stay ends.\n2. For Temporary Visitor status they are the exception, for reasons such as illness or accidents (check current); a wish to stay longer is not usually enough.\n3. Changing to a long-stay status from inside Japan is generally not how it works; long stays start with a Certificate of Eligibility.\n4. The date here is an estimate; move it to before the last day on your landing sticker.',
    },
    {
      id: 'etravel',
      title: 'Register on eTravel before flying home',
      offsetDays: 27,
      durationDays: 3,
      dependsOn: ['arrival'],
      documents: ['eTravel QR code'],
      prepare: ['Passport', 'Flight number', 'Address in the Philippines'],
      howTo:
        "1. eTravel is the Philippine government's free online travel declaration; arriving travellers, Filipinos included, register before landing, usually within 72 hours of the flight; check the current window.\n2. Use etravel.gov.ph or the eGovPH app only; look-alike sites charge fees.\n3. Show the QR code on arrival in the Philippines.",
    },
    {
      id: 'return',
      title: 'Leave Japan on time and keep the records',
      offsetDays: 30,
      durationDays: 1,
      dependsOn: ['etravel'],
      documents: ['Passport', 'Boarding pass'],
      prepare: ['The last day on the landing sticker', 'Copies of the visa and boarding passes'],
      howTo:
        '1. Leave by the last day of your period of stay; overstaying can lead to removal and a ban on returning.\n2. Keep the visa, landing stickers and boarding passes; a multiple-entry visa later looks at trips to Japan in the last 3 years.\n3. The 30 days here is an estimate; move it to the real return flight.',
    },
  ],
};
