import type { Playbook } from '../../domain/types';

const IRCC = 'https://www.canada.ca/en/immigration-refugees-citizenship/services';

export const visaCaCn: Playbook = {
  id: 'visa-ca-cn',
  title: 'Visiting Canada · Chinese passport',
  summary:
    'Paperwork plan for a short visit to Canada on a Chinese passport: the visitor visa (TRV) or super visa, the online IRCC application, biometrics in China or abroad, arrival, visitor record and leaving on time.',
  region: 'Canada',
  country: 'CA',
  citizen: 'CN',
  family: 'visa-ca',
  anchorKind: 'trip',
  ages: { from: 0 },
  conditions: [
    "You travel on a passport of the People's Republic of China",
    'The visit is for tourism, visiting family or friends, or a short business trip',
    'Not for study, work or moving to Canada',
    'The date is the day you arrive in Canada',
  ],
  reviewedAt: '2026-09-27',
  version: 1,
  sources: [
    { title: 'Find out if you need a visa or eTA — Canada.ca', url: `${IRCC}/visit-canada/check-visa-eta.html` },
    { title: 'Entry requirements by country or territory — Canada.ca', url: `${IRCC}/visit-canada/entry-requirements-country.html` },
    { title: 'Apply for a visitor visa — Canada.ca', url: `${IRCC}/visit-canada/apply-visitor-visa.html` },
    { title: 'Letter of invitation — Canada.ca', url: `${IRCC}/visit-canada/letter-invitation.html` },
    { title: 'Parent and grandparent super visa — Canada.ca', url: `${IRCC}/visit-canada/parent-grandparent-super-visa/about.html` },
    {
      title: 'Super visa: Host financial support and minimum income — Canada.ca',
      url: `${IRCC}/visit-canada/parent-grandparent-super-visa/forms-documents/host-financial-support.html`,
    },
    {
      title: 'Medical exam requirements for visitors — Canada.ca',
      url: `${IRCC}/application/medical-police/medical-exams/requirements-temporary-residents.html`,
    },
    { title: 'Biometrics: Where to give them — Canada.ca', url: `${IRCC}/biometrics/where-to-give.html` },
    { title: 'Biometrics: When to give them — Canada.ca', url: `${IRCC}/biometrics/when-to-give.html` },
    { title: 'IRCC fee list', url: 'https://ircc.canada.ca/english/information/fees/fees.asp' },
    { title: 'Check processing times — Canada.ca', url: `${IRCC}/application/check-processing-times.html` },
    { title: 'Minor children travelling to Canada — Canada.ca', url: `${IRCC}/visit-canada/minor-children-travelling.html` },
    { title: 'Prepare for arrival as a visitor — Canada.ca', url: `${IRCC}/visit-canada/prepare-arrival.html` },
    { title: 'Extend your stay in Canada as a visitor — Canada.ca', url: `${IRCC}/visit-canada/extend-stay.html` },
  ],
  steps: [
    {
      id: 'entry-check',
      title: 'Confirm the visitor visa (TRV) is the route',
      offsetDays: -200,
      durationDays: 7,
      dependsOn: [],
      documents: ['Passport'],
      prepare: ['How long you plan to stay', 'Whether a parent or grandparent is visiting a child or grandchild in Canada', 'Any earlier Canadian visas'],
      howTo:
        '1. China is on IRCC\'s list of visa-required countries, so a Chinese passport holder needs a visitor visa, also called a temporary resident visa (TRV); the eTA is not an option on this passport.\n2. A TRV can be valid for up to 10 years, or until the passport or biometrics expire, whichever comes first; the officer decides single or multiple entry.\n3. A valid TRV in an old passport can still be used alongside the new one while the visa is valid; check current on IRCC.\n4. A parent or grandparent of a Canadian citizen or permanent resident who wants to stay longer than 6 months at a time can look at the super visa in the next step.\n5. Run IRCC\'s "Find out if you need a visa or eTA" tool once to confirm; the answer decides the rest of this plan.',
    },
    {
      id: 'super-visa',
      title: 'Decide on a super visa instead',
      offsetDays: -180,
      durationDays: 14,
      conditions: ['Only if you are a parent or grandparent of a Canadian citizen or permanent resident and want to stay longer than 6 months at a time'],
      dependsOn: ['entry-check'],
      documents: ["Host's notice of assessment", "Proof of host's Canadian citizenship or permanent residence"],
      prepare: [
        "Your child's or grandchild's family size, counted the way IRCC asks",
        'Their income against the minimum on the host financial support page',
        'Proof of your relationship, such as the birth certificate (出生医学证明) or household register (户口簿)',
      ],
      howTo:
        '1. The super visa lets a parent or grandparent stay for 5 years at a time, with multiple entries for up to 10 years.\n2. For 6 months or less, IRCC points to the regular visitor visa instead.\n3. The child or grandchild in Canada meets a minimum income for their family size and signs a promise of financial support; check the current table on the host financial support page.\n4. The super visa also asks for private medical insurance and an immigration medical exam; the next steps cover them.\n5. The application fee is the same as a visitor visa on the IRCC fee list.',
    },
    {
      id: 'documents',
      title: 'Gather passport, funds and ties papers',
      offsetDays: -170,
      durationDays: 14,
      dependsOn: ['entry-check'],
      documents: ['Passport', 'Bank statements', 'Employment or leave letter', 'Digital photo'],
      prepare: [
        'Passport valid at least 6 months past the travel date',
        'Bank statements with several months of history, deposit or property certificates',
        'Employment letter with approved leave, business licence (营业执照), or retirement certificate (退休证)',
        'Previous passports and visas used to travel in the last 10 years',
        'Certified English or French translations of Chinese documents',
      ],
      howTo:
        '1. IRCC suggests renewing the passport first if it expires within 6 months of the travel date.\n2. The officer looks at funds for the trip and ties that bring you back: job, family, property.\n3. Documents not in English or French are uploaded with a translation and the translator\'s affidavit or certification; check current rules on IRCC.\n4. After a short questionnaire, the IRCC account gives a personalized checklist; follow it over this list.',
    },
    {
      id: 'host-letter',
      title: 'Ask your host for an invitation letter and status proof',
      offsetDays: -170,
      durationDays: 14,
      conditions: ['Only if visiting family or friends in Canada'],
      dependsOn: ['entry-check'],
      documents: ['Letter of invitation', "Copy of host's Canadian status document"],
      prepare: [
        "Host's full name, date of birth, address, phone and job title",
        "Copy of the host's Canadian passport, citizenship certificate, PR card or permit",
        'Purpose and length of the visit, where you will stay and who pays',
        "Names and dates of birth of the host's spouse and dependants",
      ],
      howTo:
        '1. A letter of invitation helps but does not decide the application.\n2. IRCC suggests it covers you (name, date of birth, address, relationship, purpose, length, where you stay, how you pay, when you leave) and the host (name, date of birth, address and phone, job, status in Canada with a copy of proof, family details).\n3. For a super visa, it adds the host\'s signed promise of financial support for the whole visit and proof of income.\n4. The host sends a signed scan to upload.',
    },
    {
      id: 'child-docs',
      title: "Prepare a child's birth certificate and consent letter",
      offsetDays: -170,
      durationDays: 14,
      ages: { from: 0, to: 17 },
      conditions: ['Only if a child under 18 is travelling'],
      dependsOn: [],
      documents: ["Child's passport", 'Birth certificate (出生医学证明)', 'Parental consent letter'],
      prepare: [
        "Both parents' names, addresses and phone numbers",
        'Signed consent from the parent not travelling, or from both if the child travels with someone else',
        'Copies of both parents\' ID or passports',
      ],
      howTo:
        '1. Each child applies on their own, with their own passport.\n2. IRCC and border officers may ask for a consent letter when a child travels with one parent or with another adult; include contact details of the parent or parents not travelling.\n3. Children under 14 are exempt from biometrics.\n4. The IRCC page on minor children travelling lists what to bring.',
    },
    {
      id: 'super-insurance',
      title: 'Buy the 1-year medical insurance for the super visa',
      offsetDays: -140,
      durationDays: 14,
      conditions: ['Only if you are applying for a super visa'],
      dependsOn: ['super-visa'],
      documents: ['Proof of private medical insurance'],
      prepare: ['Planned date of entry', 'A Canadian insurer, or an insurer outside Canada approved by the minister', 'Pre-existing conditions to declare'],
      howTo:
        '1. The super visa asks for private medical insurance valid for at least 1 year from entry, with at least $100,000 of emergency coverage.\n2. It comes from a Canadian insurance company or a company outside Canada approved by the minister; a Chinese insurer only counts if it is on that list.\n3. It is paid in full, or in instalments with a deposit; IRCC does not accept quotes.',
    },
    {
      id: 'medical',
      title: 'Take the immigration medical exam with a panel physician',
      offsetDays: -140,
      durationDays: 21,
      validForDays: 365,
      conditions: ['Only if you are applying for a super visa, or IRCC asks for an exam'],
      dependsOn: ['super-visa'],
      documents: ['Medical exam confirmation'],
      prepare: ['An IRCC panel physician clinic in China or where you live', 'Passport, glasses, medical records and list of medications'],
      howTo:
        '1. Super visa applicants take an immigration medical exam with an IRCC-approved panel physician; there are panel clinics in several Chinese cities, listed on IRCC.\n2. Visitors staying 6 months or less usually need none; for longer stays IRCC checks where you lived in the past year.\n3. Results are valid for 12 months, so book close to the application.',
    },
    {
      id: 'apply',
      title: 'Submit the application online through IRCC',
      offsetDays: -120,
      durationDays: 7,
      dependsOn: ['documents', 'host-letter', 'child-docs', 'super-insurance', 'medical'],
      documents: ['Application confirmation', 'Fee receipt'],
      prepare: [
        'IRCC account (IRCC Portal)',
        'Visa fee and biometrics fee, paid together',
        'Scans of everything on the personalized checklist',
      ],
      howTo:
        '1. Visitor visas are applied for online through the IRCC account; paper is only for people who cannot apply online, such as for a disability.\n2. The IRCC fee list shows CAD $100 for a visitor visa (super visa included) and CAD $85 for biometrics per person, with family maximums; check current before paying.\n3. Pay the biometrics fee with the application, or processing waits.\n4. Applying from China or from a third country uses the same online form; only where you give biometrics and send the passport changes.',
    },
    {
      id: 'biometrics-china',
      title: 'Give biometrics at a visa application centre in China',
      offsetDays: -85,
      durationDays: 30,
      validForDays: 3652,
      ages: { from: 14, to: 79 },
      conditions: ['Only if you are in mainland China when applying, aged 14 to 79'],
      dependsOn: ['apply'],
      documents: ['Biometric instruction letter', 'Passport'],
      prepare: ['Appointment at the nearest centre', 'Check whether biometrics from the last 10 years are still on file'],
      howTo:
        '1. After the fee, IRCC sends a biometric instruction letter; you have 30 days from getting it to give fingerprints and photo.\n2. Canada visa application centres (VAC) in China are in cities including Beijing, Shanghai, Guangzhou, Chengdu, Chongqing, Wuhan, Shenyang, Hangzhou, Jinan, Kunming and Nanjing; book on the VAC site.\n3. Biometrics are given once every 10 years for temporary residence; a valid set on file means no new appointment.\n4. The VAC also handles sending the passport in later.',
    },
    {
      id: 'biometrics-abroad',
      title: 'Give biometrics in the country where you live',
      offsetDays: -85,
      durationDays: 30,
      validForDays: 3652,
      ages: { from: 14, to: 79 },
      conditions: ['Only if you live legally outside China, aged 14 to 79'],
      dependsOn: ['apply'],
      documents: ['Biometric instruction letter', 'Passport', 'Residence permit or visa for that country'],
      prepare: ['Proof of legal status where you live', 'Proof of ties there: job, study, lease'],
      howTo:
        '1. The online application is the same from any country; in it, give your current country of residence and status there.\n2. Biometrics go to a VAC in the country you apply from; IRCC says that if there is none, any other VAC can be used.\n3. People legally in the US can give biometrics at a US Application Support Center instead.\n4. The officer weighs ties to where you live; upload the residence permit.',
    },
    {
      id: 'decision',
      title: 'Wait for the decision and send the passport',
      offsetDays: -30,
      durationDays: 50,
      dependsOn: ['biometrics-china', 'biometrics-abroad'],
      documents: ['Passport request letter', 'Visitor visa', 'Passport'],
      prepare: ['Check the IRCC processing time for your country of residence', 'Watch the IRCC account for requests'],
      howTo:
        '1. Processing times vary by country of residence; IRCC posts current estimates.\n2. The 50 days here is only a planning estimate; move it to the posted time.\n3. If approved, IRCC asks for the passport; it goes through a VAC so the visa counterfoil can be put in, then comes back.\n4. Super visa holders get the visa counterfoil the same way; check the length and entries printed on it.',
    },
    {
      id: 'flights',
      title: 'Book flights and travel medical insurance',
      offsetDays: -21,
      durationDays: 7,
      dependsOn: ['decision'],
      documents: ['Flight itinerary', 'Travel insurance policy'],
      prepare: ['Visa dates and number of entries', 'Insurance for the whole stay, unless the super visa policy already covers it'],
      howTo:
        '1. Book after the visa is in the passport, so a refusal or delay does not cost the fare.\n2. Visitors are generally not covered by provincial health insurance; travel medical insurance for a regular visitor visa is recommended rather than asked for.\n3. Match the return date to the stay in the invitation letter.',
    },
    {
      id: 'arrival',
      title: 'Arrival: meet the border officer',
      offsetDays: 0,
      durationDays: 1,
      dependsOn: ['flights'],
      documents: ['Passport', 'Visitor visa', 'Letter of invitation', 'Proof of private medical insurance'],
      prepare: ['Host address and phone in Canada', 'Return ticket and proof of funds in carry-on', 'For a super visa, ask for a passport stamp'],
      howTo:
        '1. A Canada Border Services Agency (CBSA) officer checks identity, documents, funds, ties and plans to leave.\n2. Most visitors can stay up to 6 months; the officer may stamp the passport or issue a visitor record with the leave-by date.\n3. With no stamp, the stay ends 6 months after arrival, or when the passport expires if sooner.\n4. A super visa holder can stay 5 years at a time; at a kiosk airport, ask for a stamp as proof of the entry date.',
    },
    {
      id: 'extend',
      title: 'Apply for a visitor record to extend the stay',
      offsetDays: 150,
      durationDays: 14,
      conditions: ['Only if you want to stay past the date the officer gave you'],
      dependsOn: ['arrival'],
      documents: ['Visitor record', 'Passport', 'Bank statements'],
      prepare: ['Leave-by date from the stamp or visitor record', 'Reason for staying longer', 'Funds and insurance for the extra time'],
      howTo:
        '1. To stay longer as a visitor, apply online for a visitor record from inside Canada.\n2. IRCC asks for it at least 30 days before the current status expires; the IRCC fee list shows CAD $100 per person, check current.\n3. The date here assumes a 6-month stay; move it to 30 days before your real leave-by date.\n4. A visitor record is not a visa; leaving Canada and coming back still needs a valid visa.',
    },
    {
      id: 'leave',
      title: 'Leave on time and keep the records',
      offsetDays: 180,
      durationDays: 1,
      dependsOn: ['arrival'],
      documents: ['Passport', 'Boarding pass'],
      prepare: ['Copies of the visa, stamps and visitor record', 'Boarding passes'],
      howTo:
        '1. Leave by the date on the stamp or visitor record, or 6 months after arrival if there is neither.\n2. Keep the visa, stamps and boarding passes; the next application asks about travel in the last 10 years.\n3. A multiple-entry visa can be used again while it and the passport are valid.\n4. The 180 days here is an estimate; move it to your real departure.',
    },
  ],
};
