#!/usr/bin/env node
// Builds src/content/cities.ts from a GeoNames dump (CC BY 4.0, geonames.org).
// Usage: node scripts/build-cities.mjs <dir with cities1000.txt, admin1CodesASCII.txt, countryInfo.txt>
// Keeps: every Canadian and Chinese town of 1,000+, and cities of 50,000+ elsewhere.
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const dir = process.argv[2];
if (!dir) throw new Error('Pass the GeoNames dump directory.');

const lines = f => readFileSync(join(dir, f), 'utf8').split('\n').filter(l => l && !l.startsWith('#'));

const countries = new Map(lines('countryInfo.txt').map(l => {
  const c = l.split('\t');
  return [c[0], c[4]];
}));
const admins = new Map(lines('admin1CodesASCII.txt').map(l => {
  const [code, name] = l.split('\t');
  return [code, name];
}));

const SKIP = new Set(['PPLX', 'PPLH', 'PPLQ', 'PPLW', 'PPLCH']);
const CJK = /[一-鿿]/;
const keep = (cc, pop) => (cc === 'CA' || cc === 'CN' ? pop >= 1000 : pop >= 50000);

const rows = [];
for (const l of lines('cities1000.txt')) {
  const c = l.split('\t');
  const [name, alt, fclass, fcode, cc, a1, pop] = [c[1], c[3], c[6], c[7], c[8], c[10], Number(c[14])];
  if (fclass !== 'P' || SKIP.has(fcode) || !keep(cc, pop)) continue;
  const zh = alt.split(',').find(n => CJK.test(n)) ?? '';
  rows.push({ name, zh, cc, admin: admins.get(`${cc}.${a1}`) ?? '', pop });
}
rows.sort((a, b) => b.pop - a.pop);

const regions = [];
const regionIndex = new Map();
const regionOf = (cc, admin) => {
  const key = `${cc}\t${admin}`;
  if (!regionIndex.has(key)) {
    regionIndex.set(key, regions.length);
    regions.push(`${admin}\t${countries.get(cc) ?? cc}`);
  }
  return regionIndex.get(key);
};
const body = rows.map(r => `${r.name}\t${regionOf(r.cc, r.admin)}\t${r.zh}`).join('\n');

const out = `// Generated by scripts/build-cities.mjs from GeoNames (CC BY 4.0). Don't edit.
// Rows are "name\\tregion\\tchinese name", biggest first; regions are "admin\\tcountry".
export const REGIONS = ${JSON.stringify(regions.join('\n'))};
export const CITIES = ${JSON.stringify(body)};
`;
writeFileSync(new URL('../src/content/cities.ts', import.meta.url), out);
console.log(`${rows.length} places, ${regions.length} regions, ${(out.length / 1024).toFixed(0)} KB`);
